// architecture.mjs — generate ARCHITECTURE.md from cluster output.
//
// Exports:
//   generate({ clusters, specs, existingDocs }): GeneratorResult
//
// Output: per-cluster paragraph + mermaid-graph-placeholder marker.

import path from 'node:path';

/**
 * Build a scope block for a section.
 */
function scopeBlock(srcGlobs, reason) {
  const srcList = srcGlobs.map(g => `"${g}"`).join(', ');
  return [
    '<!-- autospec-doc-scope:',
    `  src: [${srcList}]`,
    reason ? `  reason: "${reason.replace(/"/g, "'")}"` : '',
    '  generated: true',
    '-->',
  ].filter(l => l !== '').join('\n');
}

/**
 * Generate ARCHITECTURE.md content.
 */
export function generate({ clusters, specs = [], existingDocs = {} }) {
  const significant = clusters?.significant || [];
  const trivial = clusters?.trivial || [];

  const section_anchors = [];
  const lines = [
    '# Architecture',
    '',
    '> *Auto-generated by autospec reverse-engineer pipeline.*',
    '> *Describes the system shape, module graph, and component responsibilities.*',
    '',
  ];

  // ── Module graph section ──────────────────────────────────────────────────
  const allSrc = significant.flatMap(u => u.files.map(f => path.basename(f)));
  const graphHeading = '## Module Graph';
  section_anchors.push(graphHeading);

  lines.push(
    graphHeading,
    '',
    scopeBlock(allSrc.length > 0 ? allSrc : ['*'], 'Module dependency graph covering all significant units'),
    '',
    '<!-- mermaid-graph-placeholder -->',
    '',
    '> *Mermaid diagram will be generated in Phase 7 (`gen-arch-diagram.mjs`).*',
    '',
  );

  // ── Per-module sections ───────────────────────────────────────────────────
  if (significant.length > 0) {
    const modulesHeading = '## Modules';
    section_anchors.push(modulesHeading);
    lines.push(modulesHeading, '');

    for (const unit of significant) {
      const unitHeading = `### \`${unit.slug}\``;
      section_anchors.push(unitHeading);
      const srcGlobs = unit.files.map(f => path.basename(f));

      lines.push(
        unitHeading,
        '',
        scopeBlock(srcGlobs, `Module ${unit.slug} architecture coverage`),
        '',
        `**Language:** ${unit.language}`,
        `**Files:** ${unit.files.map(f => `\`${path.basename(f)}\``).join(', ')}`,
        `**Exports:** ${(unit.exports || []).length}`,
        `**Entry points:** ${(unit.entry_points || []).length}`,
        `**Significance:** ${(unit.reasons || []).join(', ')}`,
        '',
      );

      if (unit.importedBy && unit.importedBy.length > 0) {
        lines.push(
          '**Imported by:**',
          '',
          ...unit.importedBy.map(f => `- \`${path.basename(f)}\``),
          '',
        );
      }

      lines.push(
        '> *Add a description of this module\'s responsibility here.*',
        '',
      );
    }
  }

  // ── Trivial files section ─────────────────────────────────────────────────
  if (trivial.length > 0) {
    const trivialHeading = '## Supporting Files';
    section_anchors.push(trivialHeading);
    const trivialSrc = trivial.map(t => path.basename(t.filePath));

    lines.push(
      trivialHeading,
      '',
      scopeBlock(trivialSrc, 'Trivial/supporting files bubbled into parent modules'),
      '',
      'These files have no public exports and are not imported by 3+ modules.',
      'They are included within their parent module\'s responsibility.',
      '',
    );

    for (const t of trivial) {
      const bubble = t.bubbledInto ? ` → \`${path.basename(t.bubbledInto)}\`` : '';
      lines.push(`- \`${path.basename(t.filePath)}\`${bubble}`);
    }
    lines.push('');
  }

  return {
    path: 'docs/ARCHITECTURE.md',
    content: lines.join('\n'),
    section_anchors,
  };
}
