// user-manual.mjs — generate USER_MANUAL.md sections from cluster output.
//
// Exports:
//   generate({ clusters, specs, existingDocs }): GeneratorResult
//
// GeneratorResult:
//   { path: string, content: string, section_anchors: string[] }
//
// Output: one section per CLI entry point + one section per HTTP route group.
// Every generated section contains an autospec-doc-scope comment.

import path from 'node:path';

/**
 * Build a scope block for a section.
 * @param {string[]} srcGlobs - relative glob patterns
 * @param {string} reason
 * @returns {string}
 */
function scopeBlock(srcGlobs, reason) {
  const srcList = srcGlobs.map(g => `"${g}"`).join(', ');
  return [
    '<!-- autospec-doc-scope:',
    `  src: [${srcList}]`,
    reason ? `  reason: "${reason.replace(/"/g, "'")}"` : '',
    '  generated: true',
    '-->',
  ].filter(l => l !== '').join('\n');
}

/**
 * Collect all CLI entry points and HTTP routes from cluster units.
 * @param {ClusterUnit[]} significant
 * @returns {{ cli: Array<{unit, ep}>, http: Array<{unit, ep}> }}
 */
function collectEntries(significant) {
  const cli = [];
  const http = [];
  for (const unit of significant) {
    for (const ep of (unit.entry_points || [])) {
      if (ep.kind === 'cli_command') cli.push({ unit, ep });
      else if (ep.kind === 'http_route') http.push({ unit, ep });
    }
  }
  return { cli, http };
}

/**
 * Group HTTP routes by path prefix (first two segments).
 * @param {Array<{unit, ep}>} httpEntries
 * @returns {Map<string, Array<{unit, ep}>>}
 */
function groupHttpRoutes(httpEntries) {
  const groups = new Map();
  for (const entry of httpEntries) {
    const parts = entry.ep.identifier.split('/').filter(Boolean);
    const groupKey = parts.length > 0 ? `/${parts[0]}` : '/';
    if (!groups.has(groupKey)) groups.set(groupKey, []);
    groups.get(groupKey).push(entry);
  }
  return groups;
}

/**
 * Generate USER_MANUAL.md content.
 *
 * @param {{
 *   clusters: { significant: ClusterUnit[], trivial: any[] },
 *   specs: object[],
 *   existingDocs: { [path: string]: string }
 * }} opts
 * @returns {{ path: string, content: string, section_anchors: string[] }}
 */
export function generate({ clusters, specs = [], existingDocs = {} }) {
  const significant = clusters?.significant || [];
  const { cli, http } = collectEntries(significant);
  const httpGroups = groupHttpRoutes(http);

  const section_anchors = [];
  const lines = [
    '# User Manual',
    '',
    '> *Auto-generated by autospec reverse-engineer pipeline.*',
    '> *Edit sections marked with `generated: true` with care — they will be regenerated.*',
    '',
  ];

  // ── CLI entry points ────────────────────────────────────────────────────────
  if (cli.length > 0) {
    lines.push('## CLI Commands', '');
    for (const { unit, ep } of cli) {
      const heading = `### \`${ep.identifier}\``;
      section_anchors.push(heading);
      const srcGlobs = unit.files.map(f => path.basename(f));
      lines.push(
        heading,
        '',
        scopeBlock(srcGlobs, `CLI entry point from ${path.basename(unit.files[0])}`),
        '',
        `**Entry point:** \`${ep.identifier}\` (line ${ep.line})`,
        `**Module:** \`${unit.slug}\``,
        '',
        '#### Usage',
        '',
        '```',
        `# ${ep.identifier}`,
        '```',
        '',
        '#### Description',
        '',
        '> *Add a description of this command here.*',
        '',
      );
    }
  }

  // ── HTTP route groups ───────────────────────────────────────────────────────
  if (httpGroups.size > 0) {
    lines.push('## HTTP API', '');
    for (const [groupPrefix, entries] of httpGroups) {
      const heading = `### Routes: \`${groupPrefix}\``;
      section_anchors.push(heading);
      const allFiles = [...new Set(entries.map(e => path.basename(e.unit.files[0])))];
      lines.push(
        heading,
        '',
        scopeBlock(allFiles, `HTTP routes under ${groupPrefix}`),
        '',
      );
      for (const { unit, ep } of entries) {
        lines.push(`- \`${ep.identifier}\` (${unit.slug}, line ${ep.line})`);
      }
      lines.push('', '> *Add documentation for these routes here.*', '');
    }
  }

  // ── Fallback if no entry points found ────────────────────────────────────────
  if (cli.length === 0 && httpGroups.size === 0) {
    const heading = '## Getting Started';
    section_anchors.push(heading);
    const allSrc = significant.slice(0, 3).flatMap(u => u.files.map(f => path.basename(f)));
    lines.push(
      heading,
      '',
      scopeBlock(allSrc.length > 0 ? allSrc : ['*'], 'Overview section covering main source files'),
      '',
      '> *No CLI or HTTP entry points detected. Add usage documentation here.*',
      '',
    );
  }

  return {
    path: 'docs/USER_MANUAL.md',
    content: lines.join('\n'),
    section_anchors,
  };
}
