-- Registry schema for per-user keys and per-key usage.
--
-- RUN THIS AS THE OWNER ROLE, NOT AS A SUPERUSER.
--     PGPASSWORD=... psql -h <host> -p <port> -U <owner-role> -d <db> \
--          -v ON_ERROR_STOP=1 -f 001-schema.sql
--
-- Why it matters: 000-provision.sql set ALTER DEFAULT PRIVILEGES *FOR ROLE
-- <owner>*, and those defaults apply only to objects that role creates. Apply
-- this as a superuser instead and the application role receives no privileges
-- at all -- which presents later as a mystifying "permission denied for table"
-- long after anyone remembers who ran the migration.

\set ON_ERROR_STOP on

BEGIN;

CREATE TABLE IF NOT EXISTS llm.schema_migrations (
  filename    text PRIMARY KEY,
  applied_at  timestamptz NOT NULL DEFAULT now()
);

-- `sub` is the identity provider's subject and the ONLY trustworthy identity
-- claim. email and display_name are presentation only: they are refreshed from
-- the verified token on each login and are never used for authorization,
-- because the provider allows a user to change them.
CREATE TABLE IF NOT EXISTS llm.users (
  sub            text PRIMARY KEY,
  email          text,
  display_name   text,
  first_seen_at  timestamptz NOT NULL DEFAULT now(),
  last_login_at  timestamptz
);

-- key_id is public: printed in the dashboard, carried on every usage row, and
-- the lookup key for authentication. secret_hash is sha256 of a 160-bit random
-- secret shown exactly once. A subject identifier must never appear here as a
-- credential.
CREATE TABLE IF NOT EXISTS llm.api_keys (
  key_id        text PRIMARY KEY,
  sub           text NOT NULL REFERENCES llm.users(sub) ON DELETE CASCADE,
  secret_hash   text NOT NULL,
  label         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz,
  revoked_at    timestamptz,
  last_used_at  timestamptz
);
CREATE INDEX IF NOT EXISTS api_keys_sub_idx ON llm.api_keys (sub);

-- One row per completed request.
--
-- event_id is generated by the emitting node so that a buffered flush which
-- partially succeeded cannot double-count on retry -- at-least-once delivery
-- made idempotent by the primary key.
--
-- truncated marks a request whose client disconnected before the terminal
-- response chunk arrived, so its token counts are genuinely UNKNOWN. Those rows
-- keep NULL counts and are aggregated separately; they are never estimated and
-- never reported as zero.
CREATE TABLE IF NOT EXISTS llm.usage_events (
  event_id           uuid PRIMARY KEY,
  ts                 timestamptz NOT NULL,
  key_id             text NOT NULL,
  sub                text,
  model              text,
  upstream           text NOT NULL DEFAULT 'local',
  endpoint           text,
  prompt_tokens      integer,
  completion_tokens  integer,
  cached_tokens      integer,
  prompt_ms          double precision,
  predicted_ms       double precision,
  status_code        integer,
  streamed           boolean NOT NULL DEFAULT false,
  truncated          boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS usage_events_key_ts_idx ON llm.usage_events (key_id, ts DESC);
CREATE INDEX IF NOT EXISTS usage_events_sub_ts_idx ON llm.usage_events (sub, ts DESC);

-- A VIEW rather than a rollup table, deliberately. This node has two inference
-- slots; it cannot physically generate enough rows for an aggregate scan to
-- matter, and a rollup job is one more thing that fails silently and leaves the
-- dashboard confidently reporting stale totals.
CREATE OR REPLACE VIEW llm.usage_daily AS
SELECT date_trunc('day', ts)                             AS day,
       key_id,
       sub,
       model,
       count(*)                                          AS requests,
       count(*) FILTER (WHERE truncated)                 AS truncated_requests,
       sum(prompt_tokens)                                AS prompt_tokens,
       sum(completion_tokens)                            AS completion_tokens,
       sum(cached_tokens)                                AS cached_tokens,
       sum(prompt_ms)                                    AS prompt_ms,
       sum(predicted_ms)                                 AS predicted_ms
  FROM llm.usage_events
 GROUP BY 1, 2, 3, 4;

-- The view is created by the owner, so the table default privileges do not
-- cover it; grant explicitly.
GRANT SELECT ON llm.usage_daily TO llmgw_app, llmgw_read;

INSERT INTO llm.schema_migrations (filename) VALUES ('001-schema.sql')
  ON CONFLICT (filename) DO NOTHING;

COMMIT;
