//! AAR spec section 10: edit guards, thrashing detection and stop conditions.

use autospec_core::aar::guards::{
    evaluate_stop, EditAction, EditGuard, EditPolicy, ExecutionProgress, StepEvent, StopPolicy,
    StopReason, ThrashDetector, ThrashResponse, ThrashSignal, ThrashThresholds,
};

fn step(action: EditAction, recorded_finding: bool, tokens: u64, digest: &str) -> StepEvent {
    StepEvent {
        action,
        recorded_finding,
        cumulative_tokens: tokens,
        state_digest: digest.to_string(),
    }
}

#[test]
fn spec_default_edit_policy_matches_the_documented_values() {
    let policy = EditPolicy::default();

    assert!(policy.require_read_before_edit);
    assert!(policy.require_reread_after_edit);
    assert_eq!(policy.max_edit_lines, 150);
    assert_eq!(policy.max_new_file_lines, 300);
    assert!(policy.one_logical_change_per_step);
}

#[test]
fn editing_an_unread_file_is_a_violation() {
    let mut guard = EditGuard::new(EditPolicy::default());

    let violations = guard.observe(&EditAction::Edit {
        path: "src/lib.rs".to_string(),
        lines: 10,
    });

    assert_eq!(violations.len(), 1);
    assert_eq!(violations[0].code, "read_before_edit");
}

#[test]
fn reading_first_clears_the_read_before_edit_guard() {
    let mut guard = EditGuard::new(EditPolicy::default());

    guard.observe(&EditAction::Read {
        path: "src/lib.rs".to_string(),
    });
    let violations = guard.observe(&EditAction::Edit {
        path: "src/lib.rs".to_string(),
        lines: 10,
    });

    assert!(violations.is_empty());
}

#[test]
fn an_oversized_edit_is_a_violation() {
    let mut guard = EditGuard::new(EditPolicy::default());
    guard.observe(&EditAction::Read {
        path: "src/lib.rs".to_string(),
    });

    let violations = guard.observe(&EditAction::Edit {
        path: "src/lib.rs".to_string(),
        lines: 400,
    });

    assert_eq!(violations[0].code, "max_edit_lines");
}

#[test]
fn an_oversized_new_file_is_a_violation() {
    let mut guard = EditGuard::new(EditPolicy::default());

    let violations = guard.observe(&EditAction::Create {
        path: "src/new.rs".to_string(),
        lines: 900,
    });

    assert_eq!(violations[0].code, "max_new_file_lines");
}

/// Exceptions exist, but only where an operator wrote one down with a reason.
#[test]
fn an_explicit_exception_suppresses_the_guard() {
    let policy = EditPolicy::default()
        .with_exception("src/generated.rs", "generated by the schema tool")
        .expect("reason supplied");
    let mut guard = EditGuard::new(policy);

    let violations = guard.observe(&EditAction::Edit {
        path: "src/generated.rs".to_string(),
        lines: 5_000,
    });

    assert!(violations.is_empty());
    assert_eq!(
        guard.policy().exception_reason("src/generated.rs"),
        Some("generated by the schema tool")
    );
}

#[test]
fn an_exception_without_a_reason_is_rejected() {
    assert!(EditPolicy::default().with_exception("src/a.rs", "  ").is_err());
}

#[test]
fn a_second_edit_in_one_step_breaks_the_one_logical_change_rule() {
    let mut guard = EditGuard::new(EditPolicy::default());
    for path in ["src/a.rs", "src/b.rs"] {
        guard.observe(&EditAction::Read {
            path: path.to_string(),
        });
    }

    guard.observe(&EditAction::Edit {
        path: "src/a.rs".to_string(),
        lines: 5,
    });
    let violations = guard.observe(&EditAction::Edit {
        path: "src/b.rs".to_string(),
        lines: 5,
    });

    assert!(violations
        .iter()
        .any(|violation| violation.code == "one_logical_change_per_step"));
}

#[test]
fn creating_a_file_after_an_edit_also_breaks_the_one_logical_change_rule() {
    let mut guard = EditGuard::new(EditPolicy::default());
    guard.observe(&EditAction::Read {
        path: "src/a.rs".to_string(),
    });
    guard.observe(&EditAction::Edit {
        path: "src/a.rs".to_string(),
        lines: 5,
    });

    let violations = guard.observe(&EditAction::Create {
        path: "src/b.rs".to_string(),
        lines: 20,
    });

    assert!(violations
        .iter()
        .any(|violation| violation.code == "one_logical_change_per_step"));
}

#[test]
fn a_single_file_creation_in_a_step_is_allowed() {
    let mut guard = EditGuard::new(EditPolicy::default());

    let violations = guard.observe(&EditAction::Create {
        path: "src/new.rs".to_string(),
        lines: 20,
    });

    assert!(violations.is_empty());
}

#[test]
fn an_edit_without_a_re_read_is_caught_at_the_step_boundary() {
    let mut guard = EditGuard::new(EditPolicy::default());
    guard.observe(&EditAction::Read {
        path: "src/a.rs".to_string(),
    });
    guard.observe(&EditAction::Edit {
        path: "src/a.rs".to_string(),
        lines: 5,
    });

    assert_eq!(guard.pending_reread(), vec!["src/a.rs"]);
    let violations = guard.end_step();

    assert_eq!(violations[0].code, "reread_after_edit_missing");
}

#[test]
fn re_reading_after_an_edit_clears_the_step_boundary_check() {
    let mut guard = EditGuard::new(EditPolicy::default());
    guard.observe(&EditAction::Read {
        path: "src/a.rs".to_string(),
    });
    guard.observe(&EditAction::Edit {
        path: "src/a.rs".to_string(),
        lines: 5,
    });
    guard.observe(&EditAction::Read {
        path: "src/a.rs".to_string(),
    });

    assert!(guard.end_step().is_empty());
}

#[test]
fn repeated_reads_without_findings_are_detected() {
    let mut detector = ThrashDetector::with_defaults();
    let read = EditAction::Read {
        path: "src/a.rs".to_string(),
    };

    detector.observe(&step(read.clone(), false, 100, "s1"));
    detector.observe(&step(read.clone(), false, 200, "s1"));
    let findings = detector.observe(&step(read, false, 300, "s1"));

    assert_eq!(
        findings[0].signal,
        ThrashSignal::RepeatedReadsWithoutFindings
    );
    assert_eq!(findings[0].response, ThrashResponse::SummarizeState);
}

#[test]
fn a_read_that_produces_a_finding_resets_the_counter() {
    let mut detector = ThrashDetector::with_defaults();
    let read = EditAction::Read {
        path: "src/a.rs".to_string(),
    };

    detector.observe(&step(read.clone(), false, 100, "s1"));
    detector.observe(&step(read.clone(), true, 200, "s2"));
    let findings = detector.observe(&step(read, false, 300, "s3"));

    assert!(findings.is_empty());
}

#[test]
fn equivalent_searches_are_detected_regardless_of_spacing_and_case() {
    let mut detector = ThrashDetector::with_defaults();

    detector.observe(&step(
        EditAction::Search {
            query: "queue parser panic".to_string(),
        },
        false,
        10,
        "s1",
    ));
    detector.observe(&step(
        EditAction::Search {
            query: "Queue   Parser  Panic".to_string(),
        },
        false,
        20,
        "s1",
    ));
    let findings = detector.observe(&step(
        EditAction::Search {
            query: "QUEUE PARSER PANIC".to_string(),
        },
        false,
        30,
        "s1",
    ));

    assert_eq!(findings[0].signal, ThrashSignal::EquivalentSearches);
}

#[test]
fn identical_tests_with_unchanged_inputs_are_detected() {
    let mut detector = ThrashDetector::with_defaults();
    let run = EditAction::RunTests {
        command: "cargo test -p autospec-core".to_string(),
        passed: false,
    };

    detector.observe(&step(run.clone(), false, 10, "s1"));
    detector.observe(&step(run.clone(), false, 20, "s1"));
    let findings = detector.observe(&step(run, false, 30, "s1"));

    assert!(findings
        .iter()
        .any(|finding| finding.signal == ThrashSignal::IdenticalTestsWithoutChangedInputs));
}

#[test]
fn a_re_proved_conclusion_triggers_a_clean_fork() {
    let mut detector = ThrashDetector::with_defaults();
    let conclude = EditAction::Conclude {
        claim: "the parser is the cause".to_string(),
    };

    for tokens in [10, 20, 30] {
        detector.observe(&step(conclude.clone(), false, tokens, "s1"));
    }
    let findings = detector.observe(&step(conclude, false, 40, "s1"));

    let finding = findings
        .iter()
        .find(|finding| finding.signal == ThrashSignal::RepeatedConclusions)
        .expect("repeated conclusion detected");
    assert_eq!(finding.response, ThrashResponse::CleanFork);
}

#[test]
fn token_growth_without_a_state_transition_escalates_to_the_coordinator() {
    let mut detector = ThrashDetector::new(ThrashThresholds {
        tokens_without_transition: 1_000,
        ..ThrashThresholds::default()
    });

    detector.observe(&step(
        EditAction::Search {
            query: "a".to_string(),
        },
        false,
        0,
        "s1",
    ));
    let findings = detector.observe(&step(
        EditAction::Search {
            query: "b".to_string(),
        },
        false,
        5_000,
        "s1",
    ));

    let finding = findings
        .iter()
        .find(|finding| finding.signal == ThrashSignal::TokenGrowthWithoutStateTransition)
        .expect("token growth detected");
    assert_eq!(finding.response, ThrashResponse::CoordinatorIntervention);
}

#[test]
fn a_state_transition_resets_the_token_growth_window() {
    let mut detector = ThrashDetector::new(ThrashThresholds {
        tokens_without_transition: 1_000,
        ..ThrashThresholds::default()
    });

    detector.observe(&step(
        EditAction::Search {
            query: "a".to_string(),
        },
        false,
        0,
        "s1",
    ));
    let findings = detector.observe(&step(
        EditAction::Search {
            query: "b".to_string(),
        },
        false,
        5_000,
        "s2",
    ));

    assert!(findings
        .iter()
        .all(|finding| finding.signal != ThrashSignal::TokenGrowthWithoutStateTransition));
}

/// The rule agents ignore most often: budget left is not a reason to continue.
#[test]
fn meeting_every_acceptance_criterion_stops_execution_immediately() {
    let reason = evaluate_stop(
        &StopPolicy::default(),
        &ExecutionProgress {
            steps: 2,
            acceptance_criteria_total: 3,
            acceptance_criteria_met: 3,
            ..ExecutionProgress::default()
        },
    );

    assert_eq!(reason, Some(StopReason::AcceptanceMet));
    assert!(reason.expect("stopped").is_success());
}

#[test]
fn exhausting_steps_tokens_or_retries_stops_execution() {
    let policy = StopPolicy::default();

    assert_eq!(
        evaluate_stop(
            &policy,
            &ExecutionProgress {
                steps: policy.max_steps,
                ..ExecutionProgress::default()
            }
        ),
        Some(StopReason::MaxSteps)
    );
    assert_eq!(
        evaluate_stop(
            &policy,
            &ExecutionProgress {
                tokens: policy.max_tokens,
                ..ExecutionProgress::default()
            }
        ),
        Some(StopReason::MaxTokens)
    );
    assert_eq!(
        evaluate_stop(
            &policy,
            &ExecutionProgress {
                retries: policy.max_retries + 1,
                ..ExecutionProgress::default()
            }
        ),
        Some(StopReason::MaxRetries)
    );
}

#[test]
fn an_unresolved_thrash_signal_stops_execution() {
    let reason = evaluate_stop(
        &StopPolicy::default(),
        &ExecutionProgress {
            steps: 1,
            unresolved_thrash_signals: 1,
            ..ExecutionProgress::default()
        },
    );

    assert_eq!(reason, Some(StopReason::Thrashing));
    assert!(!reason.expect("stopped").is_success());
}

#[test]
fn execution_with_budget_remaining_and_work_outstanding_continues() {
    let reason = evaluate_stop(
        &StopPolicy::default(),
        &ExecutionProgress {
            steps: 3,
            acceptance_criteria_total: 4,
            acceptance_criteria_met: 2,
            ..ExecutionProgress::default()
        },
    );

    assert_eq!(reason, None);
}
