//! Integration test for issue #3663: a blanket "keep both sides" hunk
//! strategy corrupted nine `.sha256` checksum golden files.
//!
//! The rule: a conflict-resolution strategy is a property of the file, not a
//! property of the merge. This test drives the policy against the exact
//! incident shape — a population of single-value goldens, some corrupted by
//! keep-both — plus the four acceptance criteria:
//!
//! 1. auto-resolution refuses any file it cannot classify (no default);
//! 2. a generated header names the generator, and the resolver routes the
//!    file to regeneration;
//! 3. where a repository has a generator, the resolution step runs it and
//!    takes the result;
//! 4. the gate set includes a shape check for single-value files — a
//!    `.sha256` with two lines is malformed regardless of its contents.

use autospec_core::conflict_resolution::{
    auto_resolve, check_single_value_file, classify_file, resolution_for, shape_gate,
    AutoResolutionError, AutoResolutionOutcome, FileShape, GeneratorRegistry, GeneratorRunner,
    ResolutionPlan,
};

const HASH_A: &str = "89be3092852d83aedf6baaa04ee8fdba6288a24cd2a72cbfe22367e2967b3c4e";
const HASH_B: &str = "46151f077983878b27168cd89458df806e71b23426d633cd60d1121f58878c62";
const GEN: &str = "scripts/gen-skill-goldens.sh";

fn not_readable(_path: &str) -> Option<String> {
    None
}

/// A fake generator: "running" it rewrites every golden to a known value.
struct FakeGenerator {
    invocations: std::sync::Mutex<Vec<String>>,
}

impl FakeGenerator {
    fn new() -> Self {
        Self {
            invocations: std::sync::Mutex::new(Vec::new()),
        }
    }

    fn invocation_count(&self) -> usize {
        self.invocations.lock().unwrap().len()
    }
}

impl GeneratorRunner for FakeGenerator {
    fn run(&self, generator: &str) -> Result<(), String> {
        self.invocations.lock().unwrap().push(generator.to_string());
        Ok(())
    }
}

fn golden(path_suffix: &str) -> String {
    format!("tests/fixtures/skill-goldens/{path_suffix}")
}

#[test]
fn the_incident_population_is_detected_by_the_shape_gate() {
    // Nine corrupted goldens (the #3663 shape: old hash + new hash) mixed
    // with clean ones and non-single-value files. The gate must name exactly
    // the corrupted members — wc -l == 2 is the whole detection.
    let mut files = Vec::new();
    for i in 0..9u16 {
        files.push((
            golden(&format!("skill-{i}.SKILL.md.sha256")),
            format!("{HASH_A}\n{HASH_B}"),
        ));
    }
    files.push((golden("clean.SKILL.md.sha256"), HASH_A.to_string()));
    files.push((
        "docs/CHANGELOG.md".to_string(),
        format!("{HASH_A}\n{HASH_B}\n"), // a two-line changelog is fine
    ));
    files.push((
        "src/lib.rs".to_string(),
        "pub mod a;\npub mod b;\n".to_string(),
    ));

    let findings = shape_gate(&files);
    assert_eq!(findings.len(), 9);
    for finding in &findings {
        assert!(finding.path.ends_with(".sha256"), "{}", finding.path);
        assert!(
            !finding.path.ends_with("clean.SKILL.md.sha256"),
            "{}",
            finding.path
        );
        assert!(finding.detail.contains("2 lines"), "{}", finding.detail);
    }
}

#[test]
fn auto_resolution_refuses_what_it_cannot_classify() {
    let registry = GeneratorRegistry::new();
    let generator = FakeGenerator::new();
    let outcome = auto_resolve(
        "src/something/else.yaml",
        "a: 1\nb: 2\n",
        &registry,
        &generator,
        &not_readable,
    );
    assert!(
        matches!(
            outcome,
            Err(AutoResolutionError::RefusedUnclassifiable { .. })
        ),
        "an unclassifiable file must be refused, got {outcome:?}"
    );
    assert_eq!(generator.invocation_count(), 0);
}

#[test]
fn a_generated_header_routes_the_file_to_regeneration_not_text_merge() {
    let registry = GeneratorRegistry::new();
    let generator = FakeGenerator::new();
    let content = format!("// Generated by {GEN}\npub struct Bindings;\n");
    let read_back = |_path: &str| Some(content.clone());
    let outcome = auto_resolve(
        "src/bindings.rs",
        &content,
        &registry,
        &generator,
        &read_back,
    )
    .expect("header-declared generator must resolve");
    assert_eq!(
        outcome,
        AutoResolutionOutcome::Regenerated {
            generator: GEN.to_string()
        }
    );
    assert_eq!(generator.invocation_count(), 1);
}

#[test]
fn the_resolution_step_runs_the_repository_generator_and_takes_the_result() {
    // The single-value file has no header; the repository registry says its
    // source of truth is scripts/gen-skill-goldens.sh.
    let mut registry = GeneratorRegistry::new();
    registry.register("tests/fixtures/skill-goldens/", GEN);
    let generator = FakeGenerator::new();
    let path = golden("autospec.SKILL.md.sha256");
    let corrupted = format!("{HASH_A}\n{HASH_B}");

    // The generator rewrote the golden to the new hash.
    let read_back = |_path: &str| Some(HASH_B.to_string());
    let outcome = auto_resolve(&path, &corrupted, &registry, &generator, &read_back)
        .expect("registry-owned single-value file must regenerate");

    assert_eq!(
        outcome,
        AutoResolutionOutcome::Regenerated {
            generator: GEN.to_string()
        }
    );
    assert_eq!(generator.invocation_count(), 1);

    // And the taken result is what the shape check admits.
    assert!(check_single_value_file(&path, HASH_B).is_empty());
}

#[test]
fn a_keep_both_file_still_gets_a_keep_both_plan() {
    let registry = GeneratorRegistry::new();
    let generator = FakeGenerator::new();

    let changelog = auto_resolve(
        "docs/CHANGELOG.md",
        "# 1.4.2\n",
        &registry,
        &generator,
        &not_readable,
    )
    .unwrap();
    assert_eq!(
        changelog,
        AutoResolutionOutcome::TextMerge {
            plan: ResolutionPlan::KeepBothInOrder
        }
    );

    let lib = auto_resolve(
        "src/lib.rs",
        "pub mod a;\n",
        &registry,
        &generator,
        &not_readable,
    )
    .unwrap();
    assert_eq!(
        lib,
        AutoResolutionOutcome::TextMerge {
            plan: ResolutionPlan::KeepBothDeduplicated
        }
    );
    assert_eq!(generator.invocation_count(), 0);
}

#[test]
fn the_full_table_refuses_nothing_it_can_name_and_names_nothing_it_cannot() {
    let corrupted = format!("{HASH_A}\n{HASH_B}");
    let changelog_entry = "# 1.4.2\n- entry\n".to_string();
    let allowlist_entry = "alpha\n".to_string();
    let lib_declarations = "pub mod a;\n".to_string();
    let scratch_notes = "anything\n".to_string();
    let cases: [(&str, &str, FileShape); 6] = [
        (
            "tests/fixtures/skill-goldens/x.SKILL.md.sha256",
            HASH_A,
            FileShape::SingleValue,
        ),
        (
            "tests/fixtures/skill-goldens/x.codex.prompt.md.sha256",
            &corrupted,
            FileShape::SingleValue,
        ),
        (
            "docs/CHANGELOG.md",
            &changelog_entry,
            FileShape::AppendOnlyList,
        ),
        (
            "tools/deps.allowlist",
            &allowlist_entry,
            FileShape::AppendOnlyList,
        ),
        (
            "crates/autospec-core/src/lib.rs",
            &lib_declarations,
            FileShape::AdditiveDeclarations,
        ),
        ("notes/scratch.md", &scratch_notes, FileShape::Unknown),
    ];
    for (path, content, expected) in &cases {
        let shape = classify_file(path, content);
        assert_eq!(&shape, expected, "{path}");
        if *expected == FileShape::Unknown {
            assert!(
                matches!(resolution_for(&shape), ResolutionPlan::Refuse { .. }),
                "{path}: unknown must refuse"
            );
        } else {
            assert!(
                !matches!(resolution_for(&shape), ResolutionPlan::Refuse { .. }),
                "{path}: a named shape must not refuse"
            );
        }
    }
}
