//! Local-gate coverage (issue #4304).
//!
//! The incident: the CI job was named `"Rust baseline (fmt / clippy /
//! test)"` and ran seven steps. The engineer — two months after #4197 told
//! him the steps are the contract — wrote a local gate from the three
//! commands in the label, ran it, and reported the gate clean. Steps 4-7
//! never ran locally: the `--ignored` tests, a `schema-gen --check`
//! regenerate-and-diff, the pinned-digest check, and `test-ci-skeleton.sh`,
//! which is the step that caught the defect. The fix was a two-line pin.
//!
//! The regression tests run in the configuration the bug required: a job
//! whose name enumerates three of its seven steps and a gate transcribed
//! from that name. On a job with a purpose-only name and a generated gate
//! (the control), every check agrees.

use autospec_core::ci_name_drift::{derive_name, CiJob, CiStep};
use autospec_core::gate_coverage::{
    artifact_drift, audit, challenge_claim, claim_from_words, coverage, derive_gate,
    format_step_ranges, name_policy, render_gate_script, ArtifactContract, ArtifactDrift,
    ClaimVerdict, ContractError, DriftCheck, GateClaim, GateEquivalence, NamePolicy,
};

/// The incident configuration: a job whose name enumerates three of its seven
/// steps. Steps 4-7 exist in the workflow and appear in no label.
fn incident_job() -> CiJob {
    CiJob {
        id: "rust-baseline".into(),
        name: "Rust baseline (fmt / clippy / test)".into(),
        steps: vec![
            step("fmt", "cargo fmt --all --check"),
            step("clippy", "cargo clippy --workspace --all-targets"),
            step("test", "cargo test --workspace"),
            step("ignored tests", "cargo test --workspace -- --ignored"),
            step("schema check", "schema-gen --check"),
            step("pinned digests", "bash scripts/check-pinned-digests.sh"),
            step("ci skeleton", "bash tests/test-ci-skeleton.sh"),
        ],
    }
}

fn step(name: &str, run: &str) -> CiStep {
    CiStep {
        name: name.into(),
        run: run.into(),
    }
}

/// The gate the engineer wrote by reading the label: steps 1-3, no more.
fn incident_gate() -> Vec<String> {
    vec![
        "cargo fmt --all --check".into(),
        "cargo clippy --workspace --all-targets".into(),
        "cargo test --workspace".into(),
    ]
}

/// The correct gate: every `run:` step of the job, generated from the job.
fn full_gate() -> Vec<String> {
    derive_gate(&incident_job())
}

/// The control: a purpose-named job — no parenthetical enumeration to copy.
fn control_job() -> CiJob {
    CiJob {
        id: "rust-baseline".into(),
        name: "Rust baseline".into(),
        steps: vec![
            step("", "cargo fmt --all --check"),
            step("", "cargo clippy --workspace --all-targets"),
            step("", "cargo test --workspace"),
        ],
    }
}

/// The name the steps derive to — the remedy #4304 offers for a partial
/// label, and the name a complete gate must carry.
const FULL_NAME: &str = "Rust baseline (fmt / clippy / test / ignored tests / schema check / pinned digests / ci skeleton)";

/// The #4304 cross-artifact contract: the bindings tarball is regenerated by
/// the schema step and its digest is pinned in the web lockfile. CI checked
/// the pin at step 6; the transcribed gate dropped it.
fn bindings_contract() -> ArtifactContract {
    ArtifactContract::new(
        "inferweave-bindings-0.1.0.tgz",
        "apps/web/package-lock.json",
        "npm error code EINTEGRITY inside the web image publish job, far from its cause",
        vec![5],
        Some(
            DriftCheck::new(
                "bash scripts/check-pinned-digests.sh",
                "the regenerated tarball no longer matches the digest pinned in the lockfile",
            )
            .expect("check has a command and a rationale"),
        ),
    )
    .expect("contract names its artifact, pin and failure mode")
}

// ---------------------------------------------------------------- invariant 1

#[test]
fn gate_is_derived_from_steps_not_from_the_name() {
    let gate = derive_gate(&incident_job());
    assert_eq!(gate.len(), 7, "the job has seven steps");
    assert!(
        gate.contains(&"bash tests/test-ci-skeleton.sh".to_string()),
        "the step that caught the defect must be in the generated gate"
    );
    assert_eq!(gate, incident_job().command_list());
}

#[test]
fn incident_gate_covers_three_of_seven_and_says_so() {
    let measured = coverage(&incident_gate(), &incident_job());
    assert_eq!(measured.ran, vec![1, 2, 3]);
    assert_eq!(measured.skipped, vec![4, 5, 6, 7]);
    assert!(measured.extra.is_empty());
    assert_eq!(
        measured.equivalence(),
        GateEquivalence::Partial {
            skipped: vec![4, 5, 6, 7]
        }
    );
}

#[test]
fn full_gate_is_the_same_gate() {
    let measured = coverage(&full_gate(), &incident_job());
    assert_eq!(measured.equivalence(), GateEquivalence::Same);
    assert!(measured.skipped.is_empty());
}

#[test]
fn extra_command_makes_the_gate_divergent() {
    let mut gate = incident_gate();
    gate.push("cargo +nightly miri test".into());
    let measured = coverage(&gate, &incident_job());
    assert_eq!(
        measured.equivalence(),
        GateEquivalence::Divergent {
            skipped: vec![4, 5, 6, 7],
            extra: vec!["cargo +nightly miri test".into()],
        }
    );
    assert!(measured
        .statement(&incident_job())
        .contains("no CI step runs"));
}

#[test]
fn coverage_statement_is_scoped_never_clean() {
    let measured = coverage(&incident_gate(), &incident_job());
    assert_eq!(
        measured.statement(&incident_job()),
        "ran steps 1-3 of 7 (skipped 4-7)"
    );
    let full = coverage(&full_gate(), &incident_job());
    assert_eq!(
        full.statement(&incident_job()),
        "ran all 7 steps of job 'rust-baseline'"
    );
}

#[test]
fn paired_lists_show_both_lists_when_automation_is_impossible() {
    let measured = coverage(&incident_gate(), &incident_job());
    let lines = measured.paired_lists(&incident_job());
    // header + one line per CI step.
    assert_eq!(lines.len(), 8);
    assert!(lines[0].contains("defines 7 steps; this gate runs 3"));
    assert!(lines[1].contains("[    RAN]"));
    assert!(lines[4].contains("[SKIPPED]"));
    assert!(lines[4].contains("cargo test --workspace -- --ignored"));
    // A gate command with no CI step behind it is shown as added.
    let mut gate = full_gate();
    gate.push("echo local-only".into());
    let diverged = coverage(&gate, &incident_job()).paired_lists(&incident_job());
    assert!(diverged.last().unwrap().contains("GATE extra"));
    assert!(diverged.last().unwrap().contains("echo local-only"));
}

#[test]
fn rendered_gate_carries_its_own_coverage() {
    let script = render_gate_script(&incident_job());
    assert!(script.contains("set -euo pipefail"));
    assert!(script.contains("gate step 1/7: fmt"));
    assert!(script.contains("gate step 6/7: pinned digests"));
    assert!(script.contains("gate step 7/7: ci skeleton"));
    assert!(script.contains("bash tests/test-ci-skeleton.sh"));
    // A step with no name still gets a numbered header.
    let unnamed = render_gate_script(&control_job());
    assert!(unnamed.contains("gate step 2/3: step 2"));
}

#[test]
fn rendered_gate_escapes_quoting_in_labels() {
    let mut job = control_job();
    job.steps[0].name = r#"run "tests" $HOME `id`"#.into();
    let script = render_gate_script(&job);
    // Nothing in the label terminates the echo's quoting: every risky
    // character is escaped, so the generated script cannot execute its own
    // step names.
    assert!(script.contains(r#"run \"tests\" \$HOME \`id\`"#));
}

// ---------------------------------------------------------------------------
// Invariant 2: a name may state a purpose or be generated from the steps.
// Nothing in between.
// ---------------------------------------------------------------------------

#[test]
fn purpose_named_job_is_admissible() {
    let job = control_job();
    let verdict = name_policy(&job);
    assert_eq!(verdict, NamePolicy::PurposeNamed);
    assert!(!verdict.is_trap());
    assert!(verdict.line(&job).starts_with("OK:"));
}

#[test]
fn incident_name_is_a_trap_naming_every_omitted_step() {
    let job = incident_job();
    let verdict = name_policy(&job);
    match &verdict {
        NamePolicy::PartialEnumeration {
            named_count,
            total_steps,
            not_listed,
            unbacked,
            ..
        } => {
            assert_eq!((*named_count, *total_steps), (3, 7));
            // Every omitted step is named in the verdict: the reader is not
            // left to guess what the label left out.
            assert_eq!(
                *not_listed,
                vec![
                    "ignored tests",
                    "schema check",
                    "pinned digests",
                    "ci skeleton"
                ]
            );
            assert!(unbacked.is_empty());
        }
        other => panic!("expected a partial enumeration, got {other:?}"),
    }
    assert!(verdict.is_trap());
    let line = verdict.line(&job);
    assert!(line.contains("names 3 of its 7 steps"), "{line}");
    assert!(line.contains("ci skeleton"), "{line}");
    assert!(
        line.contains("naming some of the steps is worse than naming none"),
        "{line}"
    );
}

#[test]
fn partial_enumeration_is_a_trap_even_when_every_token_is_real() {
    // The #4197 lint compares an enumerating name AGAINST the steps and passes
    // when every token is a real step. That is the weaker rule: this name names
    // 6 of 7 real steps and is still the trap, because the harm is the omission
    // and the reader runs what is written.
    let mut job = incident_job();
    job.name = format!(
        "Rust baseline ({})",
        ["fmt", "clippy", "test"]
            .iter()
            .map(|s| s.to_string())
            .chain(job.steps[3..6].iter().map(|s| s.name.clone()))
            .collect::<Vec<_>>()
            .join(" / ")
    );
    let verdict = name_policy(&job);
    assert!(verdict.is_trap(), "{verdict:?}");
    match verdict {
        NamePolicy::PartialEnumeration {
            named_count,
            total_steps,
            not_listed,
            unbacked,
            ..
        } => {
            assert_eq!((named_count, total_steps), (6, 7));
            assert_eq!(not_listed, ["ci skeleton"]);
            assert!(unbacked.is_empty(), "{unbacked:?}");
        }
        other => panic!("expected a partial enumeration, got {other:?}"),
    }
}

#[test]
fn generated_enumeration_is_admissible() {
    // A name generated from the steps cannot fall behind them: the defect that
    // #4197 caught (the omitted `test`) is impossible by construction here.
    let mut job = incident_job();
    job.name = derive_name(&job);
    let verdict = name_policy(&job);
    assert_eq!(verdict, NamePolicy::GeneratedEnumeration);
    assert!(!verdict.is_trap());
    assert!(verdict.line(&job).starts_with("OK:"));
}

#[test]
fn enumeration_is_case_insensitive_against_step_names() {
    let mut job = incident_job();
    job.name =
        "Rust baseline (FMT / Clippy / TEST / ignored tests / schema check / pinned digests / ci skeleton)".to_string();
    assert_eq!(name_policy(&job), NamePolicy::GeneratedEnumeration);
}

#[test]
fn a_label_listing_a_step_ci_no_longer_runs_is_a_trap() {
    // The name ran ahead of the job: the label still promises a step that was
    // removed from CI. Nothing in the label can be trusted as the contract.
    let mut job = CiJob {
        id: "node-baseline".into(),
        name: "Node baseline".into(),
        steps: vec![step("install", "npm ci"), step("typecheck", "tsc --noEmit")],
    };
    job.name = "Node baseline (install / typecheck / audit)".into();
    match name_policy(&job) {
        NamePolicy::PartialEnumeration {
            unbacked,
            named_count,
            total_steps,
            ..
        } => {
            assert_eq!(unbacked, ["audit"]);
            assert_eq!((named_count, total_steps), (2, 2));
        }
        other => panic!("expected a partial enumeration, got {other:?}"),
    }
}

#[test]
fn unnamed_steps_are_reported_by_position() {
    let mut job = CiJob {
        id: "node-baseline".into(),
        name: "Node baseline".into(),
        steps: vec![
            step("install", "npm ci"),
            step("", "npm run codegen"),
            step("build", "npm run build"),
        ],
    };
    job.name = "Node baseline (install)".into();
    match name_policy(&job) {
        NamePolicy::PartialEnumeration { not_listed, .. } => {
            assert_eq!(not_listed, ["step 2 (unnamed)", "build"])
        }
        other => panic!("expected a partial enumeration, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// Invariant 3: pass evidence states coverage, never "the gate is clean".
// ---------------------------------------------------------------------------

#[test]
fn claim_parser_handles_ranges_and_singletons() {
    assert_eq!(
        claim_from_words("ran steps 1-3 of 7"),
        GateClaim::RanSteps {
            ran: vec![1, 2, 3],
            total: 7
        }
    );
    assert_eq!(
        claim_from_words("ran step 5 of 7"),
        GateClaim::RanSteps {
            ran: vec![5],
            total: 7
        }
    );
    assert_eq!(
        claim_from_words("ran steps 1-3, 5, 7-8 of 8"),
        GateClaim::RanSteps {
            ran: vec![1, 2, 3, 5, 7, 8],
            total: 8
        }
    );
    // Wording that states no coverage is read as the bare claim: the burden
    // of proof is on the claimant, not on the reader.
    assert_eq!(
        claim_from_words("the gate is clean"),
        GateClaim::GateIsClean
    );
    assert_eq!(claim_from_words("gate passed"), GateClaim::GateIsClean);
}

#[test]
fn bare_clean_claim_is_overstated_when_coverage_is_partial() {
    let job = incident_job();
    let measured = coverage(&incident_gate(), &job);
    let verdict = challenge_claim(&claim_from_words("the gate is clean"), &measured, &job);
    match &verdict {
        ClaimVerdict::Overstated { restatement } => {
            assert!(
                restatement.contains("ran steps 1-3 of 7"),
                "restatement must state the coverage actually measured: {restatement}"
            );
            assert!(restatement.contains("skipped 4-7"));
        }
        other => panic!("a clean claim over a partial gate must be Overstated, got {other:?}"),
    }
    assert!(verdict.line().starts_with("WARN:"));
}

#[test]
fn correct_coverage_claim_is_accepted() {
    let job = incident_job();
    let measured = coverage(&full_gate(), &job);
    assert_eq!(
        challenge_claim(&claim_from_words("the gate is clean"), &measured, &job),
        ClaimVerdict::Accepted,
        "a gate that runs every step may be called clean"
    );
    let partial = coverage(&incident_gate(), &job);
    assert_eq!(
        challenge_claim(&claim_from_words("ran steps 1-3 of 7"), &partial, &job),
        ClaimVerdict::Accepted
    );
}

#[test]
fn wrong_coverage_claim_is_rejected() {
    let job = incident_job();
    let partial = coverage(&incident_gate(), &job);
    // Claims every step ran.
    let v = challenge_claim(&claim_from_words("ran steps 1-7 of 7"), &partial, &job);
    assert!(matches!(v, ClaimVerdict::WrongCoverage { .. }), "{v:?}");
    assert!(v.line().starts_with("WARN:"));
    // Right steps, wrong denominator.
    assert!(matches!(
        challenge_claim(&claim_from_words("ran steps 1-3 of 3"), &partial, &job),
        ClaimVerdict::WrongCoverage { .. }
    ));
}

// ---------------------------------------------------------------------------
// Invariant 4: a gate that regenerates an artifact must run the pin check.
// ---------------------------------------------------------------------------

#[test]
fn artifact_check_dropped_by_the_gate_is_reported_with_its_ci_step() {
    // CI ran `check-pinned-digests.sh` at step 6; the transcribed gate does
    // not run it at all. The finding must name the step CI runs it at.
    let drift = artifact_drift(&incident_job(), &incident_gate(), &bindings_contract());
    match &drift {
        ArtifactDrift::CheckNotRun {
            artifact,
            command,
            ci_step,
        } => {
            assert_eq!(artifact, "inferweave-bindings-0.1.0.tgz");
            assert_eq!(command, "bash scripts/check-pinned-digests.sh");
            assert_eq!(*ci_step, Some(6), "CI runs the check at step 6");
        }
        other => panic!("dropped pin check must be CheckNotRun, got {other:?}"),
    }
    let line = drift.line(&bindings_contract());
    assert!(line.starts_with("WARN:"));
    assert!(line.contains("CI runs it at step 6"), "{line}");
    assert!(
        line.contains("EINTEGRITY"),
        "the line must name the failure the check prevents: {line}"
    );
}

#[test]
fn artifact_check_covered_when_gate_runs_it() {
    let drift = artifact_drift(&incident_job(), &full_gate(), &bindings_contract());
    match &drift {
        ArtifactDrift::Covered { command } => {
            assert_eq!(command, "bash scripts/check-pinned-digests.sh")
        }
        other => panic!("full gate runs the pin check, got {other:?}"),
    }
    assert!(drift.line(&bindings_contract()).starts_with("OK:"));
}

#[test]
fn a_contract_with_no_declared_check_is_missing_check() {
    // The contract itself is incomplete: it regenerates an artifact and
    // names no check for its pin. Construction accepts it (the omission is
    // the state under audit), and the verdict names the failure it allows.
    let contract = ArtifactContract::new(
        "inferweave-bindings-0.1.0.tgz",
        "apps/web/package-lock.json",
        "npm error code EINTEGRITY inside the web image publish job",
        vec![5],
        None,
    )
    .expect("artifact, pin and failure mode are present");
    let drift = artifact_drift(&incident_job(), &full_gate(), &contract);
    match &drift {
        ArtifactDrift::MissingCheck {
            artifact,
            pin_file,
            regenerated_by,
        } => {
            assert_eq!(artifact, "inferweave-bindings-0.1.0.tgz");
            assert_eq!(pin_file, "apps/web/package-lock.json");
            assert_eq!(regenerated_by, &vec![5]);
        }
        other => panic!("a contract with no check must be MissingCheck, got {other:?}"),
    }
    assert!(drift
        .line(&contract)
        .contains("no cross-artifact drift check"));
}

#[test]
fn a_gate_that_regenerates_nothing_has_no_obligation() {
    let contract = ArtifactContract::new(
        "some-other-artifact.tar.gz",
        "elsewhere/pin.txt",
        "unrelated drift",
        vec![],
        None,
    )
    .expect("artifact, pin and failure mode are present");
    let drift = artifact_drift(&incident_job(), &incident_gate(), &contract);
    assert!(matches!(drift, ArtifactDrift::NotRegenerated));
    assert!(drift.line(&contract).starts_with("OK:"));
}

#[test]
fn contracts_refuse_to_be_constructed_empty() {
    let err: ContractError =
        ArtifactContract::new("", "apps/web/package-lock.json", "drift", vec![5], None)
            .expect_err("an unnamed artifact is not a contract");
    assert_eq!(err.field(), "artifact");

    let err = DriftCheck::new("bash scripts/check-pinned-digests.sh", "")
        .expect_err("a drift check with no rationale is a habit, not a contract");
    assert_eq!(err.field(), "rationale");
    assert!(err.to_string().contains("rationale"));
}

#[test]
fn step_ranges_group_consecutive_indices() {
    // The coverage statement's formatting primitive: "1-3, 5, 7-8" reads as
    // coverage, a bare list of numbers does not.
    assert_eq!(format_step_ranges(&[1, 2, 3, 5, 7, 8]), "1-3, 5, 7-8");
    assert_eq!(format_step_ranges(&[4, 5, 6, 7]), "4-7");
    assert_eq!(format_step_ranges(&[6]), "6");
    assert_eq!(format_step_ranges(&[]), "none");
}

// ---------------------------------------------------------------------------
// The aggregate audit: the incident gate vs. a complete gate.
// ---------------------------------------------------------------------------

#[test]
fn audit_of_the_incident_gate_reports_the_findings() {
    let lines = audit(&incident_job(), &incident_gate(), &[bindings_contract()]);
    let text = lines.join("\n");
    // Coverage: the gate says what it skipped.
    assert!(text.contains("ran steps 1-3 of 7"), "{text}");
    assert!(text.contains("SKIPPED"), "{text}");
    // Name policy: the partial enumeration is named as the trap.
    assert!(
        text.contains("naming some of the steps is worse than naming none"),
        "{text}"
    );
    // Pin check: named with the CI step that runs it.
    assert!(text.contains("CI runs it at step 6"), "{text}");
    // Verdict: three findings, and it never says "clean".
    let last = lines.last().expect("audit emits a verdict line");
    assert!(last.starts_with("WARN: 3 finding(s)"), "{last}");
    assert!(!text.contains("the gate is the CI gate"), "{text}");
}

#[test]
fn audit_of_the_full_gate_is_clean() {
    // The control: a purpose-named job whose gate runs every step and whose
    // one regenerated artifact has its pin check in the gate.
    let job = CiJob {
        id: "node-baseline".into(),
        name: "Node baseline".into(),
        steps: vec![
            step("install", "npm ci"),
            step("build", "npm run build"),
            step("pin check", "bash scripts/check-pinned-digests.sh"),
        ],
    };
    let gate = derive_gate(&job);
    let contract = ArtifactContract::new(
        "inferweave-bindings-0.1.0.tgz",
        "apps/web/package-lock.json",
        "npm error code EINTEGRITY inside the web image publish job",
        vec![2],
        Some(
            DriftCheck::new(
                "bash scripts/check-pinned-digests.sh",
                "the regenerated tarball no longer matches the digest pinned in the lockfile",
            )
            .expect("check has a command and a rationale"),
        ),
    )
    .expect("contract names its artifact, pin and failure mode");
    let lines = audit(&job, &gate, &[contract]);
    let text = lines.join("\n");
    let last = lines.last().expect("audit emits a verdict line");
    assert!(
        last.starts_with("OK: the gate is the CI gate"),
        "a complete gate must be reported clean, got:\n{text}"
    );
    assert!(!text.contains("WARN:"), "{text}");
}
