#!/usr/bin/env bash
# tests/refresh-goldens.sh — regenerate committed golden-snapshot files
# from the recorded fixtures in tests/fixtures/.
#
# Per spec §6.2 / §6.4 the golden-snapshot pipeline is intentionally a
# manual loop: a maintainer runs the listener / decomposer subagent
# against a checked-in fixture, captures stdout, and commits the result
# under tests/golden/. This script automates the file-copy half of that
# loop and prints the manual subagent step it cannot automate.
#
# Usage:
#   tests/refresh-goldens.sh           # regenerate every golden
#   tests/refresh-goldens.sh -n        # dry run (print actions only)
#
# Exit 0 on success.

set -eu

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIXTURES_DIR="$REPO_ROOT/tests/fixtures"
GOLDEN_DIR="$REPO_ROOT/tests/golden"

DRY_RUN=0
if [ "${1:-}" = "-n" ] || [ "${1:-}" = "--dry-run" ]; then
    DRY_RUN=1
fi

run() {
    if [ "$DRY_RUN" -eq 1 ]; then
        printf '  [dry-run] %s\n' "$*"
    else
        eval "$@"
    fi
}

mkdir -p "$GOLDEN_DIR"

cat <<'BANNER'
refresh-goldens: golden snapshots are regenerated by replaying every
fixture conversation through the corresponding subagent and capturing
its committed-output. This script does NOT spawn subagents — the
maintainer is expected to:

  1. For each tests/fixtures/<name>.txt, invoke the listener flow
     (autospec-listen) and the autospec-define decomposer against it.
  2. Capture the resulting issue body / spec body to a temp file.
  3. Replace the matching tests/golden/<artifact>.md with that capture
     and commit the diff.

This script merely surfaces the matrix of (fixture × golden) pairs and
ensures placeholder goldens exist so the comparison harness has files
to diff against.

BANNER

# Pair each fixture with its expected golden artifact. Today there are
# two static placeholders; fill in real captures by hand.
pair() {
    src="$1"; dst="$2"
    if [ ! -f "$src" ]; then
        printf 'refresh-goldens: missing fixture %s\n' "$src" >&2
        return 0
    fi
    if [ ! -f "$dst" ]; then
        printf 'refresh-goldens: golden %s missing — leaving placeholder.\n' "$dst"
    else
        printf 'refresh-goldens: pair %s -> %s (manual capture required)\n' "$src" "$dst"
    fi
}

pair "$FIXTURES_DIR/chat_about_perf.txt"  "$GOLDEN_DIR/autospec-listen.draft-issue.md"
pair "$FIXTURES_DIR/chat_about_auth.txt"  "$GOLDEN_DIR/autospec-define.spec.md"

printf '\nrefresh-goldens: done. Manual subagent capture required.\n'
exit 0
