#[derive(Debug)]
pub(super) struct DomainSpec {
    pub(super) name: &'static str,
    pub(super) tokens: &'static [&'static str],
    pub(super) persona: &'static str,
    pub(super) lens: &'static str,
}

pub(super) fn domain_specs() -> &'static [DomainSpec] {
    &[
        DomainSpec {
            name: "ms-data",
            tokens: &[
                "metabolomics",
                "mzml",
                "mzxml",
                "mzdata",
                "raw ms",
                "mass spec",
                "mass spectrometry",
                "lc ms",
                "gc ms",
                "ms1",
                "ms2",
                "ms/ms",
                "centroid",
                "profile mode",
                "peak picking",
                "feature table",
            ],
            persona: "MS data specialist",
            lens: "raw/centroid/profile MS data handling, peak picking, and feature-table reproducibility",
        },
        DomainSpec {
            name: "chemical-ids",
            tokens: &[
                "inchi",
                "inchikey",
                "smiles",
                "canonical smiles",
                "pubchem",
                "hmdb",
                "chebi",
                "lipidmaps",
                "cas number",
                "adduct",
                "formula",
                "exact mass",
            ],
            persona: "Chemical identifiers specialist",
            lens: "chemical identifier normalization, adduct/formula ambiguity, and cross-database traceability",
        },
        DomainSpec {
            name: "lc-binbase",
            tokens: &[
                "binbase",
                "retention index",
                "retention time",
                "kovats",
                "lc bin",
                "gc bin",
                "alignment bin",
                "chromatogram",
                "rt alignment",
            ],
            persona: "LC-BinBase specialist",
            lens: "LC/GC retention alignment, BinBase-style bins, and chromatographic reproducibility",
        },
        DomainSpec {
            name: "mona-sirius",
            tokens: &[
                "mona",
                "massbank",
                "sirius",
                "csi:fingerid",
                "fingerid",
                "canopus",
                "gnps",
                "spectral library",
                "fragmentation tree",
                "ms2query",
            ],
            persona: "MoNA/SIRIUS specialist",
            lens: "spectral-library search, SIRIUS/CSI:FingerID annotation confidence, and offline fixture boundaries",
        },
        DomainSpec {
            name: "hpc-reliability",
            tokens: &[
                "lab ops",
                "slurm",
                "sbatch",
                "squeue",
                "snakemake",
                "nextflow",
                "cwl",
                "singularity",
                "apptainer",
                "hpc",
                "cluster",
                "array job",
                "job array",
                "checkpoint",
                "scratch space",
            ],
            persona: "HPC reliability specialist",
            lens: "cluster scheduling, retry/checkpoint behavior, scratch-space cleanup, and reproducible lab pipelines",
        },
        DomainSpec {
            name: "trading",
            tokens: &[
                "ccxt",
                "backtrader",
                "zipline",
                "alpaca",
                "quantlib",
                "ta lib",
                "talib",
                "backtest",
                "backtesting",
                "order book",
                "market data",
                "ohlcv",
                "exchange api",
                "trading",
                "brokerage",
                "portfolio",
            ],
            persona: "Quantitative trading strategist",
            lens: "missing risk controls, order-execution correctness, and market-data integrity",
        },
        DomainSpec {
            name: "healthcare",
            tokens: &[
                "hl7",
                "fhir",
                "hipaa",
                "dicom",
                "ehr",
                "emr",
                "patient",
                "clinical",
                "healthcare",
                "phi",
                "icd 10",
                "icd10",
            ],
            persona: "Healthcare compliance reviewer",
            lens: "PHI handling, HIPAA boundaries, and clinical-data integrity",
        },
        DomainSpec {
            name: "payments",
            tokens: &[
                "stripe",
                "braintree",
                "paypal",
                "pci",
                "pci dss",
                "payment",
                "checkout",
                "invoice",
                "billing",
                "ledger",
                "chargeback",
            ],
            persona: "Payments reliability engineer",
            lens: "idempotency, reconciliation, and PCI trust boundaries",
        },
        DomainSpec {
            name: "ml",
            tokens: &[
                "pytorch",
                "torch",
                "tensorflow",
                "keras",
                "scikit learn",
                "sklearn",
                "huggingface",
                "transformers",
                "xgboost",
                "lightgbm",
                "inference",
                "training loop",
                "model registry",
            ],
            persona: "ML systems reviewer",
            lens: "training/serving skew, data leakage, and reproducibility",
        },
        DomainSpec {
            name: "security",
            tokens: &[
                "oauth",
                "jwt",
                "bcrypt",
                "argon2",
                "crypto",
                "cryptography",
                "tls",
                "mtls",
                "vault",
                "secrets manager",
                "rbac",
                "authz",
                "authentication",
            ],
            persona: "Application security advisor",
            lens: "authz boundaries, secret handling, and injection surfaces",
        },
        DomainSpec {
            name: "infra",
            tokens: &[
                "kubernetes",
                "k8s",
                "terraform",
                "helm",
                "docker compose",
                "ansible",
                "pulumi",
                "cloudformation",
                "prometheus",
                "grafana",
            ],
            persona: "Infrastructure reliability engineer",
            lens: "blast radius, rollout safety, and observability gaps",
        },
    ]
}
