#!/usr/bin/env bash
# Observatory render helpers for scripts/autospec-control-plane.sh.

render_observatory_compose() {
    cat <<'YAML'
services:
  postgres:
    image: postgres:16
    container_name: observatory-postgres
    ports:
      - "5432:5432"
    volumes:
      - observatory-postgres-data:/var/lib/postgresql/data

volumes:
  observatory-postgres-data:
YAML
}

render_observatory_api_readme() {
    cat <<'MD'
# Autospec Observatory API

Seed path for the future event ingestion API. The MVP contract is
API-key authenticated ingestion for `POST /v1/events/batch`, project resolution,
run progress, timeline, worker, policy, cost, and fleet summary endpoints.

This dry-run scaffold is offline-only and does not implement or start a live
server.
MD
}

render_observatory_web_readme() {
    cat <<'MD'
# Autospec Observatory Web

Seed path for the developer/operator UI. The MVP UI will expose fleet, timeline,
work-item, blockers, workers, policy-decision, cost, duration, outcome, and
progress views with 10-second polling by default.

This dry-run scaffold is offline-only and does not implement or start a web app.
MD
}

render_observatory_event_schema_readme() {
    cat <<'MD'
# Event Schema Package

Seed package for run, cycle, work-item, worker, cost, blocker, progress, and
policy-decision events. Events must carry project classification and
`privacy_tier` metadata so client and server privacy enforcement can reject
over-shared payloads.
MD
}

render_observatory_db_readme() {
    cat <<'MD'
# Database Package

Seed package for the future Postgres-backed multi-tenant data model covering
runs, events, workers, projects, repositories, costs, blockers, and policy
decisions.
MD
}

render_observatory_ui_readme() {
    cat <<'MD'
# UI Package

Seed package for shared web UI components used by the observatory operator
console.
MD
}

render_observatory_migrations_readme() {
    cat <<'MD'
# Migrations

No migrations are generated by this dry run. Future implementation slices should
add deterministic Postgres migrations here after the data model is specified.
MD
}

render_observatory_operator_docs() {
    cat <<'MD'
# Local Observatory Operations

The dry-run scaffold reserves paths for local SaaS-ready development: API, web,
shared packages, migrations, docs, and `docker-compose.yml` with Postgres. The
current slice is path and seed-file generation only; no services are started.
MD
}

render_observatory_file_templates() {
    observatory_repo="$1"

    render_file_header "$observatory_repo" "docker-compose.yml"
    render_observatory_compose
    render_file_header "$observatory_repo" "apps/api/README.md"
    render_observatory_api_readme
    render_file_header "$observatory_repo" "apps/web/README.md"
    render_observatory_web_readme
    render_file_header "$observatory_repo" "packages/event-schema/README.md"
    render_observatory_event_schema_readme
    render_file_header "$observatory_repo" "packages/db/README.md"
    render_observatory_db_readme
    render_file_header "$observatory_repo" "packages/ui/README.md"
    render_observatory_ui_readme
    render_file_header "$observatory_repo" "migrations/README.md"
    render_observatory_migrations_readme
    render_file_header "$observatory_repo" "docs/local-operations.md"
    render_observatory_operator_docs
}

render_observatory_dry_run() {
    observatory_repo="$1"

    cat <<EOF_OBSERVATORY

${observatory_repo}/
  ${observatory_repo}/apps/
  ${observatory_repo}/apps/api/
  ${observatory_repo}/apps/web/
  ${observatory_repo}/packages/
  ${observatory_repo}/packages/event-schema/
  ${observatory_repo}/packages/db/
  ${observatory_repo}/packages/ui/
  ${observatory_repo}/migrations/
  ${observatory_repo}/docs/
  ${observatory_repo}/docker-compose.yml
EOF_OBSERVATORY

    render_observatory_file_templates "$observatory_repo"
}

render_control_plane_dry_run() {
    owner="$1"
    governance_repo="$2"
    observatory_repo="$3"

    cat <<EOF_RENDER
# autospec-control-plane bootstrap --dry-run

owner: ${owner}
governance_repo: ${governance_repo}
observatory_repo: ${observatory_repo}
mode: dry-run
github_writes: false

${governance_repo}/
EOF_RENDER

    print_group "policies" \
        "open-source-maintainer-default.yml" \
        "private-personal-default.yml" \
        "private-company-default.yml" \
        "client-project-default.yml" \
        "research-default.yml" \
        "sandbox-default.yml"
    print_group "rules" \
        "qa.yml" "testing.yml" "documentation.yml" "security.yml" \
        "accessibility.yml" "performance.yml" "skill-generation.yml" \
        "release-readiness.yml"
    print_group "schemas" \
        "policy.schema.json" "rule.schema.json" \
        "project-class.schema.json" "priority.schema.json"
    print_group "fixtures" \
        "projects/open-source-cli.yml" "projects/private-personal-app.yml" \
        "projects/private-company-saas.yml" "projects/client-webapp.yml" \
        "projects/research-notebook.yml" "projects/sandbox-lab.yml"
    print_group "tests" \
        "policy-schema.bats" "priority-resolution.bats" "privacy-tier.bats" \
        "merge-rules.bats" "project-classification.bats" "cost-limits.bats" \
        "evidence-requirements.bats"
    print_group "docs" \
        "policy-authoring.md" "project-classes.md" "priority-waterfall.md"
    render_governance_file_templates "$governance_repo"
    render_observatory_dry_run "$observatory_repo"
}
