#!/usr/bin/env python3
"""Target-app runtime feature generation v1.

This module intentionally generates only bounded shell/partial runtime slices
for recognized stacks. It never installs dependencies, creates migrations,
changes auth/security behavior, schedules work, or performs GitHub writes.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


FORBIDDEN_PATHS = [".github/workflows/**", ".env", ".env.*", "**/migrations/**", "package.json", "pyproject.toml"]
HEADER = "Generated by Autospec runtime feature generator."


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def yaml_scalar(value) -> str:
    text = str(value)
    if text in {"true", "false"} or re.fullmatch(r"-?\d+(?:\.\d+)?", text):
        return text
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def load_json(path: Path, default):
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else default
    except Exception:
        return default


def reports(root: Path) -> Path:
    path = root / ".autospec/reports"
    path.mkdir(parents=True, exist_ok=True)
    return path


def state(root: Path) -> Path:
    path = root / ".autospec/state"
    path.mkdir(parents=True, exist_ok=True)
    return path


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "item"


def package_text(root: Path) -> str:
    path = root / "package.json"
    return path.read_text(encoding="utf-8", errors="ignore").lower() if path.exists() else ""


def stack_profile(root: Path) -> dict:
    data = load_json(state(root) / "stack-profile.json", {})
    if data:
        return data
    from autospec_autonomy_stack import detect_stack

    detect_stack(root)
    return load_json(state(root) / "stack-profile.json", {})


def built_in_adapters() -> list[dict]:
    base_features = [
        "in-app-docs-center", "settings-area", "status-page", "feedback-support-flow", "onboarding-shell",
        "ai-provider-settings", "ai-usage-token-dashboard", "rag-assistant-shell", "mcp-diagnostics-shell",
        "capability-interface-shell", "pretty-rendering-viewers", "data-query-shell", "file-operations-shell",
        "analytics-dashboard-shell", "report-export-shell", "visualization-standard-shell",
        "playwright-viewport-tests", "playwright-accessibility-tests", "playwright-white-screen-tests",
    ]
    return [
        adapter("react-vite", "React/Vite", ["javascript", "typescript"], base_features, ["src/**", "docs/**", "tests/**", ".autospec/**"], ["src/pages/{pascal}.tsx", "src/components/autospec/{component}.tsx"]),
        adapter("nextjs-app-router", "Next.js App Router", ["javascript", "typescript"], base_features, ["app/**", "src/**", "docs/**", "tests/**", ".autospec/**"], ["app/{route}/page.tsx", "src/components/autospec/{component}.tsx"], required=["app/page.tsx"]),
        adapter("nextjs-pages-router", "Next.js Pages Router", ["javascript", "typescript"], base_features, ["pages/**", "src/**", "docs/**", "tests/**", ".autospec/**"], ["pages/{route}.tsx", "src/components/autospec/{component}.tsx"], required=["pages/index.tsx"]),
        adapter("node-cli", "Node CLI", ["javascript"], ["playwright-viewport-tests", "report-export-shell"], ["bin/**", "docs/**", ".autospec/**", "tests/**"], ["bin/autospec-status.js"]),
        adapter("python-cli", "Python CLI", ["python"], ["report-export-shell"], ["src/**", "docs/**", ".autospec/**", "tests/**"], ["src/autospec_status.py"]),
    ]


def adapter(aid: str, title: str, stacks: list[str], features: list[str], allowed: list[str], patterns: list[str], required: list[str] | None = None) -> dict:
    return {
        "id": aid,
        "title": title,
        "stack_profiles": stacks,
        "status": "enabled",
        "confidence_required": 0.8,
        "supported_feature_slices": features,
        "source_roots": ["src", "app", "pages"],
        "route_patterns": patterns,
        "component_patterns": patterns,
        "test_patterns": ["tests/e2e/autospec-{feature}.spec.ts"],
        "style_patterns": [],
        "config_patterns": ["package.json"],
        "allowed_paths": allowed,
        "forbidden_paths": FORBIDDEN_PATHS,
        "file_generation": {"route": {"patterns": patterns}, "component": {"patterns": patterns}, "test": {"patterns": ["tests/e2e/autospec-{feature}.spec.ts"]}, "docs": {"patterns": ["docs/specs/{feature}.md"]}},
        "validation": {"focused_commands": ["bash scripts/autospec-verify-runtime-feature.sh --dry-run"], "full_commands": []},
        "detection": {"required_files": required or [], "evidence_files": ["package.json"], "confidence_rules": stacks},
        "risk": {"default_level": "low", "requires_human_guidance": False},
    }


def built_in_slices() -> list[dict]:
    return [
        feature("in-app-docs-center", "In-app documentation center", "product", "route", "shell", ["required_in_app_documentation"], ["docs", "product"], ["DocsCenter", "Docs"]),
        feature("settings-area", "Settings area shell", "product", "route", "shell", ["required_settings_area"], ["settings"], ["SettingsShell", "Settings"]),
        feature("status-page", "Status diagnostics page shell", "product", "route", "shell", ["required_status_page"], ["diagnostics"], ["StatusShell", "Status"]),
        feature("feedback-support-flow", "Feedback support flow shell", "product", "route", "shell", ["required_feedback_flow"], ["product"], ["FeedbackSupport", "Feedback"]),
        feature("onboarding-shell", "Onboarding shell", "product", "route", "shell", ["required_onboarding"], ["product"], ["OnboardingShell", "Onboarding"]),
        feature("ai-provider-settings", "AI provider settings shell", "ai", "mixed", "shell", ["required_ai_provider_abstraction", "required_ai_settings_page"], ["ai"], ["AiProviderSettings", "AiSettings"]),
        feature("ai-usage-token-dashboard", "AI usage token dashboard shell", "ai", "mixed", "shell", ["required_token_usage_tracking"], ["ai"], ["AiUsageTokenDashboard", "AiUsage"]),
        feature("rag-assistant-shell", "RAG assistant shell", "ai", "route", "shell", ["required_rag_indexing"], ["ai"], ["RagAssistantShell", "RagAssistant"]),
        feature("mcp-diagnostics-shell", "MCP diagnostics shell", "ai", "route", "shell", ["required_mcp_registry"], ["ai", "diagnostics"], ["McpDiagnosticsShell", "McpDiagnostics"]),
        feature("capability-interface-shell", "NLAI capability interface shell", "nlai", "route", "shell", ["required_nlai_capability_registry"], ["nlai"], ["CapabilityInterfaceShell", "Capabilities"]),
        feature("pretty-rendering-viewers", "Pretty rendering viewers shell", "nlai", "component", "shell", ["required_pretty_human_output"], ["nlai"], ["PrettyRenderingViewers", "PrettyRendering"]),
        feature("data-query-shell", "Data query shell", "nlai", "route", "shell", ["required_nlai_data_querying_for_data_apps"], ["nlai"], ["DataQueryShell", "DataQuery"]),
        feature("file-operations-shell", "File operations shell", "nlai", "route", "shell", ["required_nlai_file_operations_for_file_apps"], ["nlai"], ["FileOperationsShell", "FileOperations"]),
        feature("analytics-dashboard-shell", "Analytics dashboard shell", "reporting", "route", "shell", ["required_metrics_definitions"], ["reporting"], ["AnalyticsDashboardShell", "Analytics"]),
        feature("report-export-shell", "Report export shell", "reporting", "route", "shell", ["required_csv_pdf_exports"], ["reporting"], ["ReportExportShell", "Reports"]),
        feature("visualization-standard-shell", "Visualization standard shell", "reporting", "docs", "shell", ["required_visualization_library_standard"], ["reporting"], ["VisualizationStandardShell", "Visualization"]),
        feature("playwright-viewport-tests", "Playwright viewport tests", "testing", "test", "partial", ["required_playwright_viewport_matrix"], ["testing"], ["ViewportEvidence", "Viewport"]),
        feature("playwright-accessibility-tests", "Playwright accessibility tests", "testing", "test", "partial", ["required_playwright_accessibility_flow"], ["testing"], ["AccessibilityEvidence", "Accessibility"]),
        feature("playwright-white-screen-tests", "Playwright white-screen tests", "testing", "test", "partial", ["required_playwright_white_screen_repro"], ["testing"], ["WhiteScreenEvidence", "WhiteScreen"]),
    ]


def feature(fid: str, title: str, category: str, kind: str, claim: str, rules: list[str], baselines: list[str], names: list[str]) -> dict:
    return {
        "id": fid,
        "title": title,
        "category": category,
        "summary": title,
        "source_rules": rules,
        "source_baselines": baselines,
        "requires_adapter": True,
        "supported_adapters": ["react-vite", "nextjs-app-router", "nextjs-pages-router"],
        "implementation_kind": kind,
        "runtime_claim_level": claim,
        "risk_level": "low",
        "allowed_paths": ["src/**", "app/**", "pages/**", "docs/**", "tests/**", ".autospec/**"],
        "forbidden_paths": FORBIDDEN_PATHS,
        "required_inputs": ["detected stack profile", "runtime adapter"],
        "generated_artifacts": names,
        "metadata_updates": [".autospec/state/ui-surface.json", ".autospec/state/capability-registry.json"],
        "tests_generated": ["tests/e2e/autospec-{feature}.spec.ts"],
        "validation_expectations": ["runtime feature verification"],
        "acceptance_criteria": [f"{title} shell is generated.", "Runtime claim level is honest."],
        "not_in_scope": ["database migrations", "auth/security behavior changes", "dependency installation", "provider calls"],
        "stuck_if": ["stack confidence is low", "adapter is missing", "route would overwrite user file"],
    }


def write_adapter_files(root: Path, adapters: list[dict]) -> None:
    base = root / ".autospec/adapters"
    write_text(base / "README.md", "# Runtime Adapters\n\nAdapters define safe file-generation patterns for recognized target stacks.\n")
    for item in adapters:
        lines = [
            f"id: {yaml_scalar(item['id'])}",
            f"title: {yaml_scalar(item['title'])}",
            "stack_profiles:",
            *[f"  - {yaml_scalar(p)}" for p in item["stack_profiles"]],
            f"status: {yaml_scalar(item['status'])}",
            f"confidence_required: {item['confidence_required']}",
            "supported_feature_slices:",
            *[f"  - {yaml_scalar(f)}" for f in item["supported_feature_slices"]],
            "allowed_paths:",
            *[f"  - {yaml_scalar(p)}" for p in item["allowed_paths"]],
            "forbidden_paths:",
            *[f"  - {yaml_scalar(p)}" for p in item["forbidden_paths"]],
            "validation:",
            "  focused_commands:",
            *[f"    - {yaml_scalar(c)}" for c in item["validation"]["focused_commands"]],
            "risk:",
            f"  default_level: {yaml_scalar(item['risk']['default_level'])}",
            f"  requires_human_guidance: {str(item['risk']['requires_human_guidance']).lower()}",
        ]
        write_text(base / f"{item['id']}.yml", "\n".join(lines))


def runtime_adapter_index(root: Path) -> int:
    profile = stack_profile(root).get("primary_profile", {})
    adapters = built_in_adapters()
    for item in adapters:
        required = item["detection"].get("required_files", [])
        required_ok = all((root / rel).exists() for rel in required)
        stack_ok = profile.get("id") in item["stack_profiles"] and float(profile.get("confidence", 0) or 0) >= item["confidence_required"]
        item["match_status"] = "available" if stack_ok and required_ok else "unsupported"
        item["match_reason"] = "stack profile and required files match" if item["match_status"] == "available" else "stack profile, confidence, or route convention did not match"
    payload = {"schema": 1, "detected_stack": profile, "adapters": adapters}
    write_adapter_files(root, adapters)
    write_json(state(root) / "runtime-adapters.json", payload)
    write_json(reports(root) / "runtime-adapters.json", payload)
    write_text(reports(root) / "runtime-adapters.md", "\n".join([
        "# Runtime Adapters",
        "",
        "## Summary",
        "",
        f"- Detected stack: `{profile.get('id', 'unknown')}`",
        "",
        "| Adapter | Status | Feature slices |",
        "| --- | --- | ---: |",
        "\n".join(f"| `{a['id']}` | {a['match_status']} | {len(a['supported_feature_slices'])} |" for a in adapters),
    ]))
    return 0


def write_feature_files(root: Path, features: list[dict]) -> None:
    base = root / ".autospec/feature-slices"
    for item in features:
        out = base / item["category"] / f"{item['id']}.yml"
        lines = [
            f"id: {item['id']}",
            f"title: {item['title']}",
            f"category: {item['category']}",
            f"summary: {item['summary']}",
            "source_rules:",
            *[f"  - {r}" for r in item["source_rules"]],
            "source_baselines:",
            *[f"  - {b}" for b in item["source_baselines"]],
            f"requires_adapter: {str(item['requires_adapter']).lower()}",
            "supported_adapters:",
            *[f"  - {a}" for a in item["supported_adapters"]],
            f"implementation_kind: {item['implementation_kind']}",
            f"runtime_claim_level: {item['runtime_claim_level']}",
            f"risk_level: {item['risk_level']}",
            "not_in_scope:",
            *[f"  - {n}" for n in item["not_in_scope"]],
        ]
        write_text(out, "\n".join(lines))


def feature_slice_index(root: Path) -> int:
    features = built_in_slices()
    write_feature_files(root, features)
    payload = {"schema": 1, "feature_slices": features, "summary": {"total": len(features)}}
    write_json(state(root) / "feature-slices.json", payload)
    write_json(reports(root) / "feature-slices.json", payload)
    write_text(reports(root) / "feature-slices.md", "\n".join([
        "# Feature Slices",
        "",
        "## Summary",
        "",
        f"- Feature slices: {len(features)}",
        "",
        "| Feature | Category | Runtime claim |",
        "| --- | --- | --- |",
        "\n".join(f"| `{f['id']}` | {f['category']} | {f['runtime_claim_level']} |" for f in features),
    ]))
    return 0


def load_adapters(root: Path) -> list[dict]:
    data = load_json(state(root) / "runtime-adapters.json", {})
    if not data.get("adapters"):
        runtime_adapter_index(root)
        data = load_json(state(root) / "runtime-adapters.json", {})
    return data.get("adapters", [])


def load_features(root: Path) -> list[dict]:
    data = load_json(state(root) / "feature-slices.json", {})
    if not data.get("feature_slices"):
        feature_slice_index(root)
        data = load_json(state(root) / "feature-slices.json", {})
    return data.get("feature_slices", [])


def selected_feature(root: Path, feature_id: str) -> dict:
    features = load_features(root)
    return next((item for item in features if item["id"] == feature_id), features[0])


def selected_adapter(root: Path, feature_id: str) -> dict | None:
    candidates = [item for item in load_adapters(root) if item.get("match_status") == "available" and feature_id in item.get("supported_feature_slices", [])]
    if not candidates:
        return None
    return max(candidates, key=lambda item: len(item["detection"].get("required_files", [])))


def file_plan_for(root: Path, adapter_item: dict | None, feature_item: dict) -> tuple[list[str], list[str], list[str]]:
    fid = feature_item["id"]
    component, route = feature_item["generated_artifacts"][0], feature_item["generated_artifacts"][1]
    docs = [f"docs/specs/{fid}.md"]
    tests = [f"tests/e2e/autospec-{fid}.spec.ts"] if "@playwright/test" in package_text(root) else []
    if not adapter_item:
        return docs, [], []
    aid = adapter_item["id"]
    if aid == "react-vite":
        return [f"src/components/autospec/{component}.tsx", f"src/pages/{route}.tsx", *docs], [], tests
    if aid == "nextjs-app-router":
        return [f"src/components/autospec/{component}.tsx", f"app/{slug(route)}/page.tsx", *docs], [], tests
    if aid == "nextjs-pages-router":
        return [f"src/components/autospec/{component}.tsx", f"pages/{slug(route)}.tsx", *docs], [], tests
    return docs, [], tests


def runtime_plan(root: Path, feature_id: str = "", issue: str = "", rule_id: str = "") -> int:
    profile = stack_profile(root).get("primary_profile", {})
    if not feature_id:
        feature_id = "in-app-docs-center"
    feature_item = selected_feature(root, feature_id)
    adapter_item = selected_adapter(root, feature_id)
    confidence = float(profile.get("confidence", 0) or 0)
    files, updates, tests = file_plan_for(root, adapter_item, feature_item)
    status = "safe_to_generate"
    reason = "recognized stack and adapter support this feature slice"
    if confidence < 0.8:
        status, reason = "low_stack_confidence", "stack confidence is below 0.8"
    elif not adapter_item:
        status, reason = "missing_adapter", "no adapter supports this feature for the detected stack"
    elif feature_item["runtime_claim_level"] == "shell":
        status = "safe_to_generate"
    payload = {
        "schema": 1,
        "plans": [{
            "feature_slice_id": feature_item["id"],
            "source_rule_ids": feature_item["source_rules"],
            "adapter": adapter_item["id"] if adapter_item else "",
            "stack_confidence": confidence,
            "files_to_create": files,
            "files_to_update": updates,
            "tests_to_create": tests,
            "metadata_to_update": feature_item["metadata_updates"],
            "expected_validation": ["bash scripts/autospec-verify-runtime-feature.sh --dry-run"],
            "runtime_claim_level": feature_item["runtime_claim_level"],
            "risk": feature_item["risk_level"],
            "status": status,
            "reason": reason,
            "next_command": f"bash scripts/autospec-generate-runtime-feature.sh --dry-run --feature {feature_item['id']}",
        }]
    }
    write_json(state(root) / "runtime-implementation-plan.json", payload)
    write_json(reports(root) / "runtime-implementation-plan.json", payload)
    write_text(reports(root) / "runtime-implementation-plan.md", "\n".join([
        "# Runtime Implementation Plan",
        "",
        "## Summary",
        "",
        f"- Feature: `{feature_item['id']}`",
        f"- Status: `{status}`",
        f"- Adapter: `{adapter_item['id'] if adapter_item else 'none'}`",
        f"- Runtime claim level: `{feature_item['runtime_claim_level']}`",
        "",
        "## Expected files",
        "",
        "\n".join(f"- `{p}`" for p in files) or "- None.",
    ]))
    return 0


def generated_header(feature_id: str, claim: str, ext: str) -> str:
    text = f"{HEADER}\nFeature slice: {feature_id}.\nRuntime claim level: {claim}.\nReview before production use."
    return "\n".join(f"// {line}" for line in text.splitlines()) + "\n" if ext in {".tsx", ".ts", ".js"} else "<!-- " + text.replace("\n", " ") + " -->\n"


def component_body(feature_item: dict) -> str:
    fid = feature_item["id"]
    title = feature_item["title"]
    body_by_feature = {
        "ai-provider-settings": "OpenAI OpenAI-compatible Ollama base URL model embedding model RAG enabled token/cost tracking test connection placeholder secret references only",
        "ai-usage-token-dashboard": "prompt tokens completion tokens total tokens estimated cost requests user project model provider date chart placeholder export placeholder",
        "rag-assistant-shell": "chat UI citation/source area no-context fallback loading state error state docs/RAG source panel no model calls",
        "capability-interface-shell": "detected capabilities natural-language action mapping placeholder permission notes explainability area",
        "pretty-rendering-viewers": "JSON tree YAML code SQL viewer Markdown renderer table chart placeholder raw JSON avoidance policy",
        "analytics-dashboard-shell": "summary cards chart placeholder table placeholder filters empty loading error states chart selection policy",
    }
    body = body_by_feature.get(fid, "responsive shell empty state loading state error state accessibility notes keyboard focus notes")
    return f"export function {feature_item['generated_artifacts'][0]}() {{\n  return <main aria-label=\"{title}\"><h1>{title}</h1><p>{body}</p></main>;\n}}\n"


def route_body(feature_item: dict, route_rel: str) -> str:
    component = feature_item["generated_artifacts"][0]
    component_module = f"src/components/autospec/{component}"
    route_dir = Path(route_rel).parent.as_posix()
    import_path = os.path.relpath(component_module, route_dir).replace(os.sep, "/")
    if not import_path.startswith("."):
        import_path = f"./{import_path}"
    return f"import {{ {component} }} from '{import_path}';\n\nexport default function {feature_item['generated_artifacts'][1]}Page() {{\n  return <{component} />;\n}}\n"


def safe_write(root: Path, rel: str, text: str, confirm: bool) -> tuple[bool, str]:
    path = root / rel
    if any(rel.startswith(forbidden.rstrip("*")) for forbidden in [".github/workflows", ".env", "migrations/"]):
        return False, "forbidden path"
    if path.exists() and HEADER not in path.read_text(encoding="utf-8", errors="ignore"):
        return False, "unsafe overwrite blocked"
    if confirm:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return True, ""


def generate_runtime(root: Path, feature_id: str, issue: str = "", confirm: bool = False) -> int:
    runtime_plan(root, feature_id, issue)
    plan = load_json(state(root) / "runtime-implementation-plan.json", {"plans": []}).get("plans", [{}])[0]
    feature_item = selected_feature(root, plan.get("feature_slice_id") or feature_id)
    status = plan.get("status")
    if status not in {"safe_to_generate", "safe_shell_only"}:
        result = {"schema": 1, "feature_id": feature_item["id"], "status": status, "reason": plan.get("reason", ""), "side_effects": {"wrote_files": False}}
        write_json(reports(root) / "runtime-generation-result.json", result)
        write_text(reports(root) / "runtime-generation-result.md", f"# Runtime Generation Result\n\n## Summary\n\nBlocked: `{status}`")
        return 1
    created = []
    errors = []
    for rel in plan.get("files_to_create", []):
        suffix = Path(rel).suffix
        if rel.endswith(".tsx"):
            text = generated_header(feature_item["id"], feature_item["runtime_claim_level"], suffix)
            text += component_body(feature_item) if "/components/" in rel else route_body(feature_item, rel)
        else:
            extra = "\nNo database migration. No auth/security behavior change. No dependency installation.\n" if feature_item["id"] == "ai-usage-token-dashboard" else "\nShell/partial runtime slice; review before production use.\n"
            text = generated_header(feature_item["id"], feature_item["runtime_claim_level"], suffix) + f"# {feature_item['title']}\n{extra}"
        ok, err = safe_write(root, rel, text, confirm)
        if ok:
            created.append(rel)
        else:
            errors.append(f"{rel}: {err}")
    if feature_item["id"] in {"ai-usage-token-dashboard", "analytics-dashboard-shell", "pretty-rendering-viewers"}:
        dep = root / ".autospec/backlog/runtime-dependencies" / f"{feature_item['id']}.md"
        if confirm:
            write_text(dep, f"# Dependency decision for {feature_item['title']}\n\nNo dependencies were installed automatically. Decide chart/viewer/data dependencies through ADR first.\n")
    record = {
        "schema": 1,
        "feature_id": feature_item["id"],
        "adapter": plan.get("adapter"),
        "runtime_claim_level": feature_item["runtime_claim_level"],
        "status": "generated" if confirm else "planned",
        "generated_files": created,
        "metadata_updates": plan.get("metadata_to_update", []),
        "tests_to_create": plan.get("tests_to_create", []),
        "errors": errors,
        "side_effects": {"wrote_files": confirm},
    }
    write_json(reports(root) / "runtime-generation-plan.json", {"schema": 1, "plan": plan})
    write_text(reports(root) / "runtime-generation-plan.md", f"# Runtime Generation Plan\n\n## Summary\n\n- Feature: `{feature_item['id']}`\n- Runtime claim level: `{feature_item['runtime_claim_level']}`")
    write_json(reports(root) / "runtime-generation-result.json", record)
    write_text(reports(root) / "runtime-generation-result.md", f"# Runtime Generation Result\n\n## Summary\n\nStatus: `{record['status']}`\n\n## Runtime claim level\n\n`{feature_item['runtime_claim_level']}`")
    write_json(state(root) / "runtime-generations" / f"{feature_item['id']}.json", record)
    write_text(state(root) / "runtime-generations" / f"{feature_item['id']}.md", f"# Runtime Generation: {feature_item['id']}\n\nStatus: `{record['status']}`")
    return 0 if not errors else 1


def playwright_generation(root: Path, feature_id: str = "", confirm: bool = False) -> int:
    feature_id = feature_id or "in-app-docs-center"
    has_pw = "@playwright/test" in package_text(root)
    output = f"tests/e2e/autospec-{feature_id}.spec.ts"
    if has_pw and confirm:
        write_text(root / output, "\n".join([
            "// Generated by Autospec runtime feature generator.",
            f"// Feature slice: {feature_id}.",
            "import { test, expect } from '@playwright/test';",
            "test.describe('Autospec runtime evidence', () => {",
            "  for (const viewport of [{ width: 320, height: 640 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }]) {",
            "    test(`renders without white-screen at ${viewport.width}x${viewport.height}`, async ({ page }) => {",
            "      await page.setViewportSize(viewport);",
            "      await page.goto('/');",
            "      await expect(page.locator('body')).toBeVisible();",
            "    });",
            "  }",
            "});",
        ]))
    if not has_pw:
        issue = root / ".autospec/backlog/runtime-dependencies" / "playwright-adoption.md"
        write_text(issue, "# Playwright adoption decision\n\nPlaywright is missing; Autospec did not install it automatically.\n")
    payload = {"schema": 1, "feature_id": feature_id, "playwright_detected": has_pw, "output": output if has_pw else "", "side_effects": {"wrote_file": bool(has_pw and confirm)}}
    write_json(reports(root) / "playwright-generation-plan.json", payload)
    write_text(reports(root) / "playwright-generation-plan.md", "# Playwright Generation Plan\n\n## Summary\n\n" + ("Generate viewport/white-screen evidence tests." if has_pw else "Playwright missing; adoption spec generated."))
    write_json(reports(root) / "playwright-generation-result.json", payload)
    write_text(reports(root) / "playwright-generation-result.md", "# Playwright Generation Result\n\n## Summary\n\nDone.")
    return 0


def sync_runtime_metadata(root: Path, confirm: bool = False) -> int:
    records = [load_json(path, {}) for path in sorted((state(root) / "runtime-generations").glob("*.json"))]
    features = [{"feature_id": r.get("feature_id"), "runtime_claim_level": r.get("runtime_claim_level"), "files": r.get("generated_files", []), "provider_secret_policy": "references_only_no_values"} for r in records if r]
    if confirm:
        write_json(state(root) / "ui-surface.json", {"schema": 1, "features": features})
        write_json(state(root) / "capability-registry.json", {"schema": 1, "features": features})
        write_json(state(root) / "settings-registry.json", {"schema": 1, "features": features})
        write_json(state(root) / "ai-capabilities.json", {"schema": 1, "provider_secret_policy": "references_only_no_values", "features": features})
        write_json(state(root) / "report-registry.json", {"schema": 1, "features": features})
        write_json(state(root) / "tutorial-registry.json", {"schema": 1, "features": features})
        write_json(state(root) / "knowledge-graph.json", {"schema": 1, "runtime_feature_nodes": features})
    payload = {"schema": 1, "features": features, "side_effects": {"wrote_metadata": confirm}, "digital_twin_refresh": "skipped; local metadata sync only"}
    write_json(reports(root) / "runtime-metadata-sync.json", payload)
    write_text(reports(root) / "runtime-metadata-sync.md", f"# Runtime Metadata Sync\n\n## Summary\n\n- Features: {len(features)}\n- Digital Twin refresh: {payload['digital_twin_refresh']}")
    return 0


def verify_runtime(root: Path, feature_id: str = "", issue: str = "") -> int:
    feature_id = feature_id or load_json(reports(root) / "runtime-generation-result.json", {}).get("feature_id", "")
    record = load_json(state(root) / "runtime-generations" / f"{feature_id}.json", load_json(reports(root) / "runtime-generation-result.json", {}))
    findings = []
    if not record:
        findings.append("runtime-generation report missing")
    for rel in record.get("generated_files", []):
        path = root / rel
        if not path.exists() and record.get("status") == "generated":
            findings.append(f"generated file missing: {rel}")
        if path.exists():
            text = path.read_text(encoding="utf-8", errors="ignore")
            if "API_KEY" in text or "password=" in text.lower():
                findings.append(f"secret-like content exposed: {rel}")
            if record.get("runtime_claim_level") == "shell" and re.search(r"fully implemented|real model call|db persistence", text, re.I):
                findings.append(f"runtime claim overstated: {rel}")
    metadata = load_json(state(root) / "ui-surface.json", {})
    if record.get("status") == "generated" and not metadata:
        findings.append("metadata sync missing")
    verdict = "pass" if not findings else "warn"
    payload = {"schema": 1, "feature_id": feature_id, "verdict": verdict, "findings": findings, "runtime_claim_honesty": "checked", "side_effects": {"github_writes": False}}
    write_json(reports(root) / "runtime-feature-verification.json", payload)
    write_text(reports(root) / "runtime-feature-verification.md", "\n".join([
        "# Runtime Feature Verification",
        "",
        "## Summary",
        "",
        f"- Verdict: `{verdict}`",
        "",
        "## Runtime Claim Honesty",
        "",
        "- Shell/partial/complete wording checked.",
        "",
        "## Findings",
        "",
        "\n".join(f"- {f}" for f in findings) or "- None.",
    ]))
    return 0 if verdict in {"pass", "warn"} else 1


def worker_runtime(root: Path, feature_id: str, issue: str, confirm: bool) -> int:
    runtime_adapter_index(root)
    feature_slice_index(root)
    runtime_plan(root, feature_id, issue)
    code = generate_runtime(root, feature_id, issue, confirm)
    if code == 0:
        playwright_generation(root, feature_id, confirm)
        sync_runtime_metadata(root, confirm)
        verify_runtime(root, feature_id, issue)
    result = load_json(reports(root) / "runtime-generation-result.json", {})
    md = "\n".join([
        "# Runtime Feature Generation",
        "",
        "## Summary",
        "",
        f"- Feature: `{feature_id}`",
        f"- Status: `{result.get('status', 'unknown')}`",
        f"- Runtime claim level: `{result.get('runtime_claim_level', 'unknown')}`",
        "",
        "## Source issue",
        "",
        f"`{issue}`",
        "",
        "## Constitution/baseline references",
        "",
        "- Constitution rule context: runtime feature slice.",
        "- Baseline: target-app runtime shell.",
        "",
        "## Safety notes",
        "",
        "- No GitHub writes, migrations, auth/security changes, dependency upgrades, scheduler, merge, or approval.",
    ])
    write_text(reports(root) / "worker-runtime-feature-result.md", md)
    write_text(reports(root) / "worker-pr-body.md", md)
    if code == 0:
        evidence_helper = Path(__file__).with_name("autospec-evidence-v1-lib.py")
        if evidence_helper.exists():
            subprocess.run(
                [
                    sys.executable,
                    str(evidence_helper),
                    "--repo-root",
                    str(root),
                    "--command",
                    "worker-evidence",
                    "--issue",
                    issue,
                    "--feature",
                    feature_id,
                ],
                cwd=str(root),
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
    return code


def runtime_status(root: Path) -> int:
    adapters = load_adapters(root)
    features = load_features(root)
    generations = [load_json(path, {}) for path in sorted((state(root) / "runtime-generations").glob("*.json"))]
    available = [a for a in adapters if a.get("match_status") == "available"]
    blocked = [f for f in features if not any(f["id"] in a.get("supported_feature_slices", []) for a in available)]
    runtime_evidence = load_json(reports(root) / "runtime-evidence-status.json", {})
    payload = {"schema": 1, "supported_adapters": [a["id"] for a in available], "detected_stack": stack_profile(root).get("primary_profile", {}), "safe_feature_slices": [f["id"] for f in features if f not in blocked], "generated_runtime_features": generations, "blocked_runtime_features": [f["id"] for f in blocked], "runtime_evidence_status": runtime_evidence.get("summary", runtime_evidence.get("status", "unknown"))}
    write_json(reports(root) / "runtime-feature-status.json", payload)
    write_text(reports(root) / "runtime-feature-status.md", "\n".join([
        "# Runtime Feature Status",
        "",
        "## Summary",
        "",
        f"- Supported adapters: {len(available)}",
        "",
        "## Supported adapters",
        "",
        "\n".join(f"- `{a}`" for a in payload["supported_adapters"]) or "- None.",
        "",
        "## Detected stack",
        "",
        f"`{payload['detected_stack'].get('id', 'unknown')}`",
        "",
        "## Safe feature slices",
        "",
        "\n".join(f"- `{f}`" for f in payload["safe_feature_slices"][:20]) or "- None.",
        "",
        "## Generated runtime features",
        "",
        "\n".join(f"- `{g.get('feature_id')}`" for g in generations) or "- None.",
        "",
        "## Runtime shells",
        "",
        "\n".join(f"- `{g.get('feature_id')}`" for g in generations if g.get("runtime_claim_level") == "shell") or "- None.",
        "",
        "## Partial implementations",
        "",
        "\n".join(f"- `{g.get('feature_id')}`" for g in generations if g.get("runtime_claim_level") == "partial") or "- None.",
        "",
        "## Blocked runtime features",
        "",
        str(len(blocked)),
        "",
        "## Missing dependencies",
        "",
        "- See `.autospec/backlog/runtime-dependencies/`.",
        "",
        "## Required human decisions",
        "",
        "- Dependency, migration, auth/security, and complete runtime decisions require humans.",
        "",
        "## Test/evidence status",
        "",
        f"- Runtime evidence status: `{payload['runtime_evidence_status']}`",
        "- See Playwright generation and runtime evidence reports.",
        "",
        "## Metadata sync status",
        "",
        "- See runtime metadata sync report.",
        "",
        "## Next commands",
        "",
        "- `bash scripts/autospec-runtime-implementation-plan.sh --dry-run --feature in-app-docs-center`",
    ]))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--command", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--confirm", action="store_true")
    parser.add_argument("--feature", default="")
    parser.add_argument("--issue", default="")
    parser.add_argument("--rule", default="")
    args = parser.parse_args()
    root = Path(args.repo_root).resolve()
    handlers = {
        "adapter-index": lambda: runtime_adapter_index(root),
        "feature-slice-index": lambda: feature_slice_index(root),
        "runtime-plan": lambda: runtime_plan(root, args.feature, args.issue, args.rule),
        "generate-runtime": lambda: generate_runtime(root, args.feature or "in-app-docs-center", args.issue, args.confirm),
        "playwright-generation": lambda: playwright_generation(root, args.feature, args.confirm),
        "metadata-sync": lambda: sync_runtime_metadata(root, args.confirm),
        "verify-runtime": lambda: verify_runtime(root, args.feature, args.issue),
        "worker-runtime": lambda: worker_runtime(root, args.feature or "in-app-docs-center", args.issue or "1", args.confirm),
        "status": lambda: runtime_status(root),
    }
    if args.command not in handlers:
        raise SystemExit(f"unknown command: {args.command}")
    return handlers[args.command]()


if __name__ == "__main__":
    raise SystemExit(main())
