#!/usr/bin/env bash
# scripts/autospec-ensure-labels.sh — provision Autospec control labels.
#
# Dry-run by default. Real GitHub writes require --confirm. Reads the local
# control label taxonomy generated by autospec-bot-state-init.sh.

set -eu

usage() {
    cat <<'EOF'
Usage:
  autospec-ensure-labels.sh [--repo-root <dir>] [--dry-run|--confirm] [--repo OWNER/REPO]

Writes:
  .autospec/reports/github-label-plan.json   (dry-run)
  .autospec/reports/github-label-plan.md     (dry-run)
  .autospec/reports/github-label-apply.json  (--confirm)
  .autospec/reports/github-label-apply.md    (--confirm)
EOF
}

die() {
    printf 'autospec-ensure-labels: %s\n' "$*" >&2
    exit 2
}

REPO_ROOT="$(pwd)"
CONFIRM=0
GH_REPO=""
while [ "$#" -gt 0 ]; do
    case "$1" in
        --repo-root) [ "$#" -ge 2 ] || die "--repo-root requires a value"; REPO_ROOT="$2"; shift 2 ;;
        --dry-run) CONFIRM=0; shift ;;
        --confirm) CONFIRM=1; shift ;;
        --repo) [ "$#" -ge 2 ] || die "--repo requires OWNER/REPO"; GH_REPO="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) die "unknown arg: $1" ;;
    esac
done

[ -d "$REPO_ROOT" ] || die "--repo-root does not exist: $REPO_ROOT"
REPO_ROOT="$(cd "$REPO_ROOT" && pwd -P)"

python3 - "$REPO_ROOT" "$CONFIRM" "$GH_REPO" <<'PY'
import json
import os
import subprocess
import sys

try:
    import yaml
except Exception as exc:
    print(f"autospec-ensure-labels: python yaml module is required: {exc}", file=sys.stderr)
    sys.exit(2)

repo_root = os.path.realpath(sys.argv[1])
confirm = sys.argv[2] == "1"
gh_repo = sys.argv[3]
state_dir = os.path.join(repo_root, ".autospec", "state")
reports_dir = os.path.join(repo_root, ".autospec", "reports")
labels_path = os.path.join(state_dir, "control-labels.yml")
json_report = os.path.join(reports_dir, "github-label-apply.json" if confirm else "github-label-plan.json")
md_report = os.path.join(reports_dir, "github-label-apply.md" if confirm else "github-label-plan.md")

COLORS = {
    "autospec:managed": "5319e7",
    "autospec:discovered": "1d76db",
    "autospec:active": "0e8a16",
    "autospec:paused": "fbca04",
    "autospec:blocked": "b60205",
    "autospec:stuck": "d93f0b",
    "autospec:needs-guidance": "d4c5f9",
    "autospec:guidance-provided": "c2e0c6",
    "autospec:resume": "0e8a16",
    "autospec:needs-review": "006b75",
    "autospec:architecture": "5319e7",
    "autospec:risk-high": "b60205",
    "autospec:self-improvement": "bfd4f2",
    "autospec:follow-up": "cfd3d7",
}


def write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, sort_keys=True)
        fh.write("\n")


def load_labels():
    with open(labels_path, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    labels = data.get("labels", {}) if isinstance(data, dict) else {}
    return [(name, spec) for name, spec in sorted(labels.items())]


def gh_base():
    base = ["gh"]
    if gh_repo:
        base.extend(["--repo", gh_repo])
    return base


def run_gh(args):
    cmd = gh_base() + args
    completed = subprocess.run(cmd, cwd=repo_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if completed.returncode != 0:
        raise RuntimeError(f"{' '.join(cmd)} failed: {completed.stderr.strip() or completed.stdout.strip()}")
    return completed.stdout.strip()


def manual_instruction(name, description, color):
    repo_args = f"--repo {gh_repo} " if gh_repo else ""
    return {
        "label": name,
        "command": f"gh {repo_args}label create {name} --color {color} --description {description!r} --force",
        "description": description,
        "color": color,
    }


def permission_error(text):
    lowered = text.lower()
    return any(token in lowered for token in ["permission", "403", "resource not accessible", "forbidden", "not authorized"])


def write_reports(mode, status, actions, errors, manual_instructions):
    report = {
        "version": 1,
        "mode": mode,
        "status": status,
        "source": ".autospec/state/control-labels.yml",
        "labels": actions,
        "errors": errors,
        "manual_instructions": manual_instructions,
        "side_effects": {"github_api_calls": bool(confirm), "github_labels_written": bool(confirm and not errors)},
    }
    write_json(json_report, report)
    lines = [
        "# GitHub Label Provisioning",
        "",
        f"Status: **{status.upper()}**",
        f"Mode: `{mode}`",
        "",
        "| Label | Action | Color | Description | Purpose | State-machine effect |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in actions:
        lines.append(f"| `{item['name']}` | {item['action']} | `{item['color']}` | {item['description']} | {item['purpose']} | {item['state_machine_effect']} |")
    if errors:
        lines.extend(["", "## Errors", ""])
        for error in errors:
            lines.append(f"- {error}")
    if manual_instructions:
        lines.extend(["", "## Manual creation instructions", ""])
        lines.append("The GitHub token/app/CLI could not create one or more labels. Create the missing labels manually with:")
        lines.append("")
        lines.append("```bash")
        for item in manual_instructions:
            lines.append(item["command"])
        lines.append("```")
    with open(md_report, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
        fh.write("\n")


if not os.path.isfile(labels_path):
    error = "missing .autospec/state/control-labels.yml; run scripts/autospec-bot-state-init.sh first"
    write_reports("confirm" if confirm else "dry_run", "error", [], [error], [])
    print(f"label provisioning: ERROR - {error}")
    sys.exit(2)

labels = load_labels()
actions = []
errors = []
manual_instructions = []
for name, spec in labels:
    purpose = str(spec.get("purpose", ""))
    state_machine_effect = str(spec.get("state_machine_effect", ""))
    description = purpose[:100]
    color = COLORS.get(name, "ededed")
    action = "would_create_or_update"
    if confirm:
        try:
            run_gh(["label", "create", name, "--color", color, "--description", description, "--force"])
            action = "created_or_updated"
        except Exception as exc:
            action = "failed"
            error = f"{name}: {exc}"
            errors.append(error)
            if permission_error(error):
                manual_instructions.append(manual_instruction(name, description, color))
    actions.append({
        "name": name,
        "description": description,
        "color": color,
        "purpose": purpose,
        "state_machine_effect": state_machine_effect,
        "action": action,
    })

status = "fail" if errors else "pass"
mode = "confirm" if confirm else "dry_run"
write_reports(mode, status, actions, errors, manual_instructions)
if errors:
    print("label provisioning: FAIL")
    for error in errors:
        print(f"- {error}")
    sys.exit(1)
print("label provisioning: PASS" if confirm else "label provisioning: DRY-RUN")
if confirm:
    print("reports: .autospec/reports/github-label-apply.json, .autospec/reports/github-label-apply.md")
else:
    print("reports: .autospec/reports/github-label-plan.json, .autospec/reports/github-label-plan.md")
PY
