#!/usr/bin/env python3
"""Shared constants and artifact IO for the autonomy v2 helpers.

Extracted from autospec-autonomy-v2-lib.py so that file can come under the
repo's file-size gate and so the sibling autonomy modules can share these
primitives. The lib's own filename contains hyphens and is therefore not
importable; these helpers live here instead.

Behaviour is identical to the originals — this is a move, not a rewrite.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

GENERATED_HEADER = "Generated by Autospec from template"
SAFE_OUTPUT_PREFIXES = ("docs/", "tests/", ".autospec/", "src/")
FORBIDDEN_PATHS = [".github/workflows/**", ".env", ".env.*", "**/migrations/**", "package.json", "pyproject.toml"]
CAPABILITY_IDS = [
    "docs", "specs", "metadata", "tests", "cli", "scripts", "ui_scaffold", "api_scaffold",
    "settings_scaffold", "ai_scaffold", "nlai_scaffold", "diagnostics_scaffold",
    "reporting_scaffold", "playwright_scaffold", "security_privacy_docs",
    "dependency_planning", "modernization_planning",
]


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def yaml_scalar(value) -> str:
    text = str(value)
    if text in {"true", "false", "[]"} or re.fullmatch(r"-?\d+(?:\.\d+)?", text):
        return text
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def load_json(path: Path, default):
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else default
    except Exception:
        return default


def reports(root: Path) -> Path:
    path = root / ".autospec/reports"
    path.mkdir(parents=True, exist_ok=True)
    return path


def state(root: Path) -> Path:
    path = root / ".autospec/state"
    path.mkdir(parents=True, exist_ok=True)
    return path


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "item"
