#!/usr/bin/env python3
"""Autonomy v2 local recipe helpers.

The implementation is deliberately bounded: recipes can generate plans,
templates, metadata, and dry-run execution reports. Confirmed writes only touch
operator-approved generated docs/tests/scaffold paths.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


GENERATED_HEADER = "Generated by Autospec from template"
SAFE_OUTPUT_PREFIXES = ("docs/", "tests/", ".autospec/", "src/")
FORBIDDEN_PATHS = [".github/workflows/**", ".env", ".env.*", "**/migrations/**", "package.json", "pyproject.toml"]
CAPABILITY_IDS = [
    "docs", "specs", "metadata", "tests", "cli", "scripts", "ui_scaffold", "api_scaffold",
    "settings_scaffold", "ai_scaffold", "nlai_scaffold", "diagnostics_scaffold",
    "reporting_scaffold", "playwright_scaffold", "security_privacy_docs",
    "dependency_planning", "modernization_planning",
]


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def yaml_scalar(value) -> str:
    text = str(value)
    if text in {"true", "false", "[]"} or re.fullmatch(r"-?\d+(?:\.\d+)?", text):
        return text
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def load_json(path: Path, default):
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else default
    except Exception:
        return default


def reports(root: Path) -> Path:
    path = root / ".autospec/reports"
    path.mkdir(parents=True, exist_ok=True)
    return path


def state(root: Path) -> Path:
    path = root / ".autospec/state"
    path.mkdir(parents=True, exist_ok=True)
    return path


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "item"


def default_capabilities() -> list[dict]:
    enabled = {"docs", "specs", "metadata", "tests", "cli", "scripts", "playwright_scaffold", "ai_scaffold", "nlai_scaffold", "diagnostics_scaffold", "reporting_scaffold", "security_privacy_docs", "dependency_planning", "modernization_planning"}
    experimental = {"ui_scaffold", "api_scaffold", "settings_scaffold"}
    rows = []
    for cap in CAPABILITY_IDS:
        status = "enabled" if cap in enabled else "experimental" if cap in experimental else "planned"
        risk = "medium" if cap in experimental else "low"
        title = cap.replace("_", " ").title()
        if cap == "playwright_scaffold":
            title = "Playwright scaffolds"
        rows.append({
            "id": cap,
            "title": title,
            "status": status,
            "risk_level": risk,
            "allowed_by_default": cap in enabled,
            "allowed_paths": ["docs/**", ".autospec/**", "tests/**"] + (["src/**"] if cap in experimental else []),
            "forbidden_paths": FORBIDDEN_PATHS,
            "max_files_changed": 5 if cap in enabled else 3,
            "max_lines_changed": 250 if cap in enabled else 120,
            "requires_tests": cap in {"tests", "playwright_scaffold", "ui_scaffold", "api_scaffold", "settings_scaffold"},
            "requires_verifier": True,
            "requires_human_guidance": cap in {"api_scaffold", "settings_scaffold"} if cap in experimental else False,
            "requires_architecture_review": cap in {"api_scaffold", "settings_scaffold"},
            "can_modify_code": cap in {"cli", "scripts", "tests", "playwright_scaffold", "ui_scaffold", "api_scaffold", "settings_scaffold"},
            "can_modify_dependencies": False,
            "can_modify_database": False,
            "can_modify_auth_security": False,
            "supported_repo_types": ["web", "cli", "internal-tool"],
            "supported_technologies": [],
            "input_requirements": ["structured rule or explicit operator request"],
            "output_artifacts": [".autospec/reports", ".autospec/state"],
            "validation_expectations": ["focused validation or honest skip rationale"],
            "fallback_when_unsafe": "stuck/guidance",
        })
    return rows


def capability_yaml(rows: list[dict]) -> str:
    lines = ["schema: 1", "capabilities:"]
    for row in rows:
        lines.extend([
            f"- id: {row['id']}",
            f"  title: {row['title']}",
            f"  status: {row['status']}",
            f"  risk_level: {row['risk_level']}",
            f"  allowed_by_default: {str(row['allowed_by_default']).lower()}",
            "  allowed_paths:",
            *[f"    - {yaml_scalar(p)}" for p in row["allowed_paths"]],
            "  forbidden_paths:",
            *[f"    - {yaml_scalar(p)}" for p in row["forbidden_paths"]],
            f"  max_files_changed: {row['max_files_changed']}",
            f"  max_lines_changed: {row['max_lines_changed']}",
            f"  requires_tests: {str(row['requires_tests']).lower()}",
            "  requires_verifier: true",
            f"  requires_human_guidance: {str(row['requires_human_guidance']).lower()}",
            f"  requires_architecture_review: {str(row['requires_architecture_review']).lower()}",
            f"  can_modify_code: {str(row['can_modify_code']).lower()}",
            "  can_modify_dependencies: false",
            "  can_modify_database: false",
            "  can_modify_auth_security: false",
            "  supported_repo_types: []",
            "  supported_technologies: []",
            "  input_requirements:",
            "    - structured rule or explicit operator request",
            "  output_artifacts:",
            "    - .autospec/reports",
            "  validation_expectations:",
            "    - focused validation or honest skip rationale",
            "  fallback_when_unsafe: stuck/guidance",
        ])
    return "\n".join(lines) + "\n"


def load_capability_statuses(root: Path) -> dict[str, str]:
    path = state(root) / "worker-capabilities.yml"
    if not path.exists():
        ensure_capabilities(root)
    statuses = {}
    current = None
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        m = re.match(r"- id:\s*(\S+)", line)
        if m:
            current = m.group(1)
        m = re.match(r"\s+status:\s*(\S+)", line)
        if m and current:
            statuses[current] = m.group(1)
    return statuses


def ensure_capabilities(root: Path) -> list[dict]:
    rows = default_capabilities()
    write_text(state(root) / "worker-capabilities.yml", capability_yaml(rows))
    write_json(state(root) / "worker-capabilities.json", {"schema": 1, "capabilities": rows})
    write_text(reports(root) / "worker-capabilities.md", "\n".join([
        "# Worker Capabilities",
        "",
        "## Summary",
        "",
        f"- Capabilities: {len(rows)}",
        "",
        "| Capability | Status | Risk | Code |",
        "| --- | --- | --- | --- |",
        "\n".join(f"| `{r['id']}` | {r['status']} | {r['risk_level']} | {r['can_modify_code']} |" for r in rows),
    ]))
    return rows


def built_in_recipes() -> list[dict]:
    def recipe(rid, title, category, capability, checks, mode="scaffold", expected=None, stacks=None, risk="low"):
        return {
            "id": rid,
            "title": title,
            "summary": title,
            "category": category,
            "capability": capability,
            "applies_to_rules": checks,
            "applies_to_capabilities": [capability],
            "repo_conditions": {"application_types": ["web", "cli"], "technologies": stacks or [], "required_files": [], "optional_files": []},
            "risk": {"level": risk, "requires_human_guidance": risk == "high", "requires_architecture_review": risk == "high"},
            "implementation": {"mode": mode, "allowed_paths": ["docs/**", ".autospec/**", "tests/**", "src/**"], "forbidden_paths": FORBIDDEN_PATHS, "max_files_changed": 5, "max_lines_changed": 250, "expected_files": {"create": expected or [], "update": [], "inspect": []}},
            "test_plan": {"required": mode in {"test", "scaffold"}, "suggested_commands": ["bash scripts/autospec-rule-recheck.sh --dry-run"], "generated_tests": expected or []},
            "validation": {"commands": ["bash scripts/autospec-rule-recheck.sh --dry-run"], "required_evidence": ["report"]},
            "docs": {"update": ["docs/specs"]},
            "metadata": {"update": [".autospec/state"]},
            "acceptance_criteria": [f"{title} scaffold/spec exists.", "Rule recheck is honest about before/after status."],
            "stuck_if": ["stack confidence is low", "capability is disabled", "forbidden path required"],
            "status": "supported",
        }
    return [
        recipe("in-app-docs-center", "In-app documentation center", "docs", "docs", ["required_in_app_documentation", "docs.in_app_docs"], "docs", ["docs/specs/in-app-documentation-center.md"]),
        recipe("rag-ready-docs", "RAG-ready documentation", "docs", "docs", ["required_rag_ready_documentation"], "docs", ["docs/specs/rag-ready-docs.md"]),
        recipe("tutorial-docs", "Tutorial documentation", "docs", "docs", ["required_tutorials_for_user_workflows"], "docs", ["docs/tutorials/autospec-tutorial.md"]),
        recipe("playwright-viewport-matrix", "Playwright viewport matrix", "tests", "playwright_scaffold", ["required_playwright_viewport_matrix", "testing.playwright.viewport"], "test", ["tests/e2e/autospec-viewport.spec.ts"], ["react", "vite", "nextjs", "playwright"]),
        recipe("accessibility-smoke", "Accessibility smoke test", "tests", "playwright_scaffold", ["required_accessibility_checklist", "required_playwright_accessibility_flow"], "test", ["tests/e2e/autospec-accessibility.spec.ts"], ["playwright"]),
        recipe("metadata-drift-test", "Metadata drift test", "tests", "tests", ["required_docs_drift_check"], "test", ["tests/unit/autospec-metadata-drift.bats"]),
        recipe("settings-page-scaffold", "Settings page scaffold", "ui", "settings_scaffold", ["required_settings_area", "required_ai_settings_page"], "scaffold", ["src/components/AutospecSettings.tsx"], ["react", "vite", "nextjs"], "medium"),
        recipe("documentation-route-scaffold", "Documentation route scaffold", "ui", "ui_scaffold", ["required_in_app_docs"], "scaffold", ["src/components/AutospecDocs.tsx"], ["react", "vite", "nextjs"], "medium"),
        recipe("status-page-scaffold", "Status page scaffold", "ui", "diagnostics_scaffold", ["required_status_page"], "scaffold", ["docs/specs/status-page.md"], ["react", "vite", "nextjs"]),
        recipe("feedback-flow-scaffold", "Feedback flow scaffold", "ui", "ui_scaffold", ["required_feedback_flow"], "scaffold", ["docs/specs/feedback-flow.md"], ["react", "vite", "nextjs"], "medium"),
        recipe("ai-provider-config-scaffold", "AI provider config scaffold", "ai", "ai_scaffold", ["required_ai_provider_abstraction", "ai.provider"], "scaffold", ["docs/specs/ai-provider-abstraction.md"]),
        recipe("rag-assistant-scaffold", "RAG assistant scaffold", "ai", "ai_scaffold", ["required_rag_indexing", "required_rag_capability"], "scaffold", ["docs/specs/rag-assistant.md"]),
        recipe("token-usage-scaffold", "Token usage scaffold", "ai", "ai_scaffold", ["required_token_usage_tracking", "required_multi_user_token_usage_tracking"], "planning_only", ["docs/specs/token-usage.md"]),
        recipe("ai-settings-page-scaffold", "AI settings page scaffold", "ai", "ai_scaffold", ["required_ai_settings_page", "required_ai_settings"], "scaffold", ["docs/specs/ai-settings-page.md"]),
        recipe("mcp-registry-scaffold", "MCP registry scaffold", "ai", "ai_scaffold", ["required_mcp_registry", "required_diagnostic_mcp_registry"], "scaffold", ["docs/specs/mcp-registry.md"]),
        recipe("capability-interface-scaffold", "NLAI capability interface", "nlai", "nlai_scaffold", ["required_nlai_capability_registry", "required_nlai_tool_interface"], "scaffold", ["docs/specs/nlai-capability-interface.md"]),
        recipe("pretty-rendering-scaffold", "Pretty rendering scaffold", "nlai", "nlai_scaffold", ["required_pretty_human_output", "required_pretty_rendering"], "scaffold", ["docs/specs/pretty-rendering.md"]),
        recipe("sql-query-interface-scaffold", "SQL query interface spec", "nlai", "nlai_scaffold", ["required_nlai_sql_generation_for_data_apps"], "planning_only", ["docs/specs/sql-query-interface.md"]),
        recipe("file-operations-interface-scaffold", "File operations interface spec", "nlai", "nlai_scaffold", ["required_nlai_file_operations_for_file_apps"], "planning_only", ["docs/specs/file-operations-interface.md"]),
        recipe("health-check-scaffold", "Health check scaffold", "diagnostics", "diagnostics_scaffold", ["required_health_check"], "scaffold", ["docs/specs/health-check.md"]),
        recipe("white-screen-diagnostic-scaffold", "White-screen diagnostic scaffold", "diagnostics", "diagnostics_scaffold", ["required_white_screen_diagnosis"], "test", ["tests/e2e/autospec-white-screen.spec.ts"], ["playwright"]),
        recipe("incident-report-scaffold", "Incident report scaffold", "diagnostics", "diagnostics_scaffold", ["required_incident_report_template"], "docs", ["docs/specs/incident-report-template.md"]),
        recipe("metrics-definition-scaffold", "Metrics definition scaffold", "reporting", "reporting_scaffold", ["required_metrics_definitions"], "docs", ["docs/specs/metrics-definition.yml"]),
        recipe("report-template-scaffold", "Report template scaffold", "reporting", "reporting_scaffold", ["required_report_generation"], "docs", ["docs/specs/report-template.md"]),
        recipe("visualization-standard-scaffold", "Visualization standard scaffold", "reporting", "reporting_scaffold", ["required_visualization_library_standard"], "docs", ["docs/specs/visualization-standard.md"]),
        recipe("governance-policy", "Dependency governance policy", "dependencies", "dependency_planning", ["required_dependency_governance_policy"], "planning_only", ["docs/specs/dependency-governance.md"]),
        recipe("modernization-plan", "Modernization plan", "dependencies", "modernization_planning", ["required_modernization_plan"], "planning_only", ["docs/specs/modernization-plan.md"]),
        recipe("threat-model-doc", "Threat model doc", "security-privacy", "security_privacy_docs", ["required_threat_model"], "docs", ["docs/specs/threat-model.md"], risk="medium"),
        recipe("permission-model-doc", "Permission model doc", "security-privacy", "security_privacy_docs", ["required_permission_model_for_multi_user"], "docs", ["docs/specs/permission-model.md"], risk="medium"),
        recipe("pii-retention-doc", "PII retention doc", "security-privacy", "security_privacy_docs", ["required_pii_inventory", "required_retention_policy"], "docs", ["docs/specs/pii-retention.md"], risk="medium"),
    ]


def write_recipe_files(root: Path, recipes: list[dict]) -> None:
    base = root / ".autospec/recipes"
    write_text(base / "README.md", "# Autospec Implementation Recipes\n\nRecipes map structured rule failures to bounded worker actions.\n")
    def list_block(name: str, values: list[str], indent: str = "") -> list[str]:
        return [f"{indent}{name}:"] + ([f"{indent}  - {yaml_scalar(value)}" for value in values] if values else [f"{indent}  []"])
    for recipe in recipes:
        out = base / recipe["category"] / f"{recipe['id']}.yml"
        impl = recipe["implementation"]
        expected = impl["expected_files"]
        lines = [
            f"id: {yaml_scalar(recipe['id'])}",
            f"title: {yaml_scalar(recipe['title'])}",
            f"summary: {yaml_scalar(recipe['summary'])}",
            f"category: {yaml_scalar(recipe['category'])}",
            *list_block("applies_to_rules", recipe["applies_to_rules"]),
            *list_block("applies_to_capabilities", recipe["applies_to_capabilities"]),
            "repo_conditions:",
            *list_block("application_types", recipe["repo_conditions"]["application_types"], "  "),
            *list_block("technologies", recipe["repo_conditions"]["technologies"], "  "),
            *list_block("required_files", recipe["repo_conditions"]["required_files"], "  "),
            *list_block("optional_files", recipe["repo_conditions"]["optional_files"], "  "),
            "risk:",
            f"  level: {yaml_scalar(recipe['risk']['level'])}",
            f"  requires_human_guidance: {str(recipe['risk']['requires_human_guidance']).lower()}",
            f"  requires_architecture_review: {str(recipe['risk']['requires_architecture_review']).lower()}",
            "implementation:",
            f"  mode: {yaml_scalar(impl['mode'])}",
            *list_block("allowed_paths", impl["allowed_paths"], "  "),
            *list_block("forbidden_paths", impl["forbidden_paths"], "  "),
            f"  max_files_changed: {impl['max_files_changed']}",
            f"  max_lines_changed: {impl['max_lines_changed']}",
            "  expected_files:",
            *list_block("create", expected["create"], "    "),
            *list_block("update", expected["update"], "    "),
            *list_block("inspect", expected["inspect"], "    "),
            "test_plan:",
            f"  required: {str(recipe['test_plan']['required']).lower()}",
            *list_block("suggested_commands", recipe["test_plan"]["suggested_commands"], "  "),
            *list_block("generated_tests", recipe["test_plan"]["generated_tests"], "  "),
            "validation:",
            *list_block("commands", recipe["validation"]["commands"], "  "),
            *list_block("required_evidence", recipe["validation"]["required_evidence"], "  "),
            "docs:",
            *list_block("update", recipe["docs"]["update"], "  "),
            "metadata:",
            *list_block("update", recipe["metadata"]["update"], "  "),
            *list_block("acceptance_criteria", recipe["acceptance_criteria"]),
            *list_block("stuck_if", recipe["stuck_if"]),
        ]
        write_text(out, "\n".join(lines))


def recipe_index(root: Path) -> int:
    caps = ensure_capabilities(root)
    recipes = built_in_recipes()
    write_recipe_files(root, recipes)
    statuses = {c["id"]: c["status"] for c in caps}
    for recipe in recipes:
        if statuses.get(recipe["capability"]) not in {"enabled", "experimental"}:
            recipe["status"] = "unsupported"
            recipe["unsupported_reason"] = "requires disabled worker capability"
    payload = {"schema": 1, "recipes": recipes, "summary": {"total": len(recipes), "supported": sum(1 for r in recipes if r["status"] == "supported")}}
    write_json(state(root) / "implementation-recipes.json", payload)
    write_json(reports(root) / "implementation-recipes.json", payload)
    write_text(reports(root) / "implementation-recipes.md", "\n".join([
        "# Implementation Recipes",
        "",
        "## Summary",
        "",
        f"- Recipes: {len(recipes)}",
        "",
        "| Recipe | Capability | Mode | Status |",
        "| --- | --- | --- | --- |",
        "\n".join(f"| `{r['id']}` | `{r['capability']}` | `{r['implementation']['mode']}` | {r['status']} |" for r in recipes),
    ]))
    return 0


def detect_stack(root: Path) -> int:
    pkg = (root / "package.json").read_text(encoding="utf-8", errors="ignore").lower() if (root / "package.json").exists() else ""
    files = [p.relative_to(root).as_posix().lower() for p in root.rglob("*") if p.is_file() and ".git" not in p.parts and "node_modules" not in p.parts]
    profiles = []
    def add(pid, confidence, evidence, recipes=None):
        profiles.append({"id": pid, "confidence": confidence, "evidence": evidence, "supported_recipes": recipes or [], "unsupported_recipes": [], "notes": []})
    if "react" in pkg and "vite" in pkg and ("typescript" in pkg or any(f.endswith(".tsx") for f in files)):
        add("react-vite-typescript", 0.95, ["package.json: react/vite/typescript"], ["playwright-viewport-matrix", "documentation-route-scaffold", "settings-page-scaffold"])
    if "next" in pkg:
        add("nextjs-web-app", 0.9, ["package.json: next"], ["documentation-route-scaffold", "settings-page-scaffold"])
    if "fastapi" in pkg or (root / "pyproject.toml").exists() or any(f.endswith(".py") for f in files):
        add("python-cli-tool", 0.65, ["python files or pyproject"], ["metadata-drift-test"])
    if "@playwright/test" in pkg or any("playwright.config" in f for f in files):
        add("playwright", 0.9, ["Playwright dependency/config"], ["playwright-viewport-matrix", "accessibility-smoke"])
    if not profiles:
        add("unknown", 0.1, ["no recognized stack evidence"], [])
    primary = max(profiles, key=lambda p: p["confidence"])
    payload = {"schema": 1, "profiles": profiles, "primary_profile": primary}
    write_json(state(root) / "stack-profile.json", payload)
    write_text(reports(root) / "stack-profile.md", "\n".join(["# Stack Profile", "", "## Summary", "", f"- Primary: `{primary['id']}` ({primary['confidence']})"]))
    return 0


def recipes(root: Path) -> list[dict]:
    data = load_json(state(root) / "implementation-recipes.json", {})
    if not data.get("recipes"):
        recipe_index(root)
        data = load_json(state(root) / "implementation-recipes.json", {})
    return data.get("recipes", [])


def rule_results(root: Path) -> list[dict]:
    data = load_json(state(root) / "rule-check-results.json", load_json(reports(root) / "rule-check-results.json", {"results": []}))
    return data.get("results", [])


def rule_to_recipe(root: Path, rule_filter: str = "") -> int:
    statuses = load_capability_statuses(root)
    plans = []
    for rule in rule_results(root):
        if rule_filter and rule.get("rule_id") != rule_filter:
            continue
        if rule.get("status") not in {"fail", "partial", "unknown", "manual_review"}:
            continue
        best = None
        for recipe in recipes(root):
            hay = " ".join(recipe.get("applies_to_rules", []))
            if rule.get("rule_id", "") in hay or rule.get("check_type", "") in hay:
                best = recipe
                break
        if not best:
            status = "unsupported"
        elif statuses.get(best["capability"]) not in {"enabled", "experimental"}:
            status = "recipe_available_but_disabled"
        elif best["risk"]["requires_human_guidance"]:
            status = "requires_human_guidance"
        elif best["implementation"]["mode"] == "planning_only":
            status = "planning_only"
        else:
            status = "recipe_available"
        plans.append({
            "rule_id": rule.get("rule_id"),
            "status": status,
            "best_recipe": best["id"] if best else "",
            "fallback_recipe": "planning_only",
            "worker_eligibility": status == "recipe_available",
            "required_capability": best["capability"] if best else "",
            "estimated_risk": best["risk"]["level"] if best else "unknown",
            "expected_files": best["implementation"]["expected_files"] if best else {},
            "required_tests": best["test_plan"]["generated_tests"] if best else [],
            "required_validation": best["validation"]["commands"] if best else [],
            "human_guidance_required": status == "requires_human_guidance",
            "architecture_review_required": bool(best and best["risk"]["requires_architecture_review"]),
            "target_app_runtime_required": False,
        })
    payload = {"schema": 1, "plans": plans}
    write_json(reports(root) / "rule-to-recipe-plan.json", payload)
    write_json(state(root) / "rule-to-recipe-plan.json", payload)
    write_text(reports(root) / "rule-to-recipe-plan.md", "\n".join([
        "# Rule-to-Recipe Plan",
        "",
        "## Summary",
        "",
        f"- Plans: {len(plans)}",
        "",
        "## Implementable now",
        "",
        "\n".join(f"- `{p['rule_id']}` -> `{p['best_recipe']}`" for p in plans if p["status"] == "recipe_available") or "- None.",
        "",
        "## Scaffoldable now",
        "",
        "\n".join(f"- `{p['rule_id']}`" for p in plans if p["status"] in {"recipe_available", "planning_only"}) or "- None.",
        "",
        "## Planning-only",
        "",
        "\n".join(f"- `{p['rule_id']}`" for p in plans if p["status"] == "planning_only") or "- None.",
        "",
        "## Requires human guidance",
        "",
        "\n".join(f"- `{p['rule_id']}`" for p in plans if p["human_guidance_required"]) or "- None.",
        "",
        "## Unsupported",
        "",
        "\n".join(f"- `{p['rule_id']}`" for p in plans if p["status"] == "unsupported") or "- None.",
        "",
        "## Recommended next issues",
        "",
        "- Build patch plans for recipe_available rows.",
    ]))
    return 0


def find_recipe(root: Path, rid: str) -> dict | None:
    for recipe in recipes(root):
        if recipe["id"] == rid:
            return recipe
    return None


def decompose(root: Path, recipe_id: str) -> int:
    recipe = find_recipe(root, recipe_id) or {"id": recipe_id or "unknown", "title": "Unknown", "category": "unknown"}
    pieces = [
        "add AI capability metadata", "add provider settings spec", "add AI settings page scaffold", "add RAG indexing spec",
        "add token usage schema spec", "add usage dashboard spec", "add Playwright test plan", "add docs/tutorial update",
    ] if "ai" in recipe.get("category", "") or "ai" in recipe.get("id", "") else [
        f"apply {recipe['id']} scaffold", "add validation evidence", "update metadata", "update docs",
    ]
    backlog = root / ".autospec/backlog/decomposed"
    backlog.mkdir(parents=True, exist_ok=True)
    issues = []
    for idx, title in enumerate(pieces, start=1):
        path = backlog / f"{idx:03d}-{slug(title)}.md"
        body = "\n".join([f"# {title}", "", f"Parent recipe: `{recipe['id']}`", "", "## Scope", "", title, "", "## Non-goals", "", "- No broad rewrites.", "- No migrations/auth/security changes.", "", "## Acceptance criteria", "", f"- [ ] `{title}` is complete with evidence.", "", "## Validation", "", "- Run focused validation or document skip rationale.", "", "## Worker eligibility", "", "recipe-backed dry-run first.", "", "## Blocker/risk notes", "", "Use stuck/guidance if unsafe."])
        write_text(path, body)
        issues.append({"title": title, "path": str(path.relative_to(root)), "worker_eligible": True})
    payload = {"schema": 1, "recipe_id": recipe["id"], "issues": issues}
    write_json(reports(root) / "decomposition-plan.json", payload)
    write_text(reports(root) / "decomposition-plan.md", "# Decomposition Plan\n\n## Summary\n\n" + "\n".join(f"- {i['title']}" for i in issues))
    return 0


def patch_plan(root: Path, recipe_id: str, issue: str = "1") -> int:
    recipe = find_recipe(root, recipe_id) or recipes(root)[0]
    wid = state(root) / "work-items" / str(issue or recipe_id)
    expected = recipe["implementation"]["expected_files"]
    payload = {
        "schema": 1,
        "issue": issue,
        "recipe_id": recipe["id"],
        "files_to_inspect": expected.get("inspect", []),
        "files_to_create": expected.get("create", []),
        "files_to_update": expected.get("update", []),
        "files_forbidden": recipe["implementation"].get("forbidden_paths", FORBIDDEN_PATHS),
        "expected_line_budget": recipe["implementation"].get("max_lines_changed", 250),
        "test_files_expected": recipe["test_plan"].get("generated_tests", []),
        "docs_files_expected": [f for f in expected.get("create", []) if f.startswith("docs/")],
        "metadata_files_expected": recipe["metadata"].get("update", []),
        "rollback_plan": "Remove generated files and rerun rule recheck.",
        "validation_plan": recipe["validation"].get("commands", []),
        "risk_classification": recipe["risk"],
        "human_guidance_triggers": recipe.get("stuck_if", []),
    }
    write_json(reports(root) / "patch-plan.json", payload)
    write_json(wid / "patch-plan.json", payload)
    md = "\n".join(["# Patch Plan", "", "## Summary", "", f"- Recipe: `{recipe['id']}`", "", "## Rollback plan", "", payload["rollback_plan"], "", "## Validation plan", "", "\n".join(f"- `{c}`" for c in payload["validation_plan"])])
    write_text(reports(root) / "patch-plan.md", md)
    write_text(wid / "patch-plan.md", md)
    return 0


def render_template(text: str, vars_: dict[str, str]) -> tuple[str, list[str]]:
    unresolved = []
    def repl(match):
        key = match.group(1).strip()
        if key not in vars_:
            unresolved.append(key)
            return match.group(0)
        return vars_[key]
    return re.sub(r"\{\{([^}]+)\}\}", repl, text), unresolved


def apply_template(root: Path, template: str, output: str, confirm: bool, vars_: dict[str, str], allow_overwrite: bool = False) -> int:
    template_path = (root / template).resolve()
    output_path = (root / output).resolve()
    if not str(template_path).startswith(str(root)):
        raise SystemExit("template must be inside repo")
    rel_out = output_path.relative_to(root).as_posix() if str(output_path).startswith(str(root)) else ""
    if not rel_out or not rel_out.startswith(SAFE_OUTPUT_PREFIXES):
        result = {"schema": 1, "status": "blocked", "reason": "output path is outside allowed paths", "side_effects": {"wrote_file": False}}
        write_json(reports(root) / "template-apply-result.json", result)
        write_text(reports(root) / "template-apply-result.md", "# Template Apply Result\n\n## Summary\n\nBlocked: output path is outside allowed paths.")
        return 1
    text = template_path.read_text(encoding="utf-8")
    rendered, unresolved = render_template(text, vars_)
    if unresolved:
        result = {"schema": 1, "status": "blocked", "unresolved_variables": unresolved, "side_effects": {"wrote_file": False}}
        write_json(reports(root) / "template-apply-result.json", result)
        write_text(reports(root) / "template-apply-result.md", "# Template Apply Result\n\n## Summary\n\nBlocked: unresolved variables.")
        return 1
    if output_path.exists() and not allow_overwrite and GENERATED_HEADER not in output_path.read_text(encoding="utf-8", errors="ignore"):
        result = {"schema": 1, "status": "blocked", "reason": "unsafe overwrite blocked", "side_effects": {"wrote_file": False}}
        write_json(reports(root) / "template-apply-result.json", result)
        return 1
    plan = {"schema": 1, "template": template, "output": rel_out, "variables": sorted(vars_), "mode": "confirm" if confirm else "dry_run", "side_effects": {"wrote_file": False}}
    write_json(reports(root) / "template-apply-plan.json", plan)
    write_text(reports(root) / "template-apply-plan.md", f"# Template Apply Plan\n\n## Summary\n\n- Template: `{template}`\n- Output: `{rel_out}`")
    if confirm:
        prefix = f"<!-- {GENERATED_HEADER} {template}; edit source template or confirm manual ownership. -->\n"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(prefix + rendered, encoding="utf-8")
    result = {"schema": 1, "status": "applied" if confirm else "planned", "output": rel_out, "side_effects": {"wrote_file": confirm}}
    write_json(reports(root) / "template-apply-result.json", result)
    write_text(reports(root) / "template-apply-result.md", f"# Template Apply Result\n\n## Summary\n\nStatus: `{result['status']}`")
    return 0


def stack_confidence(root: Path) -> float:
    data = load_json(state(root) / "stack-profile.json", {})
    if not data:
        detect_stack(root)
        data = load_json(state(root) / "stack-profile.json", {})
    return float(data.get("primary_profile", {}).get("confidence", 0))


def worker_recipe(root: Path, recipe_id: str, issue: str, confirm: bool, auto: bool = False) -> int:
    if auto:
        rule_to_recipe(root)
        plans = load_json(state(root) / "rule-to-recipe-plan.json", {"plans": []}).get("plans", [])
        recipe_id = next((p["best_recipe"] for p in plans if p.get("status") == "recipe_available"), recipe_id)
    recipe = find_recipe(root, recipe_id)
    if not recipe:
        return write_worker_refusal(root, issue, recipe_id, "recipe missing")
    statuses = load_capability_statuses(root)
    if statuses.get(recipe["capability"]) not in {"enabled", "experimental"}:
        return write_worker_refusal(root, issue, recipe_id, "worker capability disabled")
    if recipe["capability"] in {"ui_scaffold", "settings_scaffold", "api_scaffold"} and stack_confidence(root) < 0.8:
        return write_worker_refusal(root, issue, recipe_id, "stack confidence too low for stack-specific scaffold")
    patch_plan(root, recipe["id"], issue)
    wid = state(root) / "work-items" / str(issue)
    created = recipe["implementation"]["expected_files"].get("create", [])
    execution = {"schema": 1, "issue": issue, "recipe_id": recipe["id"], "capability": recipe["capability"], "mode": "confirm" if confirm else "dry_run", "status": "executed", "generated_files": created, "rule_progress": "planned", "validation": recipe["validation"]["commands"], "side_effects": {"wrote_files": False}}
    write_json(wid / "recipe-execution.json", execution)
    write_json(reports(root) / "worker-recipe-execution.json", execution)
    md = "\n".join([
        "# Worker Recipe Execution",
        "",
        "## Summary",
        "",
        f"- Recipe: `{recipe['id']}`",
        f"- Capability: `{recipe['capability']}`",
        "- Implementation mode: scaffolded/planned unless rule recheck and tests prove runtime behavior.",
        "",
        "## Source issue",
        "",
        f"`{issue}`",
        "",
        "## Constitution/baseline references",
        "",
        "- Constitution rule context: recipe-backed bounded implementation.",
        f"- Baseline capability: `{recipe['capability']}`",
        "",
        "## Recipe Execution",
        "",
        f"Recipe: `{recipe['id']}`",
        "Capability: " + recipe["capability"],
        "Patch plan: `.autospec/reports/patch-plan.md`",
        "Generated files: " + ", ".join(created),
        "Rule progress: planned",
        "Validation: " + ", ".join(recipe["validation"]["commands"]),
        "",
        "## Acceptance criteria",
        "",
        *[f"- [ ] {item}" for item in recipe.get("acceptance_criteria", [])],
        "",
        "## Safety notes",
        "",
        "- No GitHub writes, merges, approvals, migrations, auth/security changes, or dependency upgrades were performed.",
    ])
    write_text(wid / "recipe-execution.md", md)
    write_text(reports(root) / "worker-recipe-execution.md", md)
    write_text(reports(root) / "worker-pr-body.md", md)
    return 0


def write_worker_refusal(root: Path, issue: str, recipe_id: str, reason: str) -> int:
    wid = state(root) / "work-items" / str(issue)
    execution = {"schema": 1, "issue": issue, "recipe_id": recipe_id, "status": "refused", "reason": reason, "side_effects": {"wrote_files": False}}
    write_json(wid / "recipe-execution.json", execution)
    write_json(reports(root) / "worker-recipe-execution.json", execution)
    write_text(reports(root) / "worker-recipe-execution.md", f"# Worker Recipe Execution\n\n## Summary\n\nRefused: {reason}\n")
    return 1


def evidence_tests(root: Path, capability: str, confirm: bool) -> int:
    output = "tests/e2e/autospec-viewport.spec.ts" if "viewport" in capability else "tests/e2e/autospec-evidence.spec.ts"
    plan = {"schema": 1, "capability": capability, "output": output, "mode": "confirm" if confirm else "dry_run", "playwright_detected": (root / "package.json").exists() and "@playwright/test" in (root / "package.json").read_text(encoding="utf-8", errors="ignore")}
    write_json(reports(root) / "evidence-test-generation-plan.json", plan)
    write_text(reports(root) / "evidence-test-generation-plan.md", "# Evidence Test Generation Plan\n\n## Summary\n\nPlaywright evidence test scaffold planned.\n")
    if confirm:
        path = root / output
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("// Generated by Autospec evidence test recipe\n", encoding="utf-8")
    write_json(reports(root) / "evidence-test-generation-result.json", {**plan, "side_effects": {"wrote_file": confirm}})
    write_text(reports(root) / "evidence-test-generation-result.md", "# Evidence Test Generation Result\n\n## Summary\n\nDone.\n")
    return 0


def rule_recheck(root: Path, rule_filter: str = "", issue: str = "1") -> int:
    rows = []
    for rule in rule_results(root):
        if rule_filter and rule.get("rule_id") != rule_filter:
            continue
        rows.append({"rule_id": rule.get("rule_id"), "before_status": rule.get("status", "unknown"), "after_status": rule.get("status", "unknown"), "evidence": rule.get("evidence", []), "skip_rationale": "No metadata-changing confirmed work detected; status preserved."})
    payload = {"schema": 1, "issue": issue, "results": rows, "changed": False}
    write_json(reports(root) / "rule-recheck.json", payload)
    wid = state(root) / "work-items" / str(issue)
    write_json(wid / "rule-recheck.json", payload)
    md = "# Rule Recheck\n\n## Summary\n\n" + "\n".join(f"- `{r['rule_id']}`: {r['before_status']} -> {r['after_status']}" for r in rows)
    write_text(reports(root) / "rule-recheck.md", md)
    write_text(wid / "rule-recheck.md", md)
    return 0


def autonomy_status(root: Path) -> int:
    plan = load_json(state(root) / "rule-to-recipe-plan.json", {"plans": []}).get("plans", [])
    execution = load_json(reports(root) / "worker-recipe-execution.json", {})
    data = {
        "schema": 1,
        "worker_capabilities": len(load_capability_statuses(root)),
        "recipe_count": len(recipes(root)),
        "stack_profile": load_json(state(root) / "stack-profile.json", {}).get("primary_profile", {}),
        "safe_implementable_issues": sum(1 for p in plan if p.get("status") == "recipe_available"),
        "scaffoldable_issues": sum(1 for p in plan if p.get("best_recipe")),
        "planning_only_issues": sum(1 for p in plan if p.get("status") == "planning_only"),
        "high_risk_guidance_issues": sum(1 for p in plan if p.get("human_guidance_required")),
        "recent_recipe_executions": [execution] if execution else [],
    }
    write_json(reports(root) / "autonomy-v2-status.json", data)
    write_text(reports(root) / "autonomy-v2-status.md", "\n".join([
        "# Autospec Autonomy v2 Status",
        "",
        "## Summary",
        "",
        f"- Safe implementable issues: {data['safe_implementable_issues']}",
        "",
        "## Worker capabilities",
        "",
        str(data["worker_capabilities"]),
        "",
        "## Recipe registry",
        "",
        str(data["recipe_count"]),
        "",
        "## Stack profile",
        "",
        f"`{data['stack_profile'].get('id','unknown')}`",
        "",
        "## Rule-to-recipe coverage",
        "",
        f"- Plans: {len(plan)}",
        "",
        "## Safe implementable issues",
        "",
        str(data["safe_implementable_issues"]),
        "",
        "## Scaffoldable issues",
        "",
        str(data["scaffoldable_issues"]),
        "",
        "## Planning-only issues",
        "",
        str(data["planning_only_issues"]),
        "",
        "## High-risk/guidance issues",
        "",
        str(data["high_risk_guidance_issues"]),
        "",
        "## Recent recipe executions",
        "",
        str(len(data["recent_recipe_executions"])),
        "",
        "## Verifier recipe findings",
        "",
        "- See verifier report.",
        "",
        "## Next recommended commands",
        "",
        "- `bash scripts/autospec-rule-to-recipe-plan.sh --dry-run`",
    ]))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--command", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--confirm", action="store_true")
    parser.add_argument("--rule", default="")
    parser.add_argument("--issue", default="1")
    parser.add_argument("--recipe", default="")
    parser.add_argument("--template", default="")
    parser.add_argument("--output", default="")
    parser.add_argument("--allow-overwrite", action="store_true")
    parser.add_argument("--auto-recipe", action="store_true")
    parser.add_argument("--capability", default="")
    parser.add_argument("--var", action="append", default=[])
    args = parser.parse_args()
    root = Path(args.repo_root).resolve()
    handlers = {
        "recipe-index": lambda: recipe_index(root),
        "detect-stack": lambda: detect_stack(root),
        "rule-to-recipe": lambda: rule_to_recipe(root, args.rule),
        "decompose": lambda: decompose(root, args.recipe),
        "patch-plan": lambda: patch_plan(root, args.recipe, args.issue),
        "apply-template": lambda: apply_template(root, args.template, args.output, args.confirm, dict(v.split("=", 1) for v in args.var), args.allow_overwrite),
        "worker-recipe": lambda: worker_recipe(root, args.recipe, args.issue, args.confirm, args.auto_recipe),
        "evidence-tests": lambda: evidence_tests(root, args.capability, args.confirm),
        "rule-recheck": lambda: rule_recheck(root, args.rule, args.issue),
        "status": lambda: autonomy_status(root),
    }
    if args.command not in handlers:
        raise SystemExit(f"unknown command: {args.command}")
    return handlers[args.command]()


if __name__ == "__main__":
    raise SystemExit(main())
