#!/usr/bin/env python3
"""Autonomy v2 local recipe helpers.

The implementation is deliberately bounded: recipes can generate plans,
templates, metadata, and dry-run execution reports. Confirmed writes only touch
operator-approved generated docs/tests/scaffold paths.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

from autospec_autonomy_capabilities import load_capability_statuses
from autospec_autonomy_recipes import recipe_index
from autospec_autonomy_rulemap import find_recipe, recipes, rule_results, rule_to_recipe
from autospec_autonomy_stack import detect_stack, stack_confidence


GENERATED_HEADER = "Generated by Autospec from template"
SAFE_OUTPUT_PREFIXES = ("docs/", "tests/", ".autospec/", "src/")
FORBIDDEN_PATHS = [".github/workflows/**", ".env", ".env.*", "**/migrations/**", "package.json", "pyproject.toml"]
CAPABILITY_IDS = [
    "docs", "specs", "metadata", "tests", "cli", "scripts", "ui_scaffold", "api_scaffold",
    "settings_scaffold", "ai_scaffold", "nlai_scaffold", "diagnostics_scaffold",
    "reporting_scaffold", "playwright_scaffold", "security_privacy_docs",
    "dependency_planning", "modernization_planning",
]


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def load_json(path: Path, default):
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else default
    except Exception:
        return default


def reports(root: Path) -> Path:
    path = root / ".autospec/reports"
    path.mkdir(parents=True, exist_ok=True)
    return path


def state(root: Path) -> Path:
    path = root / ".autospec/state"
    path.mkdir(parents=True, exist_ok=True)
    return path


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "item"


def decompose(root: Path, recipe_id: str) -> int:
    recipe = find_recipe(root, recipe_id) or {"id": recipe_id or "unknown", "title": "Unknown", "category": "unknown"}
    pieces = [
        "add AI capability metadata", "add provider settings spec", "add AI settings page scaffold", "add RAG indexing spec",
        "add token usage schema spec", "add usage dashboard spec", "add Playwright test plan", "add docs/tutorial update",
    ] if "ai" in recipe.get("category", "") or "ai" in recipe.get("id", "") else [
        f"apply {recipe['id']} scaffold", "add validation evidence", "update metadata", "update docs",
    ]
    backlog = root / ".autospec/backlog/decomposed"
    backlog.mkdir(parents=True, exist_ok=True)
    issues = []
    for idx, title in enumerate(pieces, start=1):
        path = backlog / f"{idx:03d}-{slug(title)}.md"
        body = "\n".join([f"# {title}", "", f"Parent recipe: `{recipe['id']}`", "", "## Scope", "", title, "", "## Non-goals", "", "- No broad rewrites.", "- No migrations/auth/security changes.", "", "## Acceptance criteria", "", f"- [ ] `{title}` is complete with evidence.", "", "## Validation", "", "- Run focused validation or document skip rationale.", "", "## Worker eligibility", "", "recipe-backed dry-run first.", "", "## Blocker/risk notes", "", "Use stuck/guidance if unsafe."])
        write_text(path, body)
        issues.append({"title": title, "path": str(path.relative_to(root)), "worker_eligible": True})
    payload = {"schema": 1, "recipe_id": recipe["id"], "issues": issues}
    write_json(reports(root) / "decomposition-plan.json", payload)
    write_text(reports(root) / "decomposition-plan.md", "# Decomposition Plan\n\n## Summary\n\n" + "\n".join(f"- {i['title']}" for i in issues))
    return 0


def patch_plan(root: Path, recipe_id: str, issue: str = "1") -> int:
    recipe = find_recipe(root, recipe_id) or recipes(root)[0]
    wid = state(root) / "work-items" / str(issue or recipe_id)
    expected = recipe["implementation"]["expected_files"]
    payload = {
        "schema": 1,
        "issue": issue,
        "recipe_id": recipe["id"],
        "files_to_inspect": expected.get("inspect", []),
        "files_to_create": expected.get("create", []),
        "files_to_update": expected.get("update", []),
        "files_forbidden": recipe["implementation"].get("forbidden_paths", FORBIDDEN_PATHS),
        "expected_line_budget": recipe["implementation"].get("max_lines_changed", 250),
        "test_files_expected": recipe["test_plan"].get("generated_tests", []),
        "docs_files_expected": [f for f in expected.get("create", []) if f.startswith("docs/")],
        "metadata_files_expected": recipe["metadata"].get("update", []),
        "rollback_plan": "Remove generated files and rerun rule recheck.",
        "validation_plan": recipe["validation"].get("commands", []),
        "risk_classification": recipe["risk"],
        "human_guidance_triggers": recipe.get("stuck_if", []),
    }
    write_json(reports(root) / "patch-plan.json", payload)
    write_json(wid / "patch-plan.json", payload)
    md = "\n".join(["# Patch Plan", "", "## Summary", "", f"- Recipe: `{recipe['id']}`", "", "## Rollback plan", "", payload["rollback_plan"], "", "## Validation plan", "", "\n".join(f"- `{c}`" for c in payload["validation_plan"])])
    write_text(reports(root) / "patch-plan.md", md)
    write_text(wid / "patch-plan.md", md)
    return 0


def render_template(text: str, vars_: dict[str, str]) -> tuple[str, list[str]]:
    unresolved = []
    def repl(match):
        key = match.group(1).strip()
        if key not in vars_:
            unresolved.append(key)
            return match.group(0)
        return vars_[key]
    return re.sub(r"\{\{([^}]+)\}\}", repl, text), unresolved


def _blocked_apply(root: Path, result: dict, summary: str | None) -> int:
    """Record a refused template application and return its exit code.

    summary is None for the unsafe-overwrite refusal, which historically wrote only
    the JSON result and no markdown; preserved so artifacts stay identical.
    """
    write_json(reports(root) / "template-apply-result.json", result)
    if summary is not None:
        write_text(reports(root) / "template-apply-result.md",
                   f"# Template Apply Result\n\n## Summary\n\n{summary}")
    return 1


def _apply_refusal(root: Path, output_path: Path, rel_out: str, unresolved: list[str],
                   allow_overwrite: bool) -> tuple[dict, str] | None:
    """The refusal payload and summary for an unsafe apply, or None when it may run."""
    if not rel_out or not rel_out.startswith(SAFE_OUTPUT_PREFIXES):
        return ({"schema": 1, "status": "blocked", "reason": "output path is outside allowed paths",
                 "side_effects": {"wrote_file": False}},
                "Blocked: output path is outside allowed paths.")
    if unresolved:
        return ({"schema": 1, "status": "blocked", "unresolved_variables": unresolved,
                 "side_effects": {"wrote_file": False}},
                "Blocked: unresolved variables.")
    if output_path.exists() and not allow_overwrite \
            and GENERATED_HEADER not in output_path.read_text(encoding="utf-8", errors="ignore"):
        return ({"schema": 1, "status": "blocked", "reason": "unsafe overwrite blocked",
                 "side_effects": {"wrote_file": False}},
                None)
    return None


def apply_template(root: Path, template: str, output: str, confirm: bool, vars_: dict[str, str], allow_overwrite: bool = False) -> int:
    template_path = (root / template).resolve()
    output_path = (root / output).resolve()
    if not str(template_path).startswith(str(root)):
        raise SystemExit("template must be inside repo")
    rel_out = output_path.relative_to(root).as_posix() if str(output_path).startswith(str(root)) else ""
    unresolved: list[str] = []
    rendered = ""
    if rel_out and rel_out.startswith(SAFE_OUTPUT_PREFIXES):
        rendered, unresolved = render_template(template_path.read_text(encoding="utf-8"), vars_)
    refusal = _apply_refusal(root, output_path, rel_out, unresolved, allow_overwrite)
    if refusal:
        return _blocked_apply(root, refusal[0], refusal[1])
    plan = {"schema": 1, "template": template, "output": rel_out, "variables": sorted(vars_), "mode": "confirm" if confirm else "dry_run", "side_effects": {"wrote_file": False}}
    write_json(reports(root) / "template-apply-plan.json", plan)
    write_text(reports(root) / "template-apply-plan.md", f"# Template Apply Plan\n\n## Summary\n\n- Template: `{template}`\n- Output: `{rel_out}`")
    if confirm:
        prefix = f"<!-- {GENERATED_HEADER} {template}; edit source template or confirm manual ownership. -->\n"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(prefix + rendered, encoding="utf-8")
    result = {"schema": 1, "status": "applied" if confirm else "planned", "output": rel_out, "side_effects": {"wrote_file": confirm}}
    write_json(reports(root) / "template-apply-result.json", result)
    write_text(reports(root) / "template-apply-result.md", f"# Template Apply Result\n\n## Summary\n\nStatus: `{result['status']}`")
    return 0


def worker_recipe(root: Path, recipe_id: str, issue: str, confirm: bool, auto: bool = False) -> int:
    if auto:
        rule_to_recipe(root)
        plans = load_json(state(root) / "rule-to-recipe-plan.json", {"plans": []}).get("plans", [])
        recipe_id = next((p["best_recipe"] for p in plans if p.get("status") == "recipe_available"), recipe_id)
    recipe = find_recipe(root, recipe_id)
    reason = _worker_refusal_reason(root, recipe)
    if reason:
        return write_worker_refusal(root, issue, recipe_id, reason)
    patch_plan(root, recipe["id"], issue)
    wid = state(root) / "work-items" / str(issue)
    created = recipe["implementation"]["expected_files"].get("create", [])
    execution = {"schema": 1, "issue": issue, "recipe_id": recipe["id"], "capability": recipe["capability"], "mode": "confirm" if confirm else "dry_run", "status": "executed", "generated_files": created, "rule_progress": "planned", "validation": recipe["validation"]["commands"], "side_effects": {"wrote_files": False}}
    write_json(wid / "recipe-execution.json", execution)
    write_json(reports(root) / "worker-recipe-execution.json", execution)
    md = _worker_execution_markdown(recipe, issue, created)
    write_text(wid / "recipe-execution.md", md)
    write_text(reports(root) / "worker-recipe-execution.md", md)
    write_text(reports(root) / "worker-pr-body.md", md)
    return 0


STACK_SPECIFIC_CAPABILITIES = {"ui_scaffold", "settings_scaffold", "api_scaffold"}
MIN_SCAFFOLD_STACK_CONFIDENCE = 0.8


def _worker_refusal_reason(root: Path, recipe: dict | None) -> str:
    """Why this recipe must not run, or an empty string when it may."""
    if not recipe:
        return "recipe missing"
    if load_capability_statuses(root).get(recipe["capability"]) not in {"enabled", "experimental"}:
        return "worker capability disabled"
    if recipe["capability"] in STACK_SPECIFIC_CAPABILITIES and stack_confidence(root) < MIN_SCAFFOLD_STACK_CONFIDENCE:
        return "stack confidence too low for stack-specific scaffold"
    return ""


def _worker_execution_markdown(recipe: dict, issue: str, created: list[str]) -> str:
    return "\n".join([
        "# Worker Recipe Execution",
        "",
        "## Summary",
        "",
        f"- Recipe: `{recipe['id']}`",
        f"- Capability: `{recipe['capability']}`",
        "- Implementation mode: scaffolded/planned unless rule recheck and tests prove runtime behavior.",
        "",
        "## Source issue",
        "",
        f"`{issue}`",
        "",
        "## Constitution/baseline references",
        "",
        "- Constitution rule context: recipe-backed bounded implementation.",
        f"- Baseline capability: `{recipe['capability']}`",
        "",
        "## Recipe Execution",
        "",
        f"Recipe: `{recipe['id']}`",
        "Capability: " + recipe["capability"],
        "Patch plan: `.autospec/reports/patch-plan.md`",
        "Generated files: " + ", ".join(created),
        "Rule progress: planned",
        "Validation: " + ", ".join(recipe["validation"]["commands"]),
        "",
        "## Acceptance criteria",
        "",
        *[f"- [ ] {item}" for item in recipe.get("acceptance_criteria", [])],
        "",
        "## Safety notes",
        "",
        "- No GitHub writes, merges, approvals, migrations, auth/security changes, or dependency upgrades were performed.",
    ])


def write_worker_refusal(root: Path, issue: str, recipe_id: str, reason: str) -> int:
    wid = state(root) / "work-items" / str(issue)
    execution = {"schema": 1, "issue": issue, "recipe_id": recipe_id, "status": "refused", "reason": reason, "side_effects": {"wrote_files": False}}
    write_json(wid / "recipe-execution.json", execution)
    write_json(reports(root) / "worker-recipe-execution.json", execution)
    write_text(reports(root) / "worker-recipe-execution.md", f"# Worker Recipe Execution\n\n## Summary\n\nRefused: {reason}\n")
    return 1


def evidence_tests(root: Path, capability: str, confirm: bool) -> int:
    output = "tests/e2e/autospec-viewport.spec.ts" if "viewport" in capability else "tests/e2e/autospec-evidence.spec.ts"
    plan = {"schema": 1, "capability": capability, "output": output, "mode": "confirm" if confirm else "dry_run", "playwright_detected": (root / "package.json").exists() and "@playwright/test" in (root / "package.json").read_text(encoding="utf-8", errors="ignore")}
    write_json(reports(root) / "evidence-test-generation-plan.json", plan)
    write_text(reports(root) / "evidence-test-generation-plan.md", "# Evidence Test Generation Plan\n\n## Summary\n\nPlaywright evidence test scaffold planned.\n")
    if confirm:
        path = root / output
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("// Generated by Autospec evidence test recipe\n", encoding="utf-8")
    write_json(reports(root) / "evidence-test-generation-result.json", {**plan, "side_effects": {"wrote_file": confirm}})
    write_text(reports(root) / "evidence-test-generation-result.md", "# Evidence Test Generation Result\n\n## Summary\n\nDone.\n")
    return 0


def rule_recheck(root: Path, rule_filter: str = "", issue: str = "1") -> int:
    rows = []
    for rule in rule_results(root):
        if rule_filter and rule.get("rule_id") != rule_filter:
            continue
        rows.append({"rule_id": rule.get("rule_id"), "before_status": rule.get("status", "unknown"), "after_status": rule.get("status", "unknown"), "evidence": rule.get("evidence", []), "skip_rationale": "No metadata-changing confirmed work detected; status preserved."})
    payload = {"schema": 1, "issue": issue, "results": rows, "changed": False}
    write_json(reports(root) / "rule-recheck.json", payload)
    wid = state(root) / "work-items" / str(issue)
    write_json(wid / "rule-recheck.json", payload)
    md = "# Rule Recheck\n\n## Summary\n\n" + "\n".join(f"- `{r['rule_id']}`: {r['before_status']} -> {r['after_status']}" for r in rows)
    write_text(reports(root) / "rule-recheck.md", md)
    write_text(wid / "rule-recheck.md", md)
    return 0


def _status_data(root: Path, plan: list[dict]) -> dict:
    execution = load_json(reports(root) / "worker-recipe-execution.json", {})
    return {
        "schema": 1,
        "worker_capabilities": len(load_capability_statuses(root)),
        "recipe_count": len(recipes(root)),
        "stack_profile": load_json(state(root) / "stack-profile.json", {}).get("primary_profile", {}),
        "safe_implementable_issues": sum(1 for p in plan if p.get("status") == "recipe_available"),
        "scaffoldable_issues": sum(1 for p in plan if p.get("best_recipe")),
        "planning_only_issues": sum(1 for p in plan if p.get("status") == "planning_only"),
        "high_risk_guidance_issues": sum(1 for p in plan if p.get("human_guidance_required")),
        "recent_recipe_executions": [execution] if execution else [],
    }


def _status_sections(data: dict, plan: list[dict]) -> list[tuple[str, str]]:
    return [
        ("Worker capabilities", str(data["worker_capabilities"])),
        ("Recipe registry", str(data["recipe_count"])),
        ("Stack profile", f"`{data['stack_profile'].get('id','unknown')}`"),
        ("Rule-to-recipe coverage", f"- Plans: {len(plan)}"),
        ("Safe implementable issues", str(data["safe_implementable_issues"])),
        ("Scaffoldable issues", str(data["scaffoldable_issues"])),
        ("Planning-only issues", str(data["planning_only_issues"])),
        ("High-risk/guidance issues", str(data["high_risk_guidance_issues"])),
        ("Recent recipe executions", str(len(data["recent_recipe_executions"]))),
        ("Verifier recipe findings", "- See verifier report."),
        ("Next recommended commands", "- `bash scripts/autospec-rule-to-recipe-plan.sh --dry-run`"),
    ]


def _status_markdown(data: dict, plan: list[dict]) -> str:
    lines = [
        "# Autospec Autonomy v2 Status",
        "",
        "## Summary",
        "",
        f"- Safe implementable issues: {data['safe_implementable_issues']}",
    ]
    for heading, value in _status_sections(data, plan):
        lines += ["", f"## {heading}", "", value]
    return "\n".join(lines)


def autonomy_status(root: Path) -> int:
    plan = load_json(state(root) / "rule-to-recipe-plan.json", {"plans": []}).get("plans", [])
    data = _status_data(root, plan)
    write_json(reports(root) / "autonomy-v2-status.json", data)
    write_text(reports(root) / "autonomy-v2-status.md", _status_markdown(data, plan))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--command", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--confirm", action="store_true")
    parser.add_argument("--rule", default="")
    parser.add_argument("--issue", default="1")
    parser.add_argument("--recipe", default="")
    parser.add_argument("--template", default="")
    parser.add_argument("--output", default="")
    parser.add_argument("--allow-overwrite", action="store_true")
    parser.add_argument("--auto-recipe", action="store_true")
    parser.add_argument("--capability", default="")
    parser.add_argument("--var", action="append", default=[])
    args = parser.parse_args()
    root = Path(args.repo_root).resolve()
    handlers = {
        "recipe-index": lambda: recipe_index(root),
        "detect-stack": lambda: detect_stack(root),
        "rule-to-recipe": lambda: rule_to_recipe(root, args.rule),
        "decompose": lambda: decompose(root, args.recipe),
        "patch-plan": lambda: patch_plan(root, args.recipe, args.issue),
        "apply-template": lambda: apply_template(root, args.template, args.output, args.confirm, dict(v.split("=", 1) for v in args.var), args.allow_overwrite),
        "worker-recipe": lambda: worker_recipe(root, args.recipe, args.issue, args.confirm, args.auto_recipe),
        "evidence-tests": lambda: evidence_tests(root, args.capability, args.confirm),
        "rule-recheck": lambda: rule_recheck(root, args.rule, args.issue),
        "status": lambda: autonomy_status(root),
    }
    if args.command not in handlers:
        raise SystemExit(f"unknown command: {args.command}")
    return handlers[args.command]()


if __name__ == "__main__":
    raise SystemExit(main())
