#!/usr/bin/env bash
# scripts/gen-ac-tests.sh — Generate bats AC stubs from issue body, or verify a dir.
#
# Usage:
#   gen-ac-tests.sh --issue-body <file> --out <output.bats>
#     Parse ## Acceptance criteria checkboxes and emit bats stubs.
#     Criteria matching known runnable patterns get real assertions;
#     others get: skip "auto-stub"
#
#   gen-ac-tests.sh --verify <dir>
#     Scan every *.bats in <dir>. Exit 1 with structured output if any
#     contains 'skip "auto-stub"'. Exit 0 if clean.
#
# Exit codes:
#   0  Success (or clean verify)
#   1  --verify: stubs found; or argument error
#
# Compatible with bash 3.2+

set -eu

HELP_TEXT='Usage:
  gen-ac-tests.sh --issue-body <file> --out <output.bats>
  gen-ac-tests.sh --verify <dir>
  gen-ac-tests.sh --help

Generate bats AC stubs from issue body checkboxes, or verify a dir has no remaining auto-stubs.

Exit code = 0 (success/clean) or 1 (error/stubs found).'

MODE=""
ISSUE_BODY_FILE=""
OUT_FILE=""
VERIFY_DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --help|-h)
      printf '%s\n' "$HELP_TEXT"
      exit 0
      ;;
    --issue-body)
      if [ $# -lt 2 ]; then printf 'gen-ac-tests.sh: --issue-body requires an argument\n' >&2; exit 1; fi
      ISSUE_BODY_FILE="$2"
      MODE="emit"
      shift 2
      ;;
    --out)
      if [ $# -lt 2 ]; then printf 'gen-ac-tests.sh: --out requires an argument\n' >&2; exit 1; fi
      OUT_FILE="$2"
      shift 2
      ;;
    --verify)
      if [ $# -lt 2 ]; then printf 'gen-ac-tests.sh: --verify requires an argument\n' >&2; exit 1; fi
      VERIFY_DIR="$2"
      MODE="verify"
      shift 2
      ;;
    -*)
      printf 'gen-ac-tests.sh: unknown option: %s\n' "$1" >&2
      exit 1
      ;;
    *)
      printf 'gen-ac-tests.sh: unexpected argument: %s\n' "$1" >&2
      exit 1
      ;;
  esac
done

if [ -z "$MODE" ]; then
  printf '%s\n' "$HELP_TEXT" >&2
  exit 1
fi

# ── verify mode ──────────────────────────────────────────────────────────────

if [ "$MODE" = "verify" ]; then
  if [ ! -d "$VERIFY_DIR" ]; then
    printf 'gen-ac-tests.sh: verify dir not found: %s\n' "$VERIFY_DIR" >&2
    exit 1
  fi

  found_stubs=0
  for bats_file in "$VERIFY_DIR"/*.bats; do
    # Handle empty glob on bash 3.2 (glob returns literal pattern if no match)
    [ -f "$bats_file" ] || continue
    if grep -q 'skip "auto-stub"' "$bats_file"; then
      found_stubs=$((found_stubs + 1))
      stubs=$(grep -n 'skip "auto-stub"' "$bats_file" | head -5)
      printf 'STUB_REMAINING:%s\n%s\n' "$bats_file" "$stubs"
    fi
  done

  if [ "$found_stubs" -gt 0 ]; then
    printf '\n%d file(s) contain auto-stub entries that must be replaced with real assertions before push.\n' "$found_stubs"
    exit 1
  fi

  exit 0
fi

# ── emit mode ────────────────────────────────────────────────────────────────

if [ -z "$ISSUE_BODY_FILE" ]; then
  printf 'gen-ac-tests.sh: --issue-body is required for emit mode\n' >&2; exit 1
fi
if [ ! -f "$ISSUE_BODY_FILE" ]; then
  printf 'gen-ac-tests.sh: issue body file not found: %s\n' "$ISSUE_BODY_FILE" >&2; exit 1
fi
if [ -z "$OUT_FILE" ]; then
  printf 'gen-ac-tests.sh: --out is required for emit mode\n' >&2; exit 1
fi

# Count checkboxes first
checkbox_count=$(awk '
  /^## Acceptance criteria/ { in_ac=1; next }
  /^## / && in_ac { exit }
  in_ac && /^- \[ \]/ { count++ }
  END { print count+0 }
' "$ISSUE_BODY_FILE")

if [ "$checkbox_count" -eq 0 ]; then
  printf 'gen-ac-tests.sh: no checkboxes found in ## Acceptance criteria\n' >&2
  exit 1
fi

# Determine real assertion for known runnable patterns
make_assertion() {
  local criterion="$1"
  local lower
  lower=$(printf '%s' "$criterion" | tr '[:upper:]' '[:lower:]')

  if printf '%s' "$lower" | grep -qE 'bats test'; then
    printf '  run bats tests/\n  [ "$status" -eq 0 ]'
  elif printf '%s' "$lower" | grep -q 'npm test'; then
    printf '  run npm test\n  [ "$status" -eq 0 ]'
  elif printf '%s' "$lower" | grep -q 'validate\.sh'; then
    printf '  run autospec validate\n  [ "$status" -eq 0 ]'
  elif printf '%s' "$lower" | grep -q 'pytest'; then
    printf '  run pytest\n  [ "$status" -eq 0 ]'
  else
    printf '  skip "auto-stub"'
  fi
}

# Emit the bats file using awk to extract checkboxes, then process each
{
  printf '#!/usr/bin/env bats\n'
  printf '# Auto-generated AC stubs — replace skip "auto-stub" with real assertions before push.\n'
  printf '# Generated by: scripts/gen-ac-tests.sh\n\n'
} > "$OUT_FILE"

idx=1
while IFS= read -r criterion; do
  assertion=$(make_assertion "$criterion")
  {
    printf '@test "AC#%d: %s" {\n' "$idx" "$criterion"
    printf '%s\n' "$assertion"
    printf '}\n\n'
  } >> "$OUT_FILE"
  idx=$((idx + 1))
done < <(awk '
  /^## Acceptance criteria/ { in_ac=1; next }
  /^## / && in_ac { exit }
  in_ac && /^- \[ \]/ { sub(/^- \[ \] /, ""); print }
' "$ISSUE_BODY_FILE")

printf 'gen-ac-tests.sh: wrote %d AC stubs to %s\n' "$checkbox_count" "$OUT_FILE"
exit 0
