#!/usr/bin/env bash
#
# Consumer enumeration (issue #3893): every generated artefact this script
# owns lists its consumers below, so a change to this generator surfaces the
# consumer list. scripts/lint-generated-artifacts.sh ratchets the enumeration
# and verifies the recorded digests in config/generated-artifact-integrity.sha256.
#
# Consumers(templates/generated/harness-runtime-aliases.sh): install.sh tests/harness-runtime-alias-generation.bats tests/agent-env-install.bats config/generated-artifact-integrity.sha256
# Consumers(templates/generated/harness-runtime-aliases.fish): install.sh tests/harness-runtime-alias-generation.bats config/generated-artifact-integrity.sha256
# Consumers(docs/generated/harness-runtime-aliases.md): tests/harness-runtime-alias-generation.bats config/generated-artifact-integrity.sha256
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="$ROOT/config/harness-runtime-aliases.tsv"
MODE=write
FORMAT=""
PIN_TARGET="$ROOT/config/generated-artifact-integrity.sha256"
ARTIFACTS=(
    "templates/generated/harness-runtime-aliases.sh"
    "templates/generated/harness-runtime-aliases.fish"
    "docs/generated/harness-runtime-aliases.md"
)

usage() {
    printf 'Usage: %s [--check] [--source PATH] [--stdout sh|fish|docs]\n' "$0"
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --check) MODE=check; shift ;;
            --source) SOURCE="${2:-}"; shift 2 ;;
            --stdout) MODE=stdout; FORMAT="${2:-}"; shift 2 ;;
            -h|--help) usage; exit 0 ;;
            *) printf 'unknown argument: %s\n' "$1" >&2; exit 2 ;;
        esac
    done
}

validate_source() {
    awk -F '\t' '
        NF != 4 { printf "line %d: expected 4 tab-separated fields\n", NR > "/dev/stderr"; bad=1 }
        $1 !~ /^[a-z][a-z0-9-]*$/ { printf "line %d: invalid harness id: %s\n", NR, $1 > "/dev/stderr"; bad=1 }
        $2 !~ /^[A-Za-z0-9._+-]+$/ { printf "line %d: invalid executable: %s\n", NR, $2 > "/dev/stderr"; bad=1 }
        seen[$1]++ { printf "duplicate harness id: %s\n", $1 > "/dev/stderr"; bad=1 }
        END { if (NR == 0) { print "harness table is empty" > "/dev/stderr"; bad=1 }; exit bad ? 2 : 0 }
    ' "$SOURCE"
}

render_sh() {
    awk -F '\t' '
        BEGIN { print "# shellcheck shell=bash"; print "# Generated by scripts/gen-harness-runtime-aliases.sh; do not edit."; print "# BEGIN AUTOSPEC RUNTIME ALIASES" }
        { suffix=$3 == "" ? "" : " " $3; printf "alias %s=\047autospec-env session -- %s%s\047\n", $1, $2, suffix }
        END { print "# END AUTOSPEC RUNTIME ALIASES"; print "# BEGIN AUTOSPEC ROLLOVER WRAPPERS" }
    ' "$SOURCE"
    awk -F '\t' '{ suffix=$3 == "" ? "" : " " $3; printf "unalias %s 2>/dev/null || true\n%s() { autospec-session %s%s \"$@\"; } # autospec-env session -- %s%s\n", $1, $1, $2, suffix, $2, suffix }' "$SOURCE"
    printf '%s\n' '# END AUTOSPEC ROLLOVER WRAPPERS'
}

render_fish() {
    awk -F '\t' '
        BEGIN { print "# Generated by scripts/gen-harness-runtime-aliases.sh; do not edit."; print "# BEGIN AUTOSPEC RUNTIME ALIASES" }
        { suffix=$3 == "" ? "" : " " $3; printf "function %s; autospec-env session -- %s%s $argv; end\n", $1, $2, suffix }
        END { print "# END AUTOSPEC RUNTIME ALIASES"; print "# BEGIN AUTOSPEC ROLLOVER WRAPPERS" }
    ' "$SOURCE"
    awk -F '\t' '{ suffix=$3 == "" ? "" : " " $3; printf "function %s; autospec-session %s%s $argv; end # autospec-env session -- %s%s\n", $1, $2, suffix, $2, suffix }' "$SOURCE"
    printf '%s\n' '# END AUTOSPEC ROLLOVER WRAPPERS'
}

render_docs() {
    printf '%s\n\n' '# Generated harness runtime aliases' 'Generated from `config/harness-runtime-aliases.tsv`. Do not edit this file directly.'
    printf '%s\n' '| ID | Executable | Runtime command | Display name |' '| --- | --- | --- | --- |'
    awk -F '\t' '{ suffix=$3 == "" ? "" : " " $3; printf "| `%s` | `%s` | `autospec-env session -- %s%s` | %s |\n", $1, $2, $2, suffix, $4 }' "$SOURCE"
}

sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        openssl dgst -sha256 "$1" | awk '{print $NF}'
    fi
}

render_pins() {
    local p
    for p in "${ARTIFACTS[@]}"; do
        printf '%s  %s\n' "$(sha256_of "$ROOT/$p")" "$p"
    done
}

render() {
    case "$1" in
        sh) render_sh ;;
        fish) render_fish ;;
        docs) render_docs ;;
        pins) render_pins ;;
        *) printf 'unsupported output format: %s\n' "$1" >&2; exit 2 ;;
    esac
}

write_or_check() {
    local format="$1" target="$2" temporary
    temporary="$(mktemp)"
    render "$format" > "$temporary"
    if [[ "$MODE" == check ]]; then
        cmp -s "$temporary" "$target" || { printf 'generated file is stale: %s\n' "$target" >&2; rm -f "$temporary"; return 1; }
        rm -f "$temporary"
    else
        mkdir -p "$(dirname "$target")"
        mv "$temporary" "$target"
    fi
}

main() {
    parse_args "$@"
    [[ -f "$SOURCE" ]] || { printf 'harness table not found: %s\n' "$SOURCE" >&2; exit 2; }
    validate_source
    if [[ "$MODE" == stdout ]]; then render "$FORMAT"; return; fi
    write_or_check sh "$ROOT/templates/generated/harness-runtime-aliases.sh"
    write_or_check fish "$ROOT/templates/generated/harness-runtime-aliases.fish"
    write_or_check docs "$ROOT/docs/generated/harness-runtime-aliases.md"
    # The pin manifest is rendered last so it hashes the artefacts just
    # written; --check mode hashes the committed artefacts instead.
    write_or_check pins "$PIN_TARGET"
}

main "$@"
