#!/usr/bin/env bats
# tests/lint/test_generated_artifact_integrity_checker.bats
#
# Exercises scripts/lint-generated-artifacts.sh (issue #3893): every committed
# generated artefact must be enumerated by its generator (`# Consumers(...)`),
# every enumerated consumer must still reference the artefact, and every
# recorded sha256/sha512 reference must still match the artefact's bytes.

bats_require_minimum_version 1.5.0

setup() {
    REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../.." && pwd)"
    CHECKER="$REPO_ROOT/scripts/lint-generated-artifacts.sh"
    FIX="$(mktemp -d)"
}

teardown() {
    rm -rf "$FIX"
}

sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        openssl dgst -sha256 "$1" | awk '{print $NF}'
    fi
}

sha512_of() {
    if command -v sha512sum >/dev/null 2>&1; then
        sha512sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 512 "$1" | awk '{print $1}'
    else
        openssl dgst -sha512 "$1" | awk '{print $NF}'
    fi
}

build_fixture() {
    mkdir -p "$FIX/scripts" "$FIX/templates/generated" "$FIX/docs/generated" "$FIX/docs" "$FIX/config"
    # Generator with a Consumers enumeration block for both artefacts.
    printf '%s\n' \
        '#!/usr/bin/env bash' \
        '# Consumers(templates/generated/fixture-aliases.sh): install-fixture.sh config/fixture-integrity.sha256' \
        '# Consumers(docs/generated/fixture-aliases.md): docs/consumer-notes.md config/fixture-integrity.sha256' \
        'set -euo pipefail' \
        'ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"' \
        'mkdir -p "$ROOT/templates/generated" "$ROOT/docs/generated"' \
        'printf "%s\n" "# Generated by scripts/gen-fixture-artefacts.sh; do not edit." "alias demo=demo-cmd" > "$ROOT/templates/generated/fixture-aliases.sh"' \
        'printf "%s\n" "# Fixture aliases" "| demo |" > "$ROOT/docs/generated/fixture-aliases.md"' \
        > "$FIX/scripts/gen-fixture-artefacts.sh"
    bash "$FIX/scripts/gen-fixture-artefacts.sh"
    # Root-level consumer: parameterized reference (directory + stem only).
    printf '%s\n' '#!/usr/bin/env bash' 'source "templates/generated/fixture-aliases"' > "$FIX/install-fixture.sh"
    # Docs consumer of the .md artefact.
    printf '%s\n' 'See docs/generated/fixture-aliases.md for the table.' > "$FIX/docs/consumer-notes.md"
    # Pin manifest in sha256sum form (the second, independent check).
    local h_sh h_md
    h_sh="$(sha256_of "$FIX/templates/generated/fixture-aliases.sh")"
    h_md="$(sha256_of "$FIX/docs/generated/fixture-aliases.md")"
    printf '%s\n' "${h_sh}  templates/generated/fixture-aliases.sh" "${h_md}  docs/generated/fixture-aliases.md" \
        > "$FIX/config/fixture-integrity.sha256"
}

# Flip the first hex character of the manifest's first line hash.
flip_first_pin_hash() {
    awk 'NR==1 { c=substr($1,1,1); n=(c=="0")?"1":"0"; print n substr($1,2) "  " $2; next } { print }' \
        "$FIX/config/fixture-integrity.sha256" > "$FIX/config/fixture-integrity.tmp"
    mv "$FIX/config/fixture-integrity.tmp" "$FIX/config/fixture-integrity.sha256"
}

@test "clean fixture passes with no output" {
    build_fixture
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 0 ]
    [ -z "$output" ]
}

@test "corrupted pin manifest hash fires STALE_REFERENCE (AC3 negative case)" {
    build_fixture
    flip_first_pin_hash
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 1 ]
    [[ "$output" == *"STALE_REFERENCE"* ]]
    [[ "$output" == *"config/fixture-integrity.sha256"* ]]
    [[ "$output" == *"templates/generated/fixture-aliases.sh"* ]]
    [[ "$output" == *"scripts/gen-fixture-artefacts.sh"* ]]
}

@test "artefact without a Consumers block fires UNLISTED_ARTIFACT" {
    build_fixture
    sed -i.bak '/Consumers(templates\/generated\/fixture-aliases.sh)/d' "$FIX/scripts/gen-fixture-artefacts.sh"
    rm -f "$FIX/scripts/gen-fixture-artefacts.sh.bak"
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 1 ]
    [[ "$output" == *"UNLISTED_ARTIFACT:templates/generated/fixture-aliases.sh"* ]]
}

@test "deleted enumerated consumer fires STALE_CONSUMER" {
    build_fixture
    rm "$FIX/install-fixture.sh"
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 1 ]
    [[ "$output" == *"STALE_CONSUMER:install-fixture.sh"* ]]
}

@test "consumer that no longer references the artefact fires STALE_CONSUMER" {
    build_fixture
    printf '%s\n' 'Unrelated notes.' > "$FIX/docs/consumer-notes.md"
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 1 ]
    [[ "$output" == *"STALE_CONSUMER:docs/consumer-notes.md"* ]]
}

@test "artefact with no generator fires ORPHAN_ARTIFACT for each artefact" {
    build_fixture
    rm "$FIX/scripts/gen-fixture-artefacts.sh"
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 1 ]
    [[ "$output" == *"ORPHAN_ARTIFACT:templates/generated/fixture-aliases.sh"* ]]
    [[ "$output" == *"ORPHAN_ARTIFACT:docs/generated/fixture-aliases.md"* ]]
}

@test "explicit sha512 reference is verified and fires when stale" {
    build_fixture
    local h
    h="$(sha512_of "$FIX/docs/generated/fixture-aliases.md")"
    printf '%s\n' "docs/generated/fixture-aliases.md sha512:${h}" > "$FIX/docs/notes512.txt"
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 0 ]
    [ -z "$output" ]
    # Corrupt one hex character of the sha512 token.
    local first rest
    first="${h:0:1}"
    rest="${h:1}"
    if [ "$first" = "0" ]; then first="1"; else first="0"; fi
    printf '%s\n' "docs/generated/fixture-aliases.md sha512:${first}${rest}" > "$FIX/docs/notes512.txt"
    run bash "$CHECKER" --root "$FIX"
    [ "$status" -eq 1 ]
    [[ "$output" == *"STALE_REFERENCE"* ]]
    [[ "$output" == *"sha512"* ]]
}

@test "the real repository passes its own ratchet (dogfood)" {
    run bash "$CHECKER" --root "$REPO_ROOT"
    [ "$status" -eq 0 ]
    [ -z "$output" ]
}

@test "--list prints one INFO line per artefact and exits 0" {
    build_fixture
    run bash "$CHECKER" --root "$FIX" --list
    [ "$status" -eq 0 ]
    [[ "$output" == *"INFO:templates/generated/fixture-aliases.sh: generator=scripts/gen-fixture-artefacts.sh consumers=install-fixture.sh config/fixture-integrity.sha256"* ]]
    [[ "$output" == *"INFO:docs/generated/fixture-aliases.md: generator=scripts/gen-fixture-artefacts.sh consumers=docs/consumer-notes.md config/fixture-integrity.sha256"* ]]
}
