#!/usr/bin/env python3
"""Emit router presets sized for the GPU this job actually landed on.

    gen-preset.py --vram-mib 46068 --models-dir /scratch/x > presets.ini

`opencode_hive` picks whichever GPU can start soonest, so the card is not known
until the job runs: 96 GiB Blackwell one time, 46 GiB L40S the next. A preset
written for the larger card loads the weights on the smaller one and then dies
allocating state -- `failed to allocate buffer for rs cache` -- which reads like
a corrupt model rather than a budget that was never checked.

The arithmetic, for this hybrid architecture (16 of 64 layers are full
attention; the other 48 carry a constant-size recurrent state):

    KV bytes/token = 2 x 16 layers x 4 kv_heads x 256 head_dim x bytes_per_elem

which is 32 KiB/token at fp8 and therefore **64 KiB/token at f16**. Getting that
factor of two wrong is what put a 16 GiB KV cache into a 16.4 GiB hole.
"""
from __future__ import annotations

import argparse
import sys

KV_BYTES_PER_TOKEN = {"f16": 65536, "q8_0": 34816, "q4_0": 18432}
N_CTX_TRAIN = 262144
# Weight file sizes as staged. Measured, not estimated from parameter counts.
WEIGHTS_MIB = {"Qwen3.8-27B-UD-Q8_K_XL.gguf": 30000,
               "Qwen3.8-27B-ABLITERATED-Q8_0.gguf": 27701}
MMPROJ_MIB = 885


def plan(vram_mib: int, weights_mib: int, kv: str, parallel: int,
         extra_mib: int = 0) -> int:
    """Largest context that leaves room for everything else, in tokens."""
    # Compute buffers and the recurrent-state cache both grow with the slot
    # count. 512 MiB per slot is empirical headroom, not a published figure.
    reserve = 2048 + 512 * parallel + extra_mib
    usable = vram_mib - weights_mib - reserve
    if usable <= 0:
        return 0
    tokens = int(usable * 1024 * 1024 / KV_BYTES_PER_TOKEN[kv])
    # 80% of what the arithmetic allows. The remainder absorbs the rs cache,
    # which is real and which this formula does not model.
    tokens = int(tokens * 0.80)
    tokens = min(tokens, N_CTX_TRAIN)
    return (tokens // 32768) * 32768          # snap to a tidy multiple


def tiers_for(pool: int, parallel: int, prefix: str) -> list[tuple[str, int]]:
    """Context tiers that fit the pool and do not out-promise the slot count."""
    out = []
    for ctx in (262144, 131072, 65536, 40960):
        if ctx > pool:
            continue
        if pool // ctx > parallel:
            continue
        out.append((f"{prefix}-{ctx // 1024}k", ctx))
    return out


def emit(name: str, model: str, pool: int, parallel: int, models_dir: str,
         mmproj: str | None = None) -> str:
    if pool <= 0:
        return ""
    lines = [f"[{name}]", f"model = {models_dir}/{model}"]
    if mmproj:
        lines += [f"mmproj = {models_dir}/{mmproj}", "image-min-tokens = 1024"]
    lines += [f"c = {pool}", f"parallel = {parallel}"]
    tiers = tiers_for(pool, parallel, name)
    if tiers:
        lines.append("alias = " + ",".join(t for t, _ in tiers))
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vram-mib", type=int, required=True)
    ap.add_argument("--models-dir", required=True)
    ap.add_argument("--kv", default="f16", choices=sorted(KV_BYTES_PER_TOKEN))
    args = ap.parse_args()

    v = args.vram_mib
    # More slots only pay off where there is memory to fund them.
    parallel = 8 if v >= 80000 else 4 if v >= 40000 else 2
    kv = args.kv
    # A card too small for f16 KV is far better served by quantising the cache
    # than by giving up most of its context.
    std = WEIGHTS_MIB["Qwen3.8-27B-UD-Q8_K_XL.gguf"]
    if plan(v, std, kv, parallel) < 65536 and kv == "f16":
        kv = "q8_0"
        print(f"; f16 KV leaves too little context on {v} MiB; using q8_0",
              file=sys.stderr)

    text_pool = plan(v, std, kv, parallel)
    vis_pool = plan(v, std, kv, max(2, parallel // 2), extra_mib=MMPROJ_MIB)
    unc = WEIGHTS_MIB["Qwen3.8-27B-ABLITERATED-Q8_0.gguf"]
    unc_pool = plan(v, unc, kv, parallel)
    unc_vis = plan(v, unc, kv, max(2, parallel // 2), extra_mib=MMPROJ_MIB)

    print(f"; generated by gen-preset.py for {v} MiB of VRAM")
    print(f"; kv={kv} parallel={parallel} text_pool={text_pool}")
    print("version = 1\n")
    print("[*]")
    print("n-gpu-layers = 999\nflash-attn = auto\njinja = true")
    print("no-context-shift = true\nkv-unified = true")
    if kv != "f16":
        print(f"cache-type-k = {kv}\ncache-type-v = {kv}")
    print()
    d = args.models_dir
    print(emit("qwen3.8-27b", "Qwen3.8-27B-UD-Q8_K_XL.gguf",
               text_pool, parallel, d))
    print(emit("qwen3.8-27b-vision", "Qwen3.8-27B-UD-Q8_K_XL.gguf",
               vis_pool, max(2, parallel // 2), d, "mmproj-F16.gguf"))
    print(emit("qwen3.8-27b-uncensored", "Qwen3.8-27B-ABLITERATED-Q8_0.gguf",
               unc_pool, parallel, d))
    print(emit("qwen3.8-27b-uncensored-vision",
               "Qwen3.8-27B-ABLITERATED-Q8_0.gguf", unc_vis,
               max(2, parallel // 2), d,
               "mmproj-Qwen3.8-27B-ABLITERATED-F16.gguf"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
