#!/usr/bin/env bash
# packages/cli/scripts/init.sh — bootstrap a target repo with .autospec/test.yml
# Called by: autospec init [--help]
#
# Creates:
#   .autospec/test.yml   — initial autospec-test configuration with example scopes
#
# Usage: autospec init

set -eu

usage() {
  cat <<'EOF'
autospec init — bootstrap a target repo for autospec

Creates .autospec/test.yml with an initial scope configuration in the
current working directory.

Usage:
  autospec init [--help]

Options:
  --help    Show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    *) echo "autospec init: unknown flag '$arg'" >&2; exit 1 ;;
  esac
done

TARGET_DIR="${PWD}"
AUTOSPEC_DIR="$TARGET_DIR/.autospec"

if [ -f "$AUTOSPEC_DIR/test.yml" ]; then
  echo "autospec: .autospec/test.yml already exists — skipping init."
  echo "  Edit $AUTOSPEC_DIR/test.yml to update scopes."
  exit 0
fi

mkdir -p "$AUTOSPEC_DIR"

cat > "$AUTOSPEC_DIR/test.yml" <<'YAML'
# .autospec/test.yml — autospec-test configuration
# Generated by: autospec init
#
# Define documentation scopes that map source paths to doc paths.
# autospec-test will check for documentation drift on each PR.
#
# See: https://github.com/berlinguyinca/autospec for full reference.

version: 1

scopes:
  - id: default
    source_paths:
      - "**/*.{js,ts,py,go,sh}"
    doc_paths:
      - "docs/**/*.md"
      - "README.md"
    mismatch_action: warn
YAML

echo "autospec: initialized .autospec/test.yml in $TARGET_DIR"
echo "  Edit $AUTOSPEC_DIR/test.yml to configure your documentation scopes."
