#!/usr/bin/env bash
# scripts/explore-research/style-normalization.sh — discovery researcher.
#
# Detects frontend style drift in SPA/webapp repos and emits proposals only when
# route-level Playwright coverage plus screenshot evidence exists or has been
# generated by the proof seam. Research owns discovery; proof generation is
# delegated through AUTOSPEC_EXPLORE_STYLE_PROOF_CMD or the installed
# autospec-playwright dispatcher when available.

set -u

REPO_ROOT="${AUTOSPEC_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
ROUND="${AUTOSPEC_EXPLORE_ROUND:-round}"
PROOF_DIR="${AUTOSPEC_STYLE_PROOF_DIR:-.autospec/style-normalization/$ROUND}"
MAX_PROPOSALS=40

empty() {
    echo '{"source":"style-normalization","proposals":[]}'
    exit 0
}

cd "$REPO_ROOT" || empty

if ! command -v python3 >/dev/null 2>&1; then
    empty
fi

frontend_tmp="$(mktemp -t style-frontend.XXXXXX)"
signals_tmp="$(mktemp -t style-signals.XXXXXX)"
trap 'rm -f "$frontend_tmp" "$signals_tmp"' EXIT

# Frontend signal scan. Keep it deterministic and cheap.
{
    [ -f package.json ] && grep -Eiq '"(react|vue|svelte|next|@angular/core|vite|astro|solid-js)"' package.json && echo "package.json:frontend dependency"
    [ -f tailwind.config.js ] && echo "tailwind.config.js:tailwind config"
    [ -f tailwind.config.ts ] && echo "tailwind.config.ts:tailwind config"
    [ -f playwright.config.js ] && echo "playwright.config.js:playwright config"
    [ -f playwright.config.ts ] && echo "playwright.config.ts:playwright config"
    find src app pages components -type f \
        \( -name '*.jsx' -o -name '*.tsx' -o -name '*.vue' -o -name '*.svelte' -o -name '*.css' -o -name '*.scss' -o -name '*.html' \) \
        2>/dev/null | head -n 20 | sed 's/$/:frontend file/'
} > "$frontend_tmp" || true

[ -s "$frontend_tmp" ] || empty

# Style drift signals: inline styles, raw colors, repeated one-off spacing/radii,
# and common primitive names spread across source files.
if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git grep -n -I -E '(style=\{\{|#[0-9A-Fa-f]{3,8}\b|borderRadius|border-radius|padding:\s*[0-9]+px|margin:\s*[0-9]+px|box-shadow|className=.*(btn|button|card|modal|table|input))' \
        -- 'src/**' 'app/**' 'pages/**' 'components/**' '*.css' '*.scss' 2>/dev/null \
        | head -n "$MAX_PROPOSALS" > "$signals_tmp" || true
else
    find src app pages components -type f 2>/dev/null \
        | while IFS= read -r f; do
            grep -n -E '(style=\{\{|#[0-9A-Fa-f]{3,8}\b|borderRadius|border-radius|padding:\s*[0-9]+px|margin:\s*[0-9]+px|box-shadow)' "$f" 2>/dev/null \
                | sed "s#^#$f:#"
        done | head -n "$MAX_PROPOSALS" > "$signals_tmp" || true
fi

[ -s "$signals_tmp" ] || empty

has_proof() {
    [ -d "$PROOF_DIR" ] || return 1
    test_count="$(find "$PROOF_DIR" -type f \
        \( -name '*.spec.ts' -o -name '*.spec.js' -o -name '*.test.ts' -o -name '*.test.js' \) \
        2>/dev/null | wc -l | tr -d ' ')"
    shot_count="$(find "$PROOF_DIR" -type f \
        \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.webp' \) \
        2>/dev/null | wc -l | tr -d ' ')"
    [ "${test_count:-0}" -gt 0 ] && [ "${shot_count:-0}" -gt 0 ]
}

if ! has_proof; then
    mkdir -p "$PROOF_DIR" 2>/dev/null || true
    export AUTOSPEC_STYLE_PROOF_DIR="$PROOF_DIR"
    if [ -n "${AUTOSPEC_EXPLORE_STYLE_PROOF_CMD:-}" ]; then
        bash -c "$AUTOSPEC_EXPLORE_STYLE_PROOF_CMD" >/dev/null 2>&1 || true
    elif command -v autospec-playwright >/dev/null 2>&1; then
        autospec-playwright >/dev/null 2>&1 || true
    elif command -v autospec-test >/dev/null 2>&1; then
        autospec-test --stage 2A >/dev/null 2>&1 || true
    fi
fi

# No proof means no proposal. The verify stage treats missing proof as refuted,
# but the researcher also refuses to file proofless proposals.
has_proof || empty

python3 - "$frontend_tmp" "$signals_tmp" "$PROOF_DIR" <<'PY'
import json, os, sys

frontend_path, signals_path, proof_dir = sys.argv[1:4]

def read_lines(path, limit):
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            return [line.rstrip("\n") for line in fh if line.strip()][:limit]
    except FileNotFoundError:
        return []

signals = read_lines(signals_path, 12)
front = read_lines(frontend_path, 5)

tests = []
shots = []
for root, _, files in os.walk(proof_dir):
    for name in files:
        rel = os.path.join(root, name)
        if name.endswith((".spec.ts", ".spec.js", ".test.ts", ".test.js")):
            tests.append(rel)
        if name.lower().endswith((".png", ".jpg", ".jpeg", ".webp")):
            shots.append(rel)
tests.sort()
shots.sort()

if not signals or not tests or not shots:
    print(json.dumps({"source": "style-normalization", "proposals": []}))
    raise SystemExit(0)

evidence = (
    "Frontend signals: " + "; ".join(front[:3]) +
    ". Style drift signals: " + "; ".join(signals[:5]) +
    f". Proof: Playwright={tests[0]} screenshot={shots[0]}"
)

proposal = {
    "title": "refactor(ui): normalize SPA style primitives behind shared tokens/components",
    "evidence": evidence[:1000],
    "estimated_complexity": "medium",
    "confidence": 0.78,
    "severity": "feature",
    "named_consumer": "/autospec-run Phase 4 implementer; /autospec-playwright Stage 2A",
    "proof_playwright": tests[0],
    "proof_screenshot": shots[0],
}

print(json.dumps({"source": "style-normalization", "proposals": [proposal]}))
PY
