"""The model catalog shown on the dashboard.

Generated by joining the live model list to the presets file, so the context sizes
and seat counts on the page cannot drift from what is actually served. An id with
no matching preset section yields None rather than a guess -- the page then shows
an em dash, which is honest.
"""
import importlib.util
import pathlib
import textwrap

SRC = pathlib.Path(__file__).resolve().parents[1] / "scripts" / "collect-stats.py"


def load():
    spec = importlib.util.spec_from_file_location("collect_stats", SRC)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


PRESETS = textwrap.dedent("""
    version = 1

    [*]
    n-gpu-layers = 999

    [qwen3.8-27b]
    model = /w/Qwen3.8-27B-UD-Q4_K_M.gguf
    c = 102400
    parallel = 2
    alias = qwen3.8-27b-50k,qwen3.8-27b-40k

    [qwen3.8-27b-100k]
    model = /w/Qwen3.8-27B-UD-Q4_K_M.gguf
    c = 102400
    parallel = 1

    [qwen3.8-27b-vision]
    model = /w/Qwen3.8-27B-UD-Q4_K_M.gguf
    mmproj = /w/mmproj-27b-F16.gguf
    c = 81920
    parallel = 2

    [qwen3.8-27b-uncensored]
    model = /w/Qwen3.8-27B-ABLITERATED-Q4_K_M.gguf
    c = 102400
    parallel = 2

    [qwen3.8-27b-uncensored-vision]
    model = /w/Qwen3.8-27B-ABLITERATED-Q4_K_M.gguf
    mmproj = /w/mmproj-uncensored-Q8_0.gguf
    c = 81920
    parallel = 2
    """)

MODELS = {"data": [
    {"id": "qwen3.8-27b", "aliases": ["qwen3.8-27b-40k"], "status": {"value": "loaded"}},
    {"id": "qwen3.8-27b-100k", "aliases": [], "status": {"value": "unloaded"}},
    {"id": "qwen3.8-27b-vision", "aliases": [], "status": {"value": "unloaded"}},
    {"id": "qwen3.8-27b-uncensored", "aliases": [], "status": {"value": "unloaded"}},
    {"id": "qwen3.8-27b-uncensored-vision", "aliases": [], "status": {"value": "unloaded"}},
]}


def cat():
    return {e["id"]: e for e in load().model_catalog(MODELS, PRESETS)}


def test_classifies_text_vision_and_uncensored():
    c = cat()
    assert c["qwen3.8-27b"]["kind"] == "text"
    assert c["qwen3.8-27b-vision"]["kind"] == "vision"
    assert c["qwen3.8-27b-uncensored"]["kind"] == "uncensored"
    assert c["qwen3.8-27b-uncensored-vision"]["kind"] == "uncensored-vision"


def test_reads_context_and_seats_from_the_presets():
    c = cat()
    assert c["qwen3.8-27b"]["context"] == 102400
    assert c["qwen3.8-27b"]["slots"] == 2


def test_vision_context_is_lower_because_it_pays_for_the_projector():
    assert cat()["qwen3.8-27b-vision"]["context"] == 81920


def test_hundred_k_preset_reports_one_seat():
    """One seat is the feature: it guarantees the warm-slot cache hit."""
    assert cat()["qwen3.8-27b-100k"]["slots"] == 1


def test_marks_exactly_one_resident():
    c = load().model_catalog(MODELS, PRESETS)
    assert [e["id"] for e in c if e["resident"]] == ["qwen3.8-27b"]


def test_aliases_are_carried_through():
    assert cat()["qwen3.8-27b"]["aliases"] == ["qwen3.8-27b-40k"]


def test_unknown_id_yields_none_rather_than_a_guess():
    c = load().model_catalog({"data": [{"id": "not-a-preset"}]}, PRESETS)
    assert c[0]["context"] is None and c[0]["slots"] is None
    assert c[0]["kind"] == "text"


def test_empty_inputs_are_an_empty_catalog():
    m = load()
    assert m.model_catalog({}, PRESETS) == []
    assert m.model_catalog(MODELS, "") != []          # ids still listed, context None
    assert all(e["context"] is None for e in m.model_catalog(MODELS, ""))
