//! #4499: a bare branch is not an attempt.
//!
//! The pass pushes a branch and only then opens the PR. A run killed in
//! that window leaves a branch on the remote with no PR — and the old
//! pass read that branch as "already attempted" and retired the issue
//! forever. These tests run the real pass against a real fixture repo with
//! an orphan `conv-*` branch on the bare origin: the plan must re-offer
//! the patch and report it as `interrupted` (distinct from `fresh`), and
//! `--apply` must redo it — overwriting the orphan branch — with the
//! per-issue `START`/`DONE` lines that make a killed run diagnosable.

use std::fs;
use std::path::Path;
use std::process::{Command, Stdio};

fn autospec_bin() -> &'static str {
    env!("CARGO_BIN_EXE_autospec")
}

fn run_git(dir: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(dir)
        .env("GIT_AUTHOR_NAME", "test")
        .env("GIT_AUTHOR_EMAIL", "test@example.com")
        .env("GIT_COMMITTER_NAME", "test")
        .env("GIT_COMMITTER_EMAIL", "test@example.com")
        .status()
        .expect("git runs");
    assert!(status.success(), "git {args:?} failed in {dir:?}");
}

fn run_git_output(dir: &Path, args: &[&str]) -> String {
    run_git_output_env(dir, args, &[], true)
}

/// `keep_trailing` keeps the final newline: a patch is a stream, and a
/// stream without its last newline is a corrupt patch (git refuses it).
fn run_git_output_env(
    dir: &Path,
    args: &[&str],
    envs: &[(&str, &str)],
    keep_trailing: bool,
) -> String {
    let mut command = Command::new("git");
    command
        .args(args)
        .current_dir(dir)
        .env("GIT_AUTHOR_NAME", "test")
        .env("GIT_AUTHOR_EMAIL", "test@example.com")
        .env("GIT_COMMITTER_NAME", "test")
        .env("GIT_COMMITTER_EMAIL", "test@example.com");
    for (key, value) in envs {
        command.env(key, value);
    }
    let output = command.output().expect("git runs");
    let text = String::from_utf8_lossy(&output.stdout);
    if keep_trailing {
        text.into_owned()
    } else {
        text.trim_end().to_string()
    }
}

/// A minimal, gate-green Rust crate at a bare local origin.
fn init_fixture_repo(repo: &Path, origin: &Path) -> String {
    fs::create_dir_all(repo.join("src")).unwrap();
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n",
    )
    .unwrap();
    fs::write(
        repo.join("src/lib.rs"),
        "pub fn one() -> u32 {\n    1\n}\n\n#[test]\nfn the_base_tests() {\n    assert_eq!(one(), 1);\n}\n",
    )
    .unwrap();
    run_git(repo, &["init", "-q", "-b", "main"]);
    let status = Command::new("git")
        .args(["init", "-q", "--bare", origin.to_str().unwrap()])
        .current_dir(repo)
        .status()
        .expect("git runs");
    assert!(status.success());
    run_git(repo, &["add", "-A"]);
    run_git(repo, &["commit", "-q", "-m", "base"]);
    run_git(repo, &["remote", "add", "origin", origin.to_str().unwrap()]);
    run_git(repo, &["push", "-q", "origin", "main"]);
    run_git_output(repo, &["rev-parse", "main:src/lib.rs"])
}

/// A stand-in for `gh`: no PRs exist (so the orphan branch is not live),
/// and `pr create` succeeds (so the redo opens its PR).
fn install_fake_gh(work: &Path) -> std::path::PathBuf {
    let bin_dir = work.join("fakebin");
    fs::create_dir_all(&bin_dir).unwrap();
    let shim = bin_dir.join("gh");
    fs::write(&shim, "#!/bin/sh\nexit 0\n").unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&shim, fs::Permissions::from_mode(0o755)).unwrap();
    }
    bin_dir
}

/// The patch, generated by `git diff` itself: a real agent patch is a real
/// diff, and a hand-rolled hunk count is where these tests rot.
fn write_patch(llm_root: &Path, repo: &Path, issue: u64) {
    let lib = repo.join("src/lib.rs");
    let base = fs::read_to_string(&lib).unwrap();
    fs::write(&lib, format!("{base}pub fn two() -> u32 {{\n    2\n}}\n")).unwrap();
    let patch = run_git_output(repo, &["diff"]);
    run_git(repo, &["checkout", "-q", "--", "src/lib.rs"]);
    let issue_dir = llm_root
        .join("node-a")
        .join("out")
        .join(format!("issue-{issue}"));
    fs::create_dir_all(&issue_dir).unwrap();
    fs::write(issue_dir.join("changes.patch"), patch).unwrap();
}

/// The orphan state: a `conv-<issue>` branch on the origin, no PR — a run
/// that was killed between the push and the `pr create`.
fn push_orphan_branch(repo: &Path, issue: u64) {
    run_git(repo, &["checkout", "-q", "-b", &format!("conv-{issue}")]);
    run_git(
        repo,
        &["commit", "-q", "--allow-empty", "-m", "orphan work"],
    );
    run_git(repo, &["push", "-q", "origin", &format!("conv-{issue}")]);
    run_git(repo, &["checkout", "-q", "main"]);
}

/// Run the pass with the given mode, capturing stdout.
fn run_pass(repo: &Path, llm_root: &Path, work: &Path, apply: bool) -> (i32, String, String) {
    let path = format!(
        "{}:{}",
        work.join("fakebin").display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let mut command = Command::new(autospec_bin());
    if apply {
        command.args(["convert", "--apply", "--llm-root"]);
    } else {
        command.args(["convert", "--llm-root"]);
    }
    command
        .arg(llm_root)
        .arg("--base")
        .arg("main")
        .arg("--repo")
        .arg("test/fake")
        .current_dir(repo)
        .env("LLM", "/nonexistent-llm-for-this-test")
        .env("PATH", &path)
        .env("GIT_AUTHOR_NAME", "test")
        .env("GIT_AUTHOR_EMAIL", "test@example.com")
        .env("GIT_COMMITTER_NAME", "test")
        .env("GIT_COMMITTER_EMAIL", "test@example.com")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let output = command.output().expect("autospec convert runs");
    (
        output.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&output.stdout).to_string(),
        String::from_utf8_lossy(&output.stderr).to_string(),
    )
}

#[test]
fn a_bare_branch_reoffers_and_reports_interruption() {
    let work = std::env::temp_dir().join(format!("autospec-conv-4499-plan-{}", std::process::id()));
    let _ = fs::remove_dir_all(&work);
    fs::create_dir_all(&work).unwrap();
    let repo = work.join("repo");
    let origin = work.join("origin.git");
    let llm_root = work.join("llm");
    init_fixture_repo(&repo, &origin);
    write_patch(&llm_root, &repo, 4491);
    push_orphan_branch(&repo, 4491);
    let _ = install_fake_gh(&work);

    // Plan mode: the patch is offered — not retired — and the report says
    // it was an interrupted attempt, on its own category.
    let (code, stdout, _stderr) = run_pass(&repo, &llm_root, &work, false);
    assert_eq!(code, 0, "a plan is a diagnostic, not a failure:\n{stdout}");
    assert!(
        stdout.contains("  FRESH #4491"),
        "the interrupted attempt is re-offered:\n{stdout}"
    );
    assert!(
        stdout.contains("  INTERRUPTED #4491"),
        "the orphan is named, distinct from the fresh candidates:\n{stdout}"
    );
    assert!(
        stdout.contains("interrupted=1"),
        "the selection line carries the category:\n{stdout}"
    );
    // And the JSON says the same, machine-readably.
    let json_output = Command::new(autospec_bin())
        .args(["convert", "--llm-root"])
        .arg(&llm_root)
        .arg("--base")
        .arg("main")
        .arg("--repo")
        .arg("test/fake")
        .arg("--json")
        .current_dir(&repo)
        .env("LLM", "/nonexistent-llm-for-this-test")
        .env(
            "PATH",
            format!(
                "{}:{}",
                work.join("fakebin").display(),
                std::env::var("PATH").unwrap_or_default()
            ),
        )
        .env("GIT_AUTHOR_NAME", "test")
        .env("GIT_AUTHOR_EMAIL", "test@example.com")
        .env("GIT_COMMITTER_NAME", "test")
        .env("GIT_COMMITTER_EMAIL", "test@example.com")
        .output()
        .expect("autospec convert --json runs");
    let json = String::from_utf8_lossy(&json_output.stdout);
    assert!(
        json.contains("\"interrupted\""),
        "the JSON selection names the interrupted category:\n{json}"
    );
    let _ = fs::remove_dir_all(&work);
}

#[test]
fn an_apply_pass_redoes_the_orphan_and_names_start_and_done() {
    let work =
        std::env::temp_dir().join(format!("autospec-conv-4499-apply-{}", std::process::id()));
    let _ = fs::remove_dir_all(&work);
    fs::create_dir_all(&work).unwrap();
    let repo = work.join("repo");
    let origin = work.join("origin.git");
    let llm_root = work.join("llm");
    init_fixture_repo(&repo, &origin);
    write_patch(&llm_root, &repo, 4493);
    push_orphan_branch(&repo, 4493);
    let _ = install_fake_gh(&work);

    // The orphan's tip is an empty commit off main; the redo must replace
    // it with the converted patch — a plain push would be refused as
    // non-fast-forward, so the pass force-pushes over its own orphan.
    let (code, stdout, stderr) = run_pass(&repo, &llm_root, &work, true);
    assert_eq!(code, 0, "the redo converts:\n{stdout}\nstderr:\n{stderr}");
    assert!(
        stdout.contains("  START  #4493"),
        "the issue is on the record before the first remote write:\n{stdout}"
    );
    assert!(
        stdout.contains(&format!("  DONE   #4493: converted")),
        "the issue's outcome is printed at the moment it happened:\n{stdout}"
    );
    // The branch now carries the patch, not the orphan's empty commit.
    let converted = run_git_output(&repo, &["show", "origin/conv-4493:src/lib.rs"]);
    assert!(
        converted.contains("pub fn two"),
        "the orphan branch was overwritten by the redo:\n{converted}"
    );
    let _ = fs::remove_dir_all(&work);
}

/// #4501: a patch whose changes are already in the base is residue.
///
/// The incident: a PR that merged the work left the issue open (the number
/// was in the title, not a closing keyword in the body). Every pass then
/// re-fetched the patch, applied it, and spent a full gate on "no change."
/// The pass must detect the residue with a read-only reverse-apply check,
/// report it as `delivered` (never offered, never gated), and — in apply
/// mode — archive it so the backlog stops counting it as pending.
#[test]
fn a_patch_already_in_the_base_is_delivered_not_fresh() {
    let work = std::env::temp_dir().join(format!("autospec-conv-delivered-{}", std::process::id()));
    let _ = fs::remove_dir_all(&work);
    let repo = work.join("repo");
    let origin = work.join("origin.git");
    let llm_root = work.join("llm");
    fs::create_dir_all(&repo).unwrap();
    fs::create_dir_all(&llm_root).unwrap();

    // The base: one function.
    fs::create_dir_all(repo.join("src")).unwrap();
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n",
    )
    .unwrap();
    fs::write(
        repo.join("src/lib.rs"),
        "pub fn one() -> u32 {\n    1\n}\n\n#[test]\nfn the_base_tests() {\n    assert_eq!(one(), 1);\n}\n",
    )
    .unwrap();
    run_git(&repo, &["init", "-q", "-b", "main"]);
    let status = Command::new("git")
        .args(["init", "-q", "--bare", origin.to_str().unwrap()])
        .current_dir(&repo)
        .status()
        .expect("git runs");
    assert!(status.success());
    run_git(&repo, &["add", "-A"]);
    run_git(&repo, &["commit", "-q", "-m", "base"]);
    run_git(
        &repo,
        &["remote", "add", "origin", origin.to_str().unwrap()],
    );
    run_git(&repo, &["push", "-q", "origin", "main"]);

    // The work is delivered: main now carries the function the patch adds.
    let lib = repo.join("src/lib.rs");
    let base = fs::read_to_string(&lib).unwrap();
    fs::write(&lib, format!("{base}pub fn two() -> u32 {{\n    2\n}}\n")).unwrap();
    run_git(&repo, &["add", "-A"]);
    run_git(&repo, &["commit", "-q", "-m", "the delivered work"]);
    run_git(&repo, &["push", "-q", "origin", "main"]);

    // The patch: the base-to-delivered diff, still sitting on disk.
    let patch = run_git_output(&repo, &["diff", "main~1", "main", "--", "src/lib.rs"]);
    let issue_dir = llm_root.join("node-a").join("out").join("issue-777");
    fs::create_dir_all(&issue_dir).unwrap();
    fs::write(issue_dir.join("changes.patch"), &patch).unwrap();
    let patch_path = issue_dir.join("changes.patch");
    let bin_dir = install_fake_gh(&work);

    // Plan: reported as delivered, never offered, never archived.
    let (code, out, err) = run_pass(&repo, &llm_root, &work, false);
    assert_eq!(code, 0, "plan exits clean: {out} {err}");
    assert!(
        out.contains("DELIVERED #777"),
        "named on its own line: {out}"
    );
    assert!(
        out.contains("delivered=1"),
        "counted on the selection line: {out}"
    );
    assert!(out.contains("fresh=0"), "residue is never offered: {out}");
    assert!(patch_path.exists(), "the plan archives nothing");

    // Apply: archived (the queue entry is released) and reported.
    let (code, out, err) = run_pass(&repo, &llm_root, &work, true);
    assert_eq!(code, 0, "apply exits clean: {out} {err}");
    assert!(
        out.contains("DELIVERED #777"),
        "named on its own line: {out}"
    );
    assert!(out.contains("delivered=1"), "counted in the outcome: {out}");
    assert!(
        !patch_path.exists(),
        "the residue leaves disk, so the next pass stops enumerating it"
    );
    let archived = fs::read_dir(issue_dir.join("superseded"))
        .expect("the superseded directory exists")
        .filter_map(|e| e.ok())
        .count();
    assert_eq!(archived, 1, "the patch is archived, never discarded");

    let _ = fs::remove_dir_all(&work);
    let _ = bin_dir;
}
