//! Conflict-resolution policy (issue #3663).
//!
//! A blanket "keep both sides" hunk strategy is right for some file shapes —
//! two independent `pub mod` declarations, two changelog entries — and it
//! corrupts others. A `.sha256` golden whose entire content is one value ends
//! up holding the old hash and the new one, and `cargo build` and
//! `cargo fmt --check` both pass over it, because fixture data is not code.
//!
//! The rule this module encodes: **a conflict-resolution strategy is a
//! property of the file, not a property of the merge.**
//!
//! | file shape                          | correct resolution        |
//! | ----------------------------------- | ------------------------- |
//! | append-only list (changelog, …)     | keep both, in order       |
//! | additive declarations (`pub mod`)   | keep both, deduplicated   |
//! | single authoritative value          | regenerate from source    |
//! | generated artefact                  | regenerate, never hand-merge |
//!
//! Auto-resolution **refuses** any file it cannot classify rather than
//! applying a default. For the bottom two rows there is no correct
//! hand-resolution: the file is not the source of truth — something else is,
//! and the file is its shadow. A strategy applied to a file that is not the
//! source of truth is a guess, and the guess is exactly the corruption.

use std::collections::BTreeMap;
use std::path::Path;

/// The shape of a conflicted file. The shape — not the merge — determines the
/// correct resolution strategy.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FileShape {
    /// Append-only list (changelog, allowlist): entries accumulate in order.
    AppendOnlyList,
    /// Additive declarations (`pub mod`, imports): entries form a set.
    AdditiveDeclarations,
    /// A single authoritative value (checksum, version, lockfile entry). The
    /// file is the shadow of a source of truth that lives elsewhere.
    SingleValue,
    /// A generated artefact whose header names the generator that owns it.
    Generated { generator: String },
    /// Not classifiable from path or header.
    Unknown,
}

impl FileShape {
    pub fn as_str(&self) -> &'static str {
        match self {
            FileShape::AppendOnlyList => "append_only_list",
            FileShape::AdditiveDeclarations => "additive_declarations",
            FileShape::SingleValue => "single_value",
            FileShape::Generated { .. } => "generated",
            FileShape::Unknown => "unknown",
        }
    }
}

/// Comment prefixes that may open a generated-file header.
///
/// Ordered: `<!--` must be tried before `--` and `/*` before any `/` prefix,
/// or the shorter prefix would eat the longer one's first characters.
const HEADER_PREFIXES: [&str; 6] = ["<!--", "/*", "//", "#", "--", ";"];

/// Trailing comment closers. Prose after the closer is not part of the header.
const HEADER_CLOSES: [&str; 2] = ["-->", "*/"];

/// Parse the generated-file header: the file's first line, a comment naming
/// the generator that owns the file.
///
/// Grammar: `<comment-prefix> Generated by <generator>` where
/// `<generator>` is a single whitespace-free token (a script path or a
/// command name). The `<!--` / `/*` forms may close on the same line.
/// Anything looser — prose after the token, a multi-word generator, a header
/// on line two — is not a header, and the file falls back to path-based
/// classification or [`FileShape::Unknown`].
pub fn parse_generator_header(content: &str) -> Option<String> {
    let first = content.lines().next()?;
    let body = first.trim_start();
    // Prose after a comment close (`-->`, `*/`) is not part of the header;
    // cut at whichever closer appears first.
    let mut end = body.len();
    for close in HEADER_CLOSES {
        if let Some(pos) = body.find(close) {
            end = end.min(pos);
        }
    }
    let body = body[..end].trim_end();
    let rest = HEADER_PREFIXES
        .iter()
        .find_map(|prefix| body.strip_prefix(prefix))
        .map(str::trim_start)?;
    let marker = "generated by";
    if !rest.to_ascii_lowercase().starts_with(marker) {
        return None;
    }
    let generator = rest[marker.len()..].trim();
    if generator.is_empty() || generator.contains(char::is_whitespace) {
        return None;
    }
    Some(generator.to_string())
}

fn file_name(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path)
}

fn extension_lower(path: &str) -> Option<String> {
    Path::new(file_name(path))
        .extension()
        .and_then(|ext| ext.to_str())
        .map(|ext| ext.to_ascii_lowercase())
}

/// Whether `path` names a single-value file by its file name or extension:
/// a checksum golden (`.sha256`, `.sha512`, `.md5`) or a version file.
///
/// Deliberately path-based, not content-based: the corrupted form of a
/// `.sha256` golden — two hashes — must still classify as single-value so the
/// shape check can flag it.
pub fn is_single_value_path(path: &str) -> bool {
    let lower = file_name(path).to_ascii_lowercase();
    matches!(lower.as_str(), "version" | "version.txt" | ".version")
        || matches!(
            extension_lower(path).as_deref(),
            Some("sha256" | "sha512" | "md5")
        )
}

/// Classify a conflicted file by its path and content.
///
/// Conservative on purpose: anything not confidently recognizable is
/// [`FileShape::Unknown`], and unknown files are refused, not defaulted.
pub fn classify_file(path: &str, content: &str) -> FileShape {
    if let Some(generator) = parse_generator_header(content) {
        return FileShape::Generated { generator };
    }
    if is_single_value_path(path) {
        return FileShape::SingleValue;
    }
    let lower = file_name(path).to_ascii_lowercase();
    match lower.as_str() {
        "changelog" | "changelog.md" | "changelog.txt" | "allowlist" => {
            return FileShape::AppendOnlyList;
        }
        "mod.rs" | "lib.rs" => return FileShape::AdditiveDeclarations,
        _ => {}
    }
    if lower.ends_with(".allowlist") {
        return FileShape::AppendOnlyList;
    }
    FileShape::Unknown
}

/// The resolution a conflicted file's shape dictates.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ResolutionPlan {
    /// Append-only list: keep both sides, in order.
    KeepBothInOrder,
    /// Additive declarations: keep both sides, deduplicated.
    KeepBothDeduplicated,
    /// Single authoritative value or generated artefact: regenerate from
    /// source. `generator` is the header-declared name when the file has one;
    /// otherwise the repository registry must supply it by path.
    Regenerate { generator: Option<String> },
    /// The file's shape could not be classified. Auto-resolution refuses
    /// rather than applying a default — a default strategy here is the
    /// corruption #3663 describes.
    Refuse { reason: String },
}

impl ResolutionPlan {
    pub fn as_str(&self) -> &'static str {
        match self {
            ResolutionPlan::KeepBothInOrder => "keep_both_in_order",
            ResolutionPlan::KeepBothDeduplicated => "keep_both_deduplicated",
            ResolutionPlan::Regenerate { .. } => "regenerate",
            ResolutionPlan::Refuse { .. } => "refuse",
        }
    }
}

/// Map a file shape to its resolution plan. The table in #3663, verbatim:
/// keep-both (two flavours) for the two list shapes, regeneration for the two
/// shadow shapes, and refusal for everything the classifier did not claim.
pub fn resolution_for(shape: &FileShape) -> ResolutionPlan {
    match shape {
        FileShape::AppendOnlyList => ResolutionPlan::KeepBothInOrder,
        FileShape::AdditiveDeclarations => ResolutionPlan::KeepBothDeduplicated,
        FileShape::SingleValue => ResolutionPlan::Regenerate { generator: None },
        FileShape::Generated { generator } => ResolutionPlan::Regenerate {
            generator: Some(generator.clone()),
        },
        FileShape::Unknown => ResolutionPlan::Refuse {
            reason: "unclassifiable file shape: no conflict-resolution strategy applies, and a \
                     default would be a guess"
                .to_string(),
        },
    }
}

/// The repository's generator registry: which generator owns which files.
///
/// A single-value file (a `.sha256` golden) has no room for a header, so the
/// registry — not the file — says where its source of truth lives.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GeneratorRegistry {
    /// Exact file path, or a directory prefix ending in `/` (everything under
    /// it) → generator name.
    owners: BTreeMap<String, String>,
}

impl GeneratorRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Record that `generator` owns `path` — an exact file path, or a
    /// directory prefix ending in `/` covering everything under it.
    pub fn register(&mut self, path: &str, generator: &str) {
        self.owners.insert(path.to_string(), generator.to_string());
    }

    /// The generator that owns `path`: an exact entry wins, else the longest
    /// matching directory prefix. `None` when nothing owns the file — and
    /// nothing owning the file means regeneration is refused, not guessed.
    pub fn generator_for(&self, path: &str) -> Option<&str> {
        if let Some(generator) = self.owners.get(path) {
            return Some(generator.as_str());
        }
        self.owners
            .iter()
            .filter(|(prefix, _)| prefix.ends_with('/') && path.starts_with(prefix.as_str()))
            .max_by_key(|(prefix, _)| prefix.len())
            .map(|(_, generator)| generator.as_str())
    }
}

/// Executes a named generator. The core stays platform-agnostic; the caller
/// supplies the shell (or a test double).
pub trait GeneratorRunner {
    /// Run the named generator. `Err` when it is unknown or fails.
    fn run(&self, generator: &str) -> Result<(), String>;
}

/// What auto-resolution did with a conflicted file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutoResolutionOutcome {
    /// A text merge is correct for this shape; the plan names the flavour
    /// (in order, or deduplicated).
    TextMerge { plan: ResolutionPlan },
    /// The file is the shadow of its source of truth: the generator was run
    /// and its result taken, which cannot guess wrong.
    Regenerated { generator: String },
}

/// Why auto-resolution could not take a conflicted file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutoResolutionError {
    /// The file's shape could not be classified. A default strategy is
    /// exactly the corruption #3663 describes; a human resolves this one.
    RefusedUnclassifiable { path: String, reason: String },
    /// A single-value or generated file that no registered generator owns.
    NoGenerator { path: String },
    /// The generator failed.
    GeneratorFailed {
        path: String,
        generator: String,
        error: String,
    },
    /// The generator ran but the file it left behind fails the shape check.
    PostCheckFailed { path: String, findings: Vec<String> },
    /// The regenerated file could not be read back.
    UnreadableAfterGeneration { path: String },
}

/// The resolution step for one conflicted file.
///
/// Classifies the file, then applies the strategy its shape dictates. For the
/// keep-both shapes it returns the text-merge plan. For the regenerate shapes
/// it looks the generator up — the file's header first, then the repository
/// registry — runs it, and takes its result: re-reading the file through
/// `read_back` and running the shape check on what the generator left
/// behind, so a generator that produces garbage is rejected rather than
/// merged.
pub fn auto_resolve(
    path: &str,
    content: &str,
    registry: &GeneratorRegistry,
    runner: &dyn GeneratorRunner,
    read_back: &dyn Fn(&str) -> Option<String>,
) -> Result<AutoResolutionOutcome, AutoResolutionError> {
    let shape = classify_file(path, content);
    match resolution_for(&shape) {
        plan @ (ResolutionPlan::KeepBothInOrder | ResolutionPlan::KeepBothDeduplicated) => {
            Ok(AutoResolutionOutcome::TextMerge { plan })
        }
        ResolutionPlan::Regenerate {
            generator: declared,
        } => {
            let generator = declared
                .as_deref()
                .or_else(|| registry.generator_for(path))
                .ok_or(AutoResolutionError::NoGenerator {
                    path: path.to_string(),
                })?;
            runner
                .run(generator)
                .map_err(|error| AutoResolutionError::GeneratorFailed {
                    path: path.to_string(),
                    generator: generator.to_string(),
                    error,
                })?;
            let regenerated =
                read_back(path).ok_or_else(|| AutoResolutionError::UnreadableAfterGeneration {
                    path: path.to_string(),
                })?;
            let findings = check_single_value_file(path, &regenerated);
            if findings.is_empty() {
                Ok(AutoResolutionOutcome::Regenerated {
                    generator: generator.to_string(),
                })
            } else {
                Err(AutoResolutionError::PostCheckFailed {
                    path: path.to_string(),
                    findings,
                })
            }
        }
        ResolutionPlan::Refuse { reason } => Err(AutoResolutionError::RefusedUnclassifiable {
            path: path.to_string(),
            reason,
        }),
    }
}

/// Shape check for single-value files: a checksum, version, or lockfile entry
/// holds exactly one non-blank line.
///
/// A `.sha256` golden holding two hashes — the corruption #3663 describes —
/// is malformed regardless of what it contains, and it is one `wc -l` away
/// from being caught: exactly this check. Files whose shape is not
/// single-value return no findings.
pub fn check_single_value_file(path: &str, content: &str) -> Vec<String> {
    if !is_single_value_path(path) {
        return Vec::new();
    }
    let values: Vec<&str> = content
        .lines()
        .filter(|line| !line.trim().is_empty())
        .collect();
    match values.len() {
        0 => vec![format!(
            "{path}: malformed single-value file: no value where exactly 1 line is allowed"
        )],
        1 => Vec::new(),
        n => vec![format!(
            "{path}: malformed single-value file: {n} lines where exactly 1 is allowed \
             (a checksum/version holds a single value; regenerate it instead of merging)"
        )],
    }
}

/// One finding from the shape gate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShapeGateFinding {
    pub path: String,
    pub detail: String,
}

/// Gate-set entry (#3663): run the single-value shape check over a population
/// of files and report every member that fails it.
///
/// The habit this gate closes: applying an operation to a population without
/// checking that every member of the population admits it.
pub fn shape_gate(files: &[(String, String)]) -> Vec<ShapeGateFinding> {
    files
        .iter()
        .flat_map(|(path, content)| {
            check_single_value_file(path, content)
                .into_iter()
                .map(|detail| ShapeGateFinding {
                    path: path.clone(),
                    detail,
                })
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Two distinct sha256 hex digests, standing in for "ours" and "theirs".
    const HASH_A: &str = "89be3092852d83aedf6baaa04ee8fdba6288a24cd2a72cbfe22367e2967b3c4e";
    const HASH_B: &str = "46151f077983878b27168cd89458df806e71b23426d633cd60d1121f58878c62";
    const GOLDEN_PATH: &str = "tests/fixtures/skill-goldens/autospec.SKILL.md.sha256";
    /// The corrupted form #3663 describes: both hashes, kept.
    const CORRUPTED_GOLDEN: &str = "89be3092852d83aedf6baaa04ee8fdba6288a24cd2a72cbfe22367e2967b3c4e\n46151f077983878b27168cd89458df806e71b23426d633cd60d1121f58878c62";

    fn not_readable(_path: &str) -> Option<String> {
        None
    }

    fn registry_with_golden_owner() -> GeneratorRegistry {
        let mut registry = GeneratorRegistry::new();
        registry.register(
            "tests/fixtures/skill-goldens/",
            "scripts/gen-skill-goldens.sh",
        );
        registry
    }

    struct NoopRunner {
        ran: std::sync::Mutex<Vec<String>>,
    }

    impl NoopRunner {
        fn new() -> Self {
            Self {
                ran: std::sync::Mutex::new(Vec::new()),
            }
        }
        fn ran_generators(&self) -> Vec<String> {
            self.ran.lock().unwrap().clone()
        }
    }

    impl GeneratorRunner for NoopRunner {
        fn run(&self, generator: &str) -> Result<(), String> {
            self.ran.lock().unwrap().push(generator.to_string());
            Ok(())
        }
    }

    #[test]
    fn a_sha256_golden_classifies_as_single_value() {
        assert_eq!(classify_file(GOLDEN_PATH, HASH_A), FileShape::SingleValue);
        // The corrupted form still classifies by path, not content.
        assert_eq!(
            classify_file(GOLDEN_PATH, CORRUPTED_GOLDEN),
            FileShape::SingleValue
        );
    }

    #[test]
    fn a_version_file_classifies_as_single_value() {
        assert_eq!(classify_file("VERSION", "1.4.2"), FileShape::SingleValue);
        assert_eq!(
            classify_file("release/.version", "3\n"),
            FileShape::SingleValue
        );
    }

    #[test]
    fn a_generated_header_names_the_generator() {
        let content = "// Generated by scripts/gen-skill-goldens.sh\npub struct Bindings;\n";
        assert_eq!(
            classify_file("src/bindings.rs", content),
            FileShape::Generated {
                generator: "scripts/gen-skill-goldens.sh".to_string()
            }
        );
    }

    #[test]
    fn an_html_and_c_block_comment_header_are_recognized() {
        assert_eq!(
            parse_generator_header("<!-- Generated by bindgen -->\nfn main() {}"),
            Some("bindgen".to_string())
        );
        assert_eq!(
            parse_generator_header("/* Generated by schema-gen */\nint x;"),
            Some("schema-gen".to_string())
        );
        assert_eq!(
            parse_generator_header("# generated by make-goldens\nvalue"),
            Some("make-goldens".to_string())
        );
    }

    #[test]
    fn a_header_with_prose_after_the_token_is_not_a_header() {
        // The generator must be a single token; free text after it means the
        // line is documentation, not a declaration of ownership.
        assert_eq!(
            parse_generator_header("// Generated by scripts/gen-skill-goldens.sh — do not edit\n"),
            None
        );
        assert_eq!(
            parse_generator_header("// Generated by schema-gen --generate\n"),
            None
        );
    }

    #[test]
    fn a_header_on_the_second_line_is_not_a_header() {
        assert_eq!(parse_generator_header("\n# Generated by x\n"), None);
        assert_eq!(parse_generator_header("value\n# Generated by x\n"), None);
    }

    #[test]
    fn a_changelog_or_allowlist_classifies_as_append_only() {
        assert_eq!(
            classify_file("docs/CHANGELOG.md", "# 1.4.2\n- fix\n"),
            FileShape::AppendOnlyList
        );
        assert_eq!(
            classify_file("tools/allowlist", "alpha\n"),
            FileShape::AppendOnlyList
        );
        assert_eq!(
            classify_file("tools/trusted-paths.allowlist", "a/\n"),
            FileShape::AppendOnlyList
        );
    }

    #[test]
    fn a_mod_or_lib_file_classifies_as_additive_declarations() {
        assert_eq!(
            classify_file("src/lib.rs", "pub mod a;\npub mod b;\n"),
            FileShape::AdditiveDeclarations
        );
        assert_eq!(
            classify_file("src/a/mod.rs", "pub mod b;\n"),
            FileShape::AdditiveDeclarations
        );
    }

    #[test]
    fn anything_else_is_unknown() {
        assert_eq!(
            classify_file("src/main.rs", "fn main() {}\n"),
            FileShape::Unknown
        );
        assert_eq!(classify_file("README.md", "# Title\n"), FileShape::Unknown);
        assert_eq!(
            classify_file("data/config.yaml", "a: 1\n"),
            FileShape::Unknown
        );
    }

    #[test]
    fn the_plan_table_matches_the_issue() {
        assert_eq!(
            resolution_for(&FileShape::AppendOnlyList),
            ResolutionPlan::KeepBothInOrder
        );
        assert_eq!(
            resolution_for(&FileShape::AdditiveDeclarations),
            ResolutionPlan::KeepBothDeduplicated
        );
        assert_eq!(
            resolution_for(&FileShape::SingleValue),
            ResolutionPlan::Regenerate { generator: None }
        );
        assert_eq!(
            resolution_for(&FileShape::Generated {
                generator: "g".into()
            }),
            ResolutionPlan::Regenerate {
                generator: Some("g".into())
            }
        );
    }

    #[test]
    fn an_unknown_shape_is_refused_not_defaulted() {
        let plan = resolution_for(&FileShape::Unknown);
        match &plan {
            ResolutionPlan::Refuse { reason } => assert!(!reason.is_empty()),
            other => panic!("unknown shape must be refused, got {other:?}"),
        }
        assert_eq!(plan.as_str(), "refuse");
    }

    #[test]
    fn the_shape_check_flags_the_corruption() {
        let findings = check_single_value_file(GOLDEN_PATH, CORRUPTED_GOLDEN);
        assert_eq!(findings.len(), 1);
        assert!(
            findings[0].contains("2 lines where exactly 1 is allowed"),
            "unexpected finding: {}",
            findings[0]
        );
    }

    #[test]
    fn the_shape_check_passes_a_single_value_and_ignores_other_shapes() {
        assert!(check_single_value_file(GOLDEN_PATH, HASH_A).is_empty());
        assert!(
            check_single_value_file("docs/CHANGELOG.md", "a\nb\nc\n").is_empty(),
            "a two-line changelog is well-formed"
        );
        assert!(!check_single_value_file(GOLDEN_PATH, "").is_empty());
    }

    #[test]
    fn the_registry_prefers_an_exact_entry_over_a_directory_prefix() {
        let mut registry = GeneratorRegistry::new();
        registry.register(
            "tests/fixtures/skill-goldens/",
            "scripts/gen-skill-goldens.sh",
        );
        registry.register(
            "tests/fixtures/skill-goldens/autospec.SKILL.md.sha256",
            "scripts/gen-one-golden.sh",
        );
        assert_eq!(
            registry.generator_for("tests/fixtures/skill-goldens/autospec.SKILL.md.sha256"),
            Some("scripts/gen-one-golden.sh")
        );
        assert_eq!(
            registry.generator_for("tests/fixtures/skill-goldens/other.md.sha256"),
            Some("scripts/gen-skill-goldens.sh")
        );
        assert_eq!(registry.generator_for("elsewhere/x.sha256"), None);
    }

    #[test]
    fn the_registry_prefers_the_longest_matching_prefix() {
        let mut registry = GeneratorRegistry::new();
        registry.register("tests/", "scripts/gen-all.sh");
        registry.register("tests/fixtures/", "scripts/gen-fixtures.sh");
        assert_eq!(
            registry.generator_for("tests/fixtures/skill-goldens/x.sha256"),
            Some("scripts/gen-fixtures.sh")
        );
    }

    #[test]
    fn auto_resolve_refuses_an_unclassifiable_file() {
        let registry = GeneratorRegistry::new();
        let runner = NoopRunner::new();
        let outcome = auto_resolve(
            "src/main.rs",
            "fn main() {}\n",
            &registry,
            &runner,
            &not_readable,
        );
        match outcome {
            Err(AutoResolutionError::RefusedUnclassifiable { path, .. }) => {
                assert_eq!(path, "src/main.rs");
            }
            other => panic!("expected refusal, got {other:?}"),
        }
        assert!(runner.ran_generators().is_empty());
    }

    #[test]
    fn auto_resolve_returns_the_text_merge_plan_for_list_shapes() {
        let registry = GeneratorRegistry::new();
        let runner = NoopRunner::new();
        let outcome = auto_resolve(
            "docs/CHANGELOG.md",
            "# 1.4.2\n",
            &registry,
            &runner,
            &not_readable,
        )
        .unwrap();
        assert_eq!(
            outcome,
            AutoResolutionOutcome::TextMerge {
                plan: ResolutionPlan::KeepBothInOrder
            }
        );
    }

    #[test]
    fn auto_resolve_runs_the_registry_generator_and_takes_its_result() {
        let registry = registry_with_golden_owner();
        let runner = NoopRunner::new();
        let outcome = auto_resolve(GOLDEN_PATH, CORRUPTED_GOLDEN, &registry, &runner, &|_| {
            Some(HASH_B.to_string())
        })
        .unwrap();
        assert_eq!(
            outcome,
            AutoResolutionOutcome::Regenerated {
                generator: "scripts/gen-skill-goldens.sh".to_string()
            }
        );
        assert_eq!(
            runner.ran_generators(),
            vec!["scripts/gen-skill-goldens.sh".to_string()]
        );
    }

    #[test]
    fn a_header_declared_generator_wins_over_the_registry() {
        let registry = registry_with_golden_owner();
        let runner = NoopRunner::new();
        let content = "# Generated by make-goldens\nfn main() {}\n";
        let outcome = auto_resolve("src/bindings.rs", content, &registry, &runner, &|_| {
            Some("regenerated\n".to_string())
        })
        .unwrap();
        assert_eq!(
            outcome,
            AutoResolutionOutcome::Regenerated {
                generator: "make-goldens".to_string()
            }
        );
    }

    #[test]
    fn auto_resolve_refuses_when_no_generator_owns_the_file() {
        let registry = GeneratorRegistry::new();
        let runner = NoopRunner::new();
        let outcome = auto_resolve(GOLDEN_PATH, CORRUPTED_GOLDEN, &registry, &runner, &|_| {
            Some(HASH_B.to_string())
        });
        assert_eq!(
            outcome,
            Err(AutoResolutionError::NoGenerator {
                path: GOLDEN_PATH.to_string()
            })
        );
        assert!(runner.ran_generators().is_empty());
    }

    #[test]
    fn auto_resolve_reports_a_failed_generator() {
        struct FailingRunner;
        impl GeneratorRunner for FailingRunner {
            fn run(&self, _generator: &str) -> Result<(), String> {
                Err("command not found".to_string())
            }
        }
        let registry = registry_with_golden_owner();
        let outcome = auto_resolve(
            GOLDEN_PATH,
            CORRUPTED_GOLDEN,
            &registry,
            &FailingRunner,
            &|_| Some(HASH_B.to_string()),
        );
        assert_eq!(
            outcome,
            Err(AutoResolutionError::GeneratorFailed {
                path: GOLDEN_PATH.to_string(),
                generator: "scripts/gen-skill-goldens.sh".to_string(),
                error: "command not found".to_string(),
            })
        );
    }

    #[test]
    fn auto_resolve_rejects_a_regeneration_that_still_fails_the_shape_check() {
        let registry = registry_with_golden_owner();
        let runner = NoopRunner::new();
        // A generator that "regenerates" into the same two-line corruption.
        let outcome = auto_resolve(GOLDEN_PATH, CORRUPTED_GOLDEN, &registry, &runner, &|_| {
            Some(CORRUPTED_GOLDEN.to_string())
        });
        match outcome {
            Err(AutoResolutionError::PostCheckFailed { path, findings }) => {
                assert_eq!(path, GOLDEN_PATH);
                assert_eq!(findings.len(), 1);
            }
            other => panic!("expected post-check failure, got {other:?}"),
        }
    }

    #[test]
    fn auto_resolve_rejects_a_regeneration_it_cannot_read_back() {
        let registry = registry_with_golden_owner();
        let runner = NoopRunner::new();
        let outcome = auto_resolve(
            GOLDEN_PATH,
            CORRUPTED_GOLDEN,
            &registry,
            &runner,
            &not_readable,
        );
        assert_eq!(
            outcome,
            Err(AutoResolutionError::UnreadableAfterGeneration {
                path: GOLDEN_PATH.to_string()
            })
        );
    }

    #[test]
    fn the_shape_gate_reports_every_malformed_member_of_the_population() {
        let files = vec![
            ("a.sha256".to_string(), HASH_A.to_string()),
            ("b.sha256".to_string(), CORRUPTED_GOLDEN.to_string()),
            (
                "c.sha256".to_string(),
                format!("{HASH_A}\n{HASH_B}\n{HASH_A}"),
            ),
            ("changelog.md".to_string(), "a\nb\n".to_string()),
        ];
        let findings = shape_gate(&files);
        assert_eq!(
            findings.iter().map(|f| f.path.as_str()).collect::<Vec<_>>(),
            vec!["b.sha256", "c.sha256"]
        );
    }
}
