#!/usr/bin/env bash
# skills/autospec-harmonize/scripts/design-discover.sh
#
# Orchestrator that selects the runtime vs source token extractor with fallback,
# writes <out>/discovered-tokens.json and <out>/inventory.md.
#
# CLI: design-discover.sh --root <dir> [--url <u>] [--source-only]
#                         [--pages <list>] --out <dir>
#
# Exit 0 when the source extractor (or runtime extractor) succeeds.
# If the runtime extractor fails (exit 3 = harmonize_runtime_unavailable or any
# non-zero), the unavailability signal is echoed and we fall back to source.

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve sibling extractor scripts relative to THIS script's own directory
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Allow override via env (useful in some test harnesses), but default to sibling dir
EXTRACT_SOURCE="${AUTOSPEC_SCRIPTS_DIR:-$SCRIPT_DIR}/extract-source.mjs"
EXTRACT_RUNTIME="${AUTOSPEC_SCRIPTS_DIR:-$SCRIPT_DIR}/extract-runtime.mjs"

# ---------------------------------------------------------------------------
# Arg parsing
# ---------------------------------------------------------------------------
ROOT=""
URL=""
SOURCE_ONLY=0
PAGES=""
OUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)       ROOT="$2";    shift 2 ;;
    --url)        URL="$2";     shift 2 ;;
    --source-only) SOURCE_ONLY=1; shift ;;
    --pages)      PAGES="$2";  shift 2 ;;
    --out)        OUT="$2";    shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$ROOT" ]]; then
  echo "Usage: design-discover.sh --root <dir> [--url <u>] [--source-only] [--pages <list>] --out <dir>" >&2
  exit 1
fi

if [[ -z "$OUT" ]]; then
  echo "Error: --out <dir> is required" >&2
  exit 1
fi

mkdir -p "$OUT"

# ---------------------------------------------------------------------------
# Helper: run source extractor, write profile to $OUT/discovered-tokens.json
# ---------------------------------------------------------------------------
run_source_extractor() {
  local profile
  if profile="$(node "$EXTRACT_SOURCE" --root "$ROOT")"; then
    printf '%s\n' "$profile" > "$OUT/discovered-tokens.json"
  else
    echo "Error: source extractor failed" >&2
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Backend selection
# ---------------------------------------------------------------------------
if [[ -n "$URL" && "$SOURCE_ONLY" -eq 0 ]]; then
  # Try runtime extractor first
  runtime_args=(--url "$URL")
  if [[ -n "$PAGES" ]]; then
    runtime_args+=(--pages "$PAGES")
  fi

  runtime_out=""
  runtime_rc=0
  if runtime_out="$(node "$EXTRACT_RUNTIME" "${runtime_args[@]}" 2>&1)"; then
    runtime_rc=0
  else
    runtime_rc=$?
  fi

  if [[ "$runtime_rc" -ne 0 ]]; then
    # Echo the unavailability signal (it may be embedded in combined output)
    echo "code_health:harmonize_runtime_unavailable"
    # Also surface whatever the runtime extractor printed
    if [[ -n "$runtime_out" ]]; then
      echo "$runtime_out" >&2
    fi
    # Fall back to source extractor
    run_source_extractor
  else
    # Runtime succeeded — write its stdout (JSON) to discovered-tokens.json
    printf '%s\n' "$runtime_out" > "$OUT/discovered-tokens.json"
  fi
else
  # No URL, or --source-only: use source extractor directly
  run_source_extractor
fi

# ---------------------------------------------------------------------------
# Render inventory.md
# ---------------------------------------------------------------------------
PROFILE="$OUT/discovered-tokens.json"

{
  echo "# Design Token Inventory"
  echo ""
  echo "Generated by \`design-discover.sh\`"
  echo ""

  # Source
  src="$(node -e "const p=JSON.parse(require('fs').readFileSync('$PROFILE','utf8')); process.stdout.write(p.source);" 2>/dev/null || true)"
  echo "**Extraction source:** ${src:-unknown}"
  echo ""

  # Inconsistencies
  echo "## Inconsistencies"
  echo ""
  incon_count="$(node -e "
    const p=JSON.parse(require('fs').readFileSync('$PROFILE','utf8'));
    process.stdout.write(String((p.inconsistencies||[]).length));
  " 2>/dev/null || echo "0")"

  if [[ "$incon_count" -eq 0 ]]; then
    echo "No inconsistencies detected."
  else
    node -e "
      const p=JSON.parse(require('fs').readFileSync('$PROFILE','utf8'));
      (p.inconsistencies||[]).forEach(function(item){
        process.stdout.write('- **' + item.category + '**: ' + item.detail + '\n');
      });
    " 2>/dev/null || true
  fi
  echo ""

  # Components (button selectors)
  echo "## Components"
  echo ""
  node -e "
    const p=JSON.parse(require('fs').readFileSync('$PROFILE','utf8'));
    const btns=(p.components&&p.components.button)||[];
    if(btns.length===0){
      process.stdout.write('No button components detected.\n');
    } else {
      btns.forEach(function(b){ process.stdout.write('- ' + b.selector + '\n'); });
    }
  " 2>/dev/null || echo "No component data."
  echo ""

  # Summary counts
  echo "## Token Counts"
  echo ""
  node -e "
    const p=JSON.parse(require('fs').readFileSync('$PROFILE','utf8'));
    process.stdout.write('| Category | Count |\n');
    process.stdout.write('|---|---|\n');
    process.stdout.write('| palette | ' + (p.palette||[]).length + ' |\n');
    process.stdout.write('| type_scale | ' + (p.type_scale||[]).length + ' |\n');
    process.stdout.write('| spacing | ' + (p.spacing||[]).length + ' |\n');
    process.stdout.write('| radii | ' + (p.radii||[]).length + ' |\n');
    process.stdout.write('| shadows | ' + (p.shadows||[]).length + ' |\n');
  " 2>/dev/null || true

} > "$OUT/inventory.md"

echo "discover: wrote $OUT/discovered-tokens.json and $OUT/inventory.md"
